---
title: "벡터 해석의 주요 사항"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 

{{< include ../latexmacros.qmd >}}

</br>

### 참고자료 {.unnumbered}
::: {#refs}


:::

</br>

## 헬름홀츠 정리


::: {.callout-note appearance="minimal"}
엄밀한 의미와 증명에 대해서는 @johns2023helmholtztheoremuniqueness 를 참고하라. 
:::


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-VectorCalculus_hemlhomtz_1}

단순 연결 구간 $X$ 에서 그 내부와 경계에서의 수직방향성분에 대한 divergence 와 curl 을 안다면 벡터장은 이 $X$ 에서 유일하게 정해진다.

:::

</div>

</br>

::: {.proof}

$\bf{P}_1,\, \bf{P}_2$ 가 조건을 만족하는 두 벡터장이라고 하고 $\bf{Q}=\bf{P}_1-\bf{P}_2$ 라고 하자. 조건에 의해 

$$
\nabla\bf{\cdot Q} = 0,\qquad \nabla \times \bf{Q}= \bf{0},\qquad Q_n = 0\;(\text{on the boundary})
$$

이다. 우리는 $\nabla \times \bf{Q}=\bf{0}$ 이면 $\bf{Q}=\nabla \phi$ 인 스칼라장 $\phi$ 가 존재한다는 것을 안다. 따라서 $\nabla \bf{\cdot Q}=\nabla^2 \phi = 0$ 이다. 따라서 
$$
\begin{aligned}
\|\bf{Q}\|^2 = \nabla \phi \bf\cdot \nabla \phi = \nabla (\phi \nabla \phi)- \phi \nabla^2 \phi =\nabla (\phi \nabla \phi)
\end{aligned}
$$


이며, $X$ 의 경계면을 $S$ 라고 하면 

$$
\int_X\|\bf{Q}\|^2\, dv = \int_X\nabla (\phi \nabla \phi)\,dv = \oint_S \phi Q_n \, da = 0
$$

이다. 이것을 만족하는 $\bf{Q}=\bf{0}$ 뿐이므로 $\bf{P}_1=\bf{P_2}$ 이다. 즉 벡터장이 유일하게 결정된다. $\square$

:::

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-VectorCalculus_hemlhomtz}

#### 헬름홀츠 정리

벡터장 $\bf{P}$ 에 대해 $\nabla \bf{\cdot P}$ 와 $\nabla \times \bf{P}$ 가 모두 $\|\bf{r}\|\to \infty$ 극한에서 $1/\|\bf{r}\|$ 보다 빠르게 $0$ 이 된다면 어떤 스칼라장 $\Phi$ 와 벡터장 $\bf{A}$ 에 대해

$$
\bf{P} = -\nabla \Phi + \nabla \times \bf{A}
$$

형태이다. 
:::

</div>

</br>

::: {.proof}
우선 우리는 다음 식이 성립함을 안다. 
$$
\nabla^2 \dfrac{1}{\|\bf{r}\|} = -4\pi \delta(\bf{r})
$$ {#eq-VectorCalculus_hemlhomtz_1}

$s=\nabla \bf{\cdot P},\, \bf{c} = \nabla \times \bf{P}$ 에 대해

$$
\begin{aligned}
\Phi (\bf{r}) &:= \dfrac{1}{4\pi} \int \dfrac{s(\bf{r'})}{\|\bf{r}-\bf{r}'\|}\, d^3\bf{r}' ,\\[0.3em]
\bf{A}(\bf{r}) &:= \dfrac{1}{4\pi}\int \dfrac{\bf{c}(\bf{r'})}{\|\bf{r}-\bf{r}'\|}\, d^3\bf{r}' ,\\[0.3em]
\end{aligned}
$${#eq-VectorCalculus_hemlhomtz_2}

라고 하자. @eq-VectorCalculus_hemlhomtz_1 을 이용하면 

$$
\begin{aligned}
\nabla^2 \Phi(\bf{r}) &= \dfrac{1}{4\pi} \int s(\bf{r}') \nabla^2 \left(\dfrac{1}{\|\bf{r}-\bf{r}'\|}\right) \, d^3\bf{r}' \\
&= \dfrac{1}{4\pi} \int s(\bf{r}') \left[-4\pi \delta(\bf{r}-\bf{r}')\right] \, d^3\bf{r}' = -s(\bf{r}).
\end{aligned}
$${#eq-VectorCalculus_hemlhomtz_3}

이다. $\bf{A}$ 에 대해 비슷하게 하기 위해 다음의 항등식을 이용한다.

$$
\nabla \times (\nabla \times \bf{A}) = \nabla (\nabla \bf{\cdot A}) - \nabla^2 \bf{A}
$$

$\nabla (f\bf{A})= \nabla f \bf{\cdot A} + f \nabla \cdot \bf{A}$ 임을 이용한다. 
$$
\begin{aligned}
\nabla(\nabla \cdot \bf{A}(\bf{r})) &= \dfrac{1}{4\pi}\nabla\left[\int \nabla \bf{\cdot}\left(\dfrac{\bf{c}(\bf{r}')}{\|\bf{r}-\bf{r}'\|}\right)\right]\,d^3\bf{r}' \\[0.3em]
&= \dfrac{1}{4\pi}\nabla \int \left[\bf{c}(\bf{r}') \cdot \nabla\left(\dfrac{1}{\|\bf{r}-\bf{r}
'\|}\right)\right] \, d^3\bf{r}'\\[0.3em]
&=\dfrac{1}{4\pi}\nabla \int \left[\bf{c}(\bf{r}') \cdot \left(-\nabla'\left(\dfrac{1}{\|\bf{r}-\bf{r}
'\|}\right)\right]\right) \, d^3\bf{r}'\\[0.3em] 
&= \dfrac{1}{4\pi} \left[ -\int \nabla' \left(\dfrac{\bf{c}(\bf{r}')}{\|\bf{r}-\bf{r}'\|}\right) \, d^3\bf{r}' + \int \dfrac{\nabla \bf{\cdot c}(\bf{r}')}{\|\bf{r}-\bf{r}'\|} \, d^3\bf{r}' \right]
\end{aligned}
$$

여기서 첫번째 적분은 $\oint_S \bf{c}/\|\bf{r}-\bf{r}'\| \cdot \bf{n}\, da$ 이며 경계 조건에 의해 $\bf{0}$ 이 된다. 또한 $\bf{c}= \nabla \times \bf{P}$ 이므로 $\nabla \bf{\cdot \bf{c}} = \nabla \bf{\cdot}(\nabla \times \bf{P})=\bf{0}$ 이다. 즉 $\nabla(\nabla \cdot \bf{A}(\bf{r})) = \bf{0}$ 이다. 

이제 $\nabla^2\bf{A}$ 를 구해보자. @eq-VectorCalculus_hemlhomtz_1 을 이용하면

$$
\begin{aligned}
\nabla^2 A_j(\bf{r}) = \dfrac{1}{4\pi} \int c_j(\bf{r}')\nabla^2 \left(\dfrac{1}{\|\bf{r}-\bf{r}'\|}\right)\, d^3 = -c_j(\bf{r})
\end{aligned}
$$

임을 안다. 즉 $\nabla \times (\nabla \times \bf{A})= \bf{c}$ 이다. 


:::