project:
  type: book
  output-dir : docs

book:
  title: "수리물리학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true
  reader-mode: true


  chapters:
    - index.qmd
    - part : 벡터해석
      chapters: 
        - src/vector calculus/vectorcalculus.qmd
    - part : 텐서 해석
      chapters :
      - src/tensor/tensor01.qmd
      - src/tensor/tensor02.qmd
    - part : 군과 대칭
      chapters :
      - src/group/group01_introduction.qmd
      - src/group/group02_representation.qmd
      - src/group/group02_representation_2.qmd
      - src/group/group03_quantum.qmd
    - part: 미분방정식
      chapters :
      - src/differential equation/ode.qmd
      - src/differential equation/pde.qmd

    - part: 복소함수
      chapters :
      - src/complex/complex1.qmd
      - src/complex/complex2.qmd
      - src/complex/complex3.qmd

    # - src/figure/figure1.qmd
    # - src/figure/figure-test.qmd


bibliography: references.bib

format:
  html:
    # title-block-banner: true
    # include-in-header: 
    #   - html-hacks/load-font-awesome.html
    #   - html-hacks/load-xkcd-font.html
    # resources: web-resources/**
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    # theme: darkly
    theme: 
      - cosmo
    #  - r4ds.scss
    #include-in-header: "plausible.html"
    fontsize: 0.85em
    #toc: true
    collapse: true
    # css: styles.css
    number-sections: true
  
# filters:
#   - diagram


