project:
  type: book

book:
  title: "수리물리학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd
    - src/complex1.qmd
    - src/complex2.qmd
    - src/figure/figure1.qmd
    - src/figure/figure-test.qmd
    

bibliography: references.bib

format:
  html:
    title-block-banner: true
    # include-in-header: 
    #   - html-hacks/load-font-awesome.html
    #   - html-hacks/load-xkcd-font.html
    # resources: web-resources/**
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    # theme: darkly
    theme: cosmo
    fontsize: 0.9em
    toc: true
    collapse: true
    # css: styles.css
    number-sections: true
  
# filters:
#   - diagram


