---
title: "상미분 방정식"

number-sections: true
number-depth: 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

</br>

## 기본 개념

미분방정식에서는 여러 용어들이 일반적인 방정식이나 다항삭과 다르게 사용된다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-DE_basic_definitions}

#### 미분방정식의 기본 개념

- 하나의 독립변수에 대한 미분방정식을 **상미분 방정식 (ordinary differential equation, ODE)** 이라고 하며, 여러 독립변수에 대한 미분방정식을 **편미분 방정식 (partial differential equation, PDE)** 라고 한다.
  
- 미분 연산을 포함하는 연산자를 **미분 연산자 (differential operator)** 라고 한다. 미분 연산자 $\mathcal{L}$ 가 미분 가능한 함수 $f,\,g$ 와 상수 $a$ 에 대해 
$$
\mathcal{L}(af(x) + g(x)) = a \mathcal{L}(f(x)) + \mathcal{L}(g(x))
$$ 
를 만족하면 $\mathcal{L}$ 을 **선형 미분 연산자(linear differential operator)** 라고 한다.  

- 일반적으로 미분방정식은 미분연산자 $\mathcal{L}$ 과 함수 $F(x)$ 에 대해 다음의 꼴로 주어진다.
$$
\mathcal{L}(f(x)) = F(x)
$$ {#eq-diff_eq_basic}

- @eq-diff_eq_basic 에서 $\mathcal{L}$ 이 선형미분연산자이고 $F(x)$ 가 미분연산자를 포함하지 않은 $x$ 의 함수 일 때 이 미분방정식을 **선형미분방정식(linear differential equation)**이라고 한다.


- 상미분방정식이 $y=y(x)$ 에 대해 주어졌다고 하자. **계수 (order)** 는 $y$ 의 최고차 도함수의 차수이며  **차수 (degree)** 는 $y$ 의 최고차 도함수의 승수이다. 예를 들어 $(y''')^4 + y^5 = F(x)$ 형태의 미분방정식이라면 계수는 3 이며 차수는 4 인 3계 4차 미분방정식이 된다. 


- 미분방정식의 각각의 항이 독립변수에 대한 함수와 종속변수의 미분의 곱으로만 이루어 졌을 때 이 미분방정식을 **제차 미분방정식 (homogeneous differential equation)** 이라고 한다. (see @exm-DE_homogeneous_function_and_differential_equation)

:::
:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_homogeneous_function_and_differential_equation}
#### Homogeneity
</br>

**일반적인 함수의 경우**

$n$ 개의 독립변수를 가진 함수 $f(x_1,\ldots,\,x_n)$ 가 어떤 $k$ 에 대해 

$$
f(tx_1,\ldots,\,tx_k) = t^k f(x_1,\ldots,\,x_k)
$$ 

를 만족할 때 이 함수를 **계수가 $k$ 인 동차 함수(homogeneous function of order $k$)** 라고 한다. 

</br>

**미분방정식의 경우**

예를 들어 아래와 같은 형태의 미분방정식에서 $F(x) = 0$ 이면 이 제차 미분방정식이다. 

$$
\sum_{k=0}^N a_k(x) y^{(k)}(x) = F(x).
$$

:::

</div></br>

### 선형 동차 상미분 방정식 (LHODE) {#sec-DE_ODE_lhode}

선형이며 동차인 미분연산자 $\mathcal{L}$ 과 함수 $F$ 에 대해 다음과 같이 주어졌다고 하자.

$$
\mathcal{L}(f(x)) = F(x).
$$

$F(x)=0$ 이면 이 미분방정식은 선형이며 동차인 미분방정식이다. 많은 경우 선형 제차 미분방정식의 해를 얻는 것이 매우 중요하다. 그 이유중 하나는 위의 미분방정식의 해 $\psi$ 를 얻었고, homogeneous 한 방정식의 해 $\phi$ 를 얻었다면 $\phi + \psi$ 도 항상 위의 방정식의 해이기 때문이다. 이제 선형 제차 상미분 방정식(linear homogeneous ordinary differential equation) 을 **LHODE** 라고 줄여 쓰기로 하자. 그리고 선형 제차 상미분 연산자 (linear homogeneous ordinary differential operator) 를 **LHODO** 라고 줄여 쓰기로 하자.

</br>

#### **중첩 원리** 

LHODE $\mathcal{L}(f(x))=0$ 의 해는 보통 여러개이며 그것의 선형결합 역시 해이다. 즉 $\mathcal{L}\psi = 0$, $\mathcal{L}\phi  = 0$ 이면 임의의 $a,\,b$ 에 대해 $\mathcal{L}(a\psi + b \phi) = 0$ 이다. 이것을 **중첩 원리 (superposition principle)** 이라고 한다.  

</br>

## 1계 ODE

미분방정식이 아래와 같은 형태로 주어졌다고 하자.

$$
\dfrac{dy}{dx} = - \dfrac{P(x,\,y)}{Q(x,\,y)}.
$$ {#eq-DE_typical_1_deg_ode}

이런 미분방정식을 일반적으로 푸는 방법은 없으며, 여기서는 많이 사용되는, 특정한 경우에 사용되는 방법을 알아보도록 하자.

</br>

### 변수 분리 {#sec-DE_separable_equations_for_1degree_ode}

가장 간단한 경우 가운데 하나로 미분방정식이 

$$
\dfrac{dy}{dx} = \dfrac{-P(x)}{Q(y)}
$$

로 주어졌을 경우 이다. 그렇다면 아래의 적분을 통해 구할 수 있다. 그렇다면 이 식은 아래와 같이 쓸 수 있다.

$$
P(x)\,dx + Q(y)\,dy = 0.
$$

위 식을 $(x_0,\,y_0)$ 에서 $(x,\,y)$ 까지 적분하면 아래의 식을 얻는다. 

$$
\int_{x_0}^x P(x')\,dx' + \int_{y_0}^y Q(y')\,dy' = 0.
$$

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_drafting_falling}

#### 마찰이 있는 낙하 

마찰이 있는 낙하의 경우 시간 $t$ 와 위치 $x$ 에 대해 미분방정식이 아래와 같이 주어진다. $\dot{x}=v$ 라고 하자.

$$
m\dot{v} = mg - bv^2.
$$

그리고 초기 조건으로 $v(0)=0$ 라고 하자. $mg=bv_0^2$ 으로 놓으면

$$
\dfrac{m}{b}\dot{v} = v_0^2 -v^2
$$

이며

$$
\left(\dfrac{1}{v_0-v} + \dfrac{1}{v_0+v}\right)dv = \dfrac{2v_0 b}{m}dt
$$

이다. 이를 적분하면

$$
\ln \dfrac{v_0 + v}{v_0 - v} = \dfrac{2v_0 b}{m}t
$$

이다. $\tau:= v_0b/m$ 에 대해 $v(t)$ 를 아래와 같이 얻는다.

$$
v= v_0 \tanh (t/\tau)
$$

:::
</div>
</br>

### 완전 미분방정식의 경우 {#sec-DE_ode_exact_differential}

@eq-DE_typical_1_deg_ode 을 다음과 같은 형태로 쓰자.

$$
P(x,\,y)\,dx + Q(x,\,y)\,dy = 0
$$ {#eq-DE_typical_1_deg_ode_2}

이 미분방정식이 어떤 $\Phi(x,\,y)$ 에 대해

$$
d\Phi = \dfrac{\partial \Phi}{\partial x}\,dx + \dfrac{\partial \Phi}{\partial y}\,dy = P(x,\,y)\,dx + Q(x,\,y)\,dy
$$ {#eq-DE_typical_1_deg_ode_exact_form}

일 때, 이 마분방정식을 **전미분 형태** 라고 한다. 즉 위의 미분 방정식은 $d\Phi (x,\,y) = 0$ 인 해 $\Phi$ 를 찾는 것이며 따라서 

$$
\Phi(x,\,y) = C = \text{constant}
$$

형태의 해를 찾는 것이다.

$\Phi(x,\,y)$ 가 $C^2$ 급 함수라면 $\dfrac{\partial^2 \Phi}{\partial x \partial y} = \dfrac{\partial^2 \Phi}{\partial y \partial x}$ 이므로

$$
\dfrac{\partial P}{\partial y} = \dfrac{\partial Q}{\partial x} = \dfrac{\partial^2 \Phi}{\partial x \partial y}
$${#eq-DE_typical_1_deg_ode_exact_form_2}

이다. 또한 @eq-DE_typical_1_deg_ode_2 의 미분방정식과 조건 @eq-DE_typical_1_deg_ode_exact_form_2 이 주어졌을 때 이 미분방정식은 전미분 형태임을 보일 수 있다. $P(x,\,y) = \dfrac{\partial \Phi}{\partial x}$ 로부터

$$
\Phi = \int_{x_0}^x P(x',\,y)\,dx' + f(y)
$$

이다. 그렇다면

$$
\begin{aligned}
\dfrac{\partial \Phi}{\partial y} &= \int_{x_0}^x \dfrac{\partial P(x',\,y)}{\partial y}\, dx' + \dfrac{\partial f}{\partial y} = \int_{x_0}^x \dfrac{\partial Q(x',\,y)}{\partial x'}\,dx' + \dfrac{\partial f}{\partial y} \\[0.3em]
&=Q(x,\,y) -Q(x_0,\,y) + \dfrac{\partial f}{\partial y}= Q(x,\,y) 
\end{aligned}
$$

이므로 $x_0$ 를 $Q(x_0,\,y) = \partial f/\partial y$ 가 되도록 잡아야 한다. 그렇다면 어떤 상수 $C_f$ 에 대해

$$
f(x,\,y) = \int_{y_0}^y Q(x_0,\,y')\,dy' + C_f
$$

이며, 따라서

$$
\Phi(x,\,y) = \int_{x_0}^x P(x',\,y)\,dx' + \int_{y_0}^y Q(x_0,\,y')\,dy' = \text{const.}
$$

이다.

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_nonseparable_exact}

아래와 같이 주어진 미분방정식을 생각하자.

$$
\dfrac{dy}{dx} = -1 - \dfrac{y}{x}.
$$

양변에 $x\,dx$ 를 곱하면 $(x+y)dx + xdy = 0$ 이며 $\partial (x+y)/\partial y = \partial x/\partial x = 1$ 이므로 전미분 형태이다. 그렇다면

$$
\begin{aligned}
\Phi(x,\,y) &= \int_{x_0}^x (x'+y)\,dx' + \int_{y_0}^y x_0 \,dy' = \dfrac{x^2}{2} + xy + C_f
\end{aligned}
$$

이므로 미분방정식의 해는 다음과 같다.

$$
\Phi(x,\,y) = \dfrac{x^2}{2}+xy=\text{const.}
$$

:::
</div>
</br>

$P(x,\,y)\,dx+Q(x,\,y)\,dy=0$ 꼴인 미분방정식이 전미분 형태가 아니지만 적분 인자 $\alpha(x,\,y)$ 를 곱했을 때

$$
\alpha(x,\,y)P(x,\,y)\,dx+\alpha(x,\,y)Q(x,\,y)\,dy=0
$$

가 전미분 형태가 되면 위의 방법을 이용하여 해를 구할 수 있다. 적분 인자는 최소한 하나 이상 존재하지만 선형 1계 미분방정식을 제외하면 적분 인자를 체계적으로 구하는 방법은 존재하지 않는다. 이에 대해서는 다음에 다루기로 하자.

</br>

### 1계 제차 상미분방정식의 경우 {#sec-DE_ODE_order_1_homogeneous_case}

1계 제차 상미분 방정식의 경우 각 항애서 $x,\,y,\,dx,\,dy$ 의 곱의 승수가 동일하다. 이 경우 $y=vx$ 놓고 $x$ 와 $v$ 에 대한 미분방정식 형태로 바꾼 후 변수분리를 통해 풀 고 다시 $x,\,y$ 에 대한 함수형태로 바꿀 수 있는 경우가 있다.


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_order_1_homogeneous_case}

아래와 같이 주어진 미분방정식을 생각하자.

$$
(2x+y)\,dx + xdy = 0
$$

$y=xv$ 로 놓으면 $dy = xdv + vdx$ 이며 미분방정식은 아래의 형태가 된다.

$$
(2v+2)\,dx + xdv = 0
$$

이 미분방정식의 해는 

$$
\ln x + \dfrac{1}{2} \ln (v+1)= C
$$

이며 $y=xv$ 이므로

$$
y = \dfrac{C}{x}-x
$$

이다.

:::
</div>
</br>

제차 상미분 방정식이 아니지만 $y=vx^m$ 으로 놓을 경우 $x,\,v$ 에 대한 제차 상미분 방정식꼴이 될 수 있다.

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_order_1_homogeneous_case}

아래와 같이 주어진 미분방정식을 생각하자.

$$
(x^2-y)\,dx + xdy = 0
$$

$y=vx^2$ 으로 놓으면

$$
0 = x^2 \,dx - vx^2 dx + 2vx^2dx + x^3dv = (1+v)x^2dx + x^3dv
$$

이며 이로부터

$$
(1+v)dx + xdv = 0
$$

을 얻는다. 즉

$$
\dfrac{dx}{x} + \dfrac{dv}{1+v}=0
$$

이므로

$$
x(1+v)= C \,(\text{constant})
$$

이다. 이로부터 방정식의 해를 다음과 같이 얻는다.

$$
y=Cx-x^2
$$

:::
</div>
</br>

### 1계 선형 상미분 방정식 {#sec-DE_ODE_1olde}

1계 선형 상미분 방정식은 일반적으로 다음과 같은 형태로 주어진다.

$$
y' + p(x)y = q(x).
$$ {#eq-DE-ODE_genral_1dgree_LHODE_form}

위 식이 전미분 형태이면 @sec-DE_ode_exact_differential 에서 소개한 방법으로 쉽게 풀 수 있으며 여기서는 전미분 형태가 아닌 경우에만 다룬다. 여기서는 적분 인자 $\alpha(x)$ 를 도입하여 아래 식이 전미분 형태가 되도록 조작하고자 한다.

$$
\alpha(x)y' + \alpha (x)p(x)y = \alpha(x)q(x)
$$

이를 위해


$$
\dfrac{d}{dx}\left(\alpha (x)\,y(x)\right) = \alpha(x) y'(x) + \alpha (x)p(x)y(x)
$$

가 되는 $\alpha(x)$ 를 어쨌든 구했다고 하자. 그렇다면 원래의 미분방정식은

$$
\dfrac{d(\alpha y)}{dx} = \alpha q
$${#eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor}

가 되며, 조건으로 보면 아래를 만족시키게 된다.
$$
\alpha' y  =  \alpha p y
$$ 

이며, 위 식을 전개하면 다음을 얻는다.

$$
\dfrac{d\alpha}{\alpha} = p(x)\,dx.
$$

당연히 $\alpha(x)$ 는 적당한 초기값에 대해 아래와 같다.

$$
\alpha(x) = \alpha_0\exp \left(\int_{x_0}^x p(x)\,dx\right)
$$

그렇다면 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 로부터

$$
\alpha(x) y(x) = \int^x \alpha(x') q(x')\,dx' + C
$$

이며, 따라서

$$
y(x) = \dfrac{1}{\alpha(x)} \left[\int^x \alpha(x') q(x')\,dx' + C\right]
$$

이다. 여기서 $y_1,\,y_2$ 를 다음과 같이 정하자.

$$
y_1 := \dfrac{1}{\alpha(x)} \int^x \alpha (x')q(x')\,dx',\qquad y_2 := \dfrac{C}{\alpha(x)}.
$$

그렇다면 $y=y_1+y_2$ 이며, 

$$
y_2' + py = 0
$$

이다. 즉 $y_2$ 는 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 의 $q(x)=0$ 인 제차 미분방정식의 해이다. 반면 $y_1$ 은 $q(x)$ 를 포함한 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 을 만족한다. 

이것은 어찌 보면 당연한데 비 제차 미분방정식의 해는 제차 형태의 미분방정식의 해(일반해, general solution) 들의 선형결합과 비제차 미분방정식의 해(특이해, particular solution)의 합이다. 




<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-DE_ODE_summary}

1계 선형 미분방정식에 대해 다음이 성립한다.

($1$) 비 제차 1계 선형 미분방정식의 해는 제차 미분방정식의 선형결합을 제외하면 유일하게 결정된다.

($2$) 제차 1계 선형 미분방정식은 유일한 선형 독립 해를 가진다.


:::
</div>

::: {.proof}

($1$) $y_1,\,y_2$ 가 미분방정식 $y'+py=q$ 두 해라고 하자. 즉 $y_1'+py_1=q,\, y_2'+py_2=q$ 이면 $(y_1'-y_2')+p(y_1'-y_2') = 0$ 이며 따라서 $y_1'-y_2'$ 은 주어진 미분방정식의 제차 형태의 해이므로 특이해는 제차 미분방정식의 선형결합을 제외하면 유일하게 결정된다.

($2$) $y_1,\,y_2$ 가 제차 미분방정식 $y'+py=0$ 의 선형독립인 두 해라고 하자. 그렇다면 $y_1'/y_1 = y_2'/y_2 = -p(x)$ 이며 이로부터 어떤 상수 $C$ 에 대해 $y_1=Cy_2$ 인데 이는 선형독립인 가정에 모순이다. $\square$

:::

</br>

#### **매개변수 변환법**

1계 상미분 방정식 $y'+py=q$ 의 해를 구하는 한 방법이다. 우선 제차 형태인 $y'+py=0$ 해 $y_h$ 를 구하면

$$
y_h = C \exp \left(-\int^x p(x')\,dx'\right)
$$

이다. 여기서 $C$ 를 상수가 아닌 $x$ 에 대한 함수로 놓고 특이해를 구할 수 있는 경우가 있다. 즉 $C\to C(x)$ 로 변환한 $y_h$ 를 $y$ 로 놓고 $y'$ 을 구하면

$$
\begin{aligned}
y' &= \exp \left(-\int^x p(x')\,dx'\right)\left(-p(x)C(x) + C'(x)\right) \\[0.3em]
&= -p(x)y(x) + C'(x) \exp \left(-\int^x p(x')\,dx'\right)
\end{aligned}
$$

이며 따라서

$$
C'(x)\exp\left(-\int^x p(x')\,dx'\right) = q(x)
$$

이다. 그렇다면 특이해 $y_p$ 는 아래와 같다.

$$
y_p = C(x) \exp \left(-\int^x p(x')\,dx'\right),\quad \text{where } C(x) = \int^x \exp \left(\int^{x'} p(x')\,dx' \right) q(x'')\,dx''.
$$

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_2}

#### Arfken 7.2.3

베셀 방정식 ($n=0$) 의 라플라스 변환을 통해 아래 식을 얻는다. $f(s)$ 를 구하라.

$$
(s^2+1)f'(x) + sf(x) = 0.
$$

:::

</div>

::: {.solution}

$\dfrac{f'(x)}{f(s)} = - \dfrac{s}{s^2+1}$ 로부터 $\ln f(s) = - \dfrac{1}{2}\ln s+C$ 를 얻는다. 따라서 $f(s) = C\sqrt{s^2+1}$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_3}

#### Arfken 7.2.3

Catastrophic two-body collisions 에 의한 decay of populiation 은 아래의 1계 비선형 미분방정식에 의해 기술된다.

$$
\dfrac{dN}{dt} = -kN^2.
$$

$\tau_0 = (kN_0)^{-1}$ 에 대해 이 미분방정식의 해가 를 유도하고 다음과 같음을 보여라.

$$
N(t) = N_0 \left(1+ \dfrac{t}{\tau_0}\right)^{-1}.
$$

:::

</div>

::: {.solution}

$\dfrac{dN}{N^2} = -k\,dt$ 를 적분하면

$$
- \dfrac{1}{N(t)}+ \dfrac{1}{N_0} = -kt
$$

이며 문제의 해를 얻는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_6}

#### Arfken 7.2.6

1계 미분방정식 $\dfrac{dy}{dx}=f(x,\,y)$ 에서 함수 $f(x,\,y)$ 는 $y/x$ 의 함수이다. 즉 $\dfrac{dy}{dx}=g(y/x)$ 이다. $u=y/x$ 치환에 의해 이 미분방정식은 $u,\,x$ 에 대해 분리가능한 방정식이 됨을 보여라.

:::

</div>

::: {.solution}

$y=ux$ 이므로 $\dfrac{dy}{dx}= u + x\dfrac{du}{dx}$ 이다. 주어진 미분방정식은 $x,\,y$ 에 대해 $u+xu' = g(u)$ 이므로 아래와 같이 분리가능한 미분방정식을 얻는다.

$$
\dfrac{dx}{x} = \dfrac{du}{g(u)-u}.
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_10}

#### Arfken 7.2.10

아래와 같이 주어진 미분방정식에서 $f,\,g,\,h$ 는 $0$ 이 아니다. 

$$
f(x)\,dx + g(x)h(y)\,dy = 0.
$$

이 식이 전미분 형태가 될 필요충분조건은 $g(x)=\text{constant}$ 임을 보여라.

:::

</div>

::: {.solution}

$g(x)=\text{constant}$ 이면 전미분 형태임. 이제 방정식이 전미분 형태임을 가정하면

$$
\dfrac{\partial f(x)}{\partial y} = \dfrac{\partial g(x)h(y)}{\partial x} =0
$$

이어야 하므로 $g'(x)=0$. 즉 $g(x)=\text{constant.}$.


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_11}

#### Arfken 7.2.11

$$
y(x) = \exp \left[-\int^x p(t)\,dt\right] \left(\int^x \left[\int^s p(t)\,dt\right]\,q(s)\,ds + C\right)
$$

가 아래의 미분방정식의 해임을 보여라.

$$
\dfrac{dy}{dx}+p(x)y(x) = q(x).
$$

:::

</div>

::: {.solution}

주어진 식으로부터
$$
\begin{aligned}
y' &= - p(x) y(x)+ \left(\left[\int^x p(t)\,dt\right]\,q(x)\,ds\right)y(x)
\end{aligned}
$$

:::


</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_sho1}

#### 단순조화진동자 
LHODE $y'' + \omega^2 y = 0$ 을 보자. $y=e^{\lambda x}$ 라고 놓으면, $\lambda^2+\omega^2 = 0$ 이어야 하므로 $\lambda = \pm \omega i$ 이다. 임의의 $a,\,b \in \mathbb{C}$ 에 대해 $a e^{i\omega x} + be^{-i\omega x}$ 는 미분방정식의 해이다.
:::

</div></br>


## 계수가 상수인 ODE 의 경우

미분방정식이 다음과 같은 꼴로 주어졌다고 하자.

$$
\dfrac{d^ny}{dx^n} + a_{n-1} \dfrac{d^{n-1}y}{dx^{n-1}} + \cdots + a_1 \dfrac{dy}{dx} + a_0 y = F(x).
$$ {#eq-constant_coefficients_ode}

위 미분방정식은 $n$-계 선형 미분방정식이다. 이 경우 $y=e^{mx}$ 를 놓으면 일반해, 즉 $F(x)=0$ 일 경우의 해를 구할 수 있다. 

$$
(m^n + a_{n-1}m^{n-1} + \cdots + a_n m + a_0)e^{mx}=0
$$

이며 이를 만족 하는 $m$ 은 복소수에서 $n$ 개 존재한다. 

</br>



## 2계 선형 ODE

### Singularity {#sec-DE_ODE_sigularity}

가장 간단한 다음 꼴의 2계 ODE 를 보자.

$$
y''  + p(x) y' + q(x) y  = 0
$$ {#eq-simple_2nd_ode}

이 식은 모든 항에서 $y$ 와 그 도함수가 1차이므로 homogeneous 하다. $p(x)$ 와 $q(x)$ 가 유한한 값을 가질 때 이 $x$ 를 **ordinary point** 라고 하며 그렇지 않을 때는 **singular point** 라고 한다. $x_0$ 가 singular point 일 때  

$$
\lim_{x\to x_0} |(x-x_0)p(x)|<\infty, \qquad \lim_{x\to x_0} |(x-x_0)q(x)|<\infty
$$ 

이면 **regular singularity** 라고 하며 그렇지 않을 때 **irregular singularity** 혹은 **essential singularity** 라고 한다. 


$x\to \infty$ 나 $x \to -\infty$ 의 경우에는 $z=1/x$ 로 치환하여 미분방정식을 $z$ 에 대한 미분방정식으로 바꾼다. $w(z) = y(z^{-1})$ 이라면, 

$$
\begin{aligned}
y'(x) &= \dfrac{dy}{dz} \dfrac{dz}{dx} = - \dfrac{1}{x}^2 \dfrac{dw}{dz} = -z^2w', \\
y'' (x) &= \dfrac{dy'}{dz}\dfrac{dz}{dx} = z^4 w'' + 2z^3 w'
\end{aligned}
$$


이므로 @eq-simple_2nd_ode 는 다음과 같이 변형된다.

$$
4zw'' + \left[ 2z^3 - z^2 p(1/z) \right] w' + q(z^{-1}) w = 0.
$$ {#eq-DE_ODE_modified_simplie_2nd_ode}

</br>

### 중요한 2계 선형 미분방정식 {#sec-DE_ODE_important_differential_equations}


| 이름 | 방정식 | regular singularity | irregular singularity|
|:-----:|:----------------------------|:------------:|:------------:|
| Hypergeometric | $x(x-1) y'' + [(1+a+b)x + c]\,y' +aby=0$ | $0, 1 \infty$ | |
| Legendre | $(1-x^2) y'' -2xy' + l(l+1)y=0$ | $-1, 1, \infty$ | |
| Chebyshev | $(1-x^2) y'' -xy' + n^2y = 0$ | $-1, 1, \infty$ | |
| Confluent hypoergeometryc | $xy'' + (c-x)y' -ay = 0$ | $0$ | $\infty$ |
| Bessel | $x^2y'' + xy' + (x^2-n^2)y = 0$ | $0$ |$\infty$ |
| Laguerre | $xy'' + (1-x)y' + a y = 0$ | $0$ | $\infty$ |
| SHO | $y'' + \omega^2 y' = 0$ | | $\infty$ |
| Hermite | $y'' -2xy' + 2\alpha y = 0$ | | $\infty$ |

: 중요한 2계 선형 ODE 와 singularity {#tbl-2nd_ode_singularity}


대표적으로 르장드르 함수 $(1-x^2) y'' -2xy' + l(l+1)y=0$ 를 보자. 르장드르 함수는

$$
y'' - \dfrac{2xy}{1-x^2} y' + \dfrac{l(l+1)}{1-x^2} y = 0
$$
 
으로 $x=\pm 1$ 에서 regular singularity 를 가진다. 

</br>

### Frobenius 방법을 이용한 급수해 {#sec-DE_ODE_power_series_soluiton}

@eq-simple_2nd_ode 꼴로 주어진 2계 LHODE 를 생각하자. 이 경우 $y$ 를 $x$ 의 급수로 놓고 해를 구하는 것을 Frobenius 방법이라고 한다. 즉,

$$
y(x) = \sum_{i=0}^\infty a_i x^{s+i} ,\qquad a_0 \ne 0
$$ {#eq-ode_expansion_about_zero}

로 놓고 미분방정식에 대입하여 계수 $a_i$ 와 $s$ 를 구한다. 이 때 $a_0 \ne 0$ 임에 유의하라. 

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-ode_frobenius_sho}

#### 단순조화진동자의 경우

예를 들어 $y'' + \omega^2 y = 0$ 의 경우, 

$$
\begin{aligned}
&\sum_{i=0}^\infty a_i (s+i)(s+i-1)x^{s+i-2} + \omega^2 \sum_{i=0}^\infty a_j x^{s+i} = 0 \\
\implies & a_0 s(s-1)x^{s-2} + a_1 (s+1)s x^{s-1} \\[0.3em]
&\qquad \qquad \qquad + \sum_{i=0}^\infty \left[a_{i+2}(s+i+2)(s+i+1) +\omega^2 a_j\right]x^{s+i} = 0
\end{aligned}
$$

이로부터 우리는 세가지 조건을 얻는다.

&emsp; ($1$) $a_0 s(s-1) =0$, 

&emsp; ($2$) $a_1s(s+1) = 0$, 

&emsp; ($3$) $a_{i+2}(s+i+2)(s+i+1) + \omega^2 a_j = 0$

$a_0\ne 0$ 이므로 ($1$) 의 조건에 의해 $s(s-1)=0$ 이어야 한다. 이 방정식은 $s$ 를 결정하는 중요한 방정식으로 **indicial equation** 이라고 한다. ($2$) 의 조건에서 $s=-1$ 일 경우 $a_0 = 0$ 이어야 하므로 조건에 위배된다. 따라서 남은 조건은 $s=0$ 이고 $a_1$ 을 자유로 두거나, $s=1$ 이며 $a_1=0$ 으로 두는 것 밖에 없다. 그리고 ($3$) 조건에 의해, 

$$
a_{i+2} = \dfrac{-\omega^2}{(i+1)(i+2)}a_i \implies  a_{2k} = (-1)^n \dfrac{\omega^{2k}}{(2k)!} a_0,\, a_{2k+1} = (-1)^n \dfrac{\omega^{2k}}{(2k+1)!} a_1
$$

를 만족해야 한다. $s=0$ 일 경우, 

$$
\begin{aligned}
y(x){\large\mid}_{s=0} &= a_0 \left[ \sum_{k=0}^\infty \dfrac{(-1)^k (\omega)^{2k}}{(2k)!} x^{2k} \right] + a_1 \left[ \sum_{k=0}^\infty \dfrac{(-1)^k (\omega)^{2k}}{(2k+1)!} x^{2k+1} \right]\\[0.3em]
&= a_0 \cos (\omega x) + \dfrac{a_1}{\omega} \sin (\omega x)
\end{aligned}
$$

이다. $s=1$ 인 경우는 같은 방법으로

$$
y(x) {\large \mid}_{s=1} =  \dfrac{a_0}{\omega}\sin (\omega x)
$$

임을 알 수 있다. 
:::

</div></br>

### $x_0$ 주위로의 멱급수 전개

@eq-ode_expansion_about_zero 는 $x_0=0$ 근처의 전개이다. 이것을 임의의 $x_0$ 근처에서 다음과 같이 전개하여 미분방정식의 해를 구하는 것도 가능하다.

$$
y(x) = \sum_{i=0}^\infty a_i (x-x_0)^{s+i} ,\qquad a_0 \ne 0
$$

$x_0$ 를 regular singularity 로 잡으면 많은 경우 미분방정식의 해를 찾는 데 유용하지만 irregular siglularity 의 경우는 Frobenius 방법으로 해를 구할 수 없다.

</br>

### Fuchs' theorem {#sec-DE_ODE_fuchs_theorem}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-fuchs}

#### Fuch 의 정리

아래와 같은 꼴의 미분방정식을 생각하자.

$$
\displaystyle y''+p(x)y'+q(x)y=F(x)
$$

이 방정식은 $p(x),\, q(x),\, F(x)$ 가 $x=a$ 에서 해석적 이거나 $a$ 가 regular singular point 라면 프로베니우스 방법에 의한 해를 가진다. 즉 이 미분방정식의 $x=a$ 근처의 해는 어떤 양수 $s$ 에 대해 

$$
y_1=\sum _{n=0}^{\infty }a_{n}(x-a)^{n+s},\quad a_{0}\ne 0
$$

이거나 $y_1$ 함수에 $\ln (x-a)$ 를 곱한것과 다른 $y_1$ 꼴의 함수를 더한 아래의 형태이다.

$$
y=y_1\ln(x-a)+\sum _{n=0}^{\infty }b_{n}(x-a)^{n+r},\quad b_{0}\neq 0.
$$

:::


</div></br>

## 알고 있는 해로부터 해를 더 구하는 법

</br>

### 함수의 벡터공간

구간 $I$ 에서 $n-1$ 번 미분 가능한함수의 집합은 벡터공간을 이루며 따라서 함수에 대한 선형 독립을 정의 할 수 있다. 또한 이 벡터공간에 적절한 내적을 정하여 내적벡터공간으로 구성하면 함수 사이의 직교성(orthogonality) 도 생각 할 수 있다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-DE_ODE_wronskian}

#### Wronskian

어떤 구간 $I$ 에서 정의된 $n-1$ 번 미분 가능한 함수 $\varphi_1,\ldots,\,\varphi_n$ 에 대해 다음 과 같이 정의된 행렬식을 **Wronskian** 이라고 한다.

$$
W[\varphi_1,\ldots,\,\varphi_n] = W[\{\varphi_i\}]:= \det \left(\begin{bmatrix} \varphi_1 & \varphi_2 & \cdots &\varphi_n \\ \varphi'_1 & \varphi'_2 & \cdots & \varphi'_n \\ \vdots  & & &\vdots \\ \varphi^{(n-1)}_1 & \varphi^{(n-1)}_2 & \cdots & \varphi^{(n-1)}_n\end{bmatrix}\right)
$$

:::
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-DE_ODE_wronskian_1}

@def-DE_ODE_wronskian 의 Wronskian 에 대해 다음이 성립한다.

&emsp; ($1$) $W[\{\varphi_i\}]\ne 0$ 이면 $\{\varphi_i\}$ 는 선형독립이다.

&emsp; ($2$) $W[\{\varphi_i\}] = 0$ 이면 $\{\varphi_i\}$ 는 선형종속이다.

:::
</div>

::: {.proof} 

$\{\varphi_i\}$ 에 대해 

$$
a_1 \varphi_1  + \cdots + a_n \varphi_n = 0
$$

이라고 하자. 그렇다면 $k=1,\ldots,\, n-1$ 에 대해

$$
a_1\varphi_1^{(k)} + \cdots + a_n \varphi_n^{(k)} = 0
$$

을 만족하며 따라서 $\begin{bmatrix} a_1 & \cdots & a_n \end{bmatrix}^T$ 는 다음의 선형방정식의 해이다. 

$$
\begin{bmatrix} \varphi_1 & \varphi_2 & \cdots &\varphi_n \\ \varphi'_1 & \varphi'_2 & \cdots & \varphi'_n \\ \vdots  & & &\vdots \\ \varphi^{(n-1)}_1 & \varphi^{(n-1)}_2 & \cdots & \varphi^{(n-1)}_n\end{bmatrix} \begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_n \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix}
$$

즉 $W[\{\varphi_i\}] = 0$ 이면 nontrivial $a_1,\ldots,\,a_n$ 이 존재하며 따라서 $\{\varphi_i\}$ 는 선형 종속이다. $W[\{\varphi_i\}] \ne 0$ 이면 $a_1=\cdots = a_n = 0$ 이므로 $\{\varphi_i\}$ 는 선형 독립이다. $\square$

:::

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_dependency_sho}

@exm-ode_frobenius_sho 에서 우리는 $y'' + \omega^2 y = 0$ 의 해  $\sin \omega x,\,\cos\omega x$ 를 구했다. 여기서

$$
W[\sin \omega x,\, \cos\omega x] = \det \left(\begin{bmatrix} \cos \omega x & \sin \omega x \\ - \sin \omega x & \cos \omega x\end{bmatrix}\right) = 1
$$

이므로 두 해는 선형독립임을 안다.

:::

</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-DE_ODE_number_of_solution_of_second_order_linear_ode}

2계 LHODE 는 최대 두개의 독립적인 해를 가진다.

:::
</div>

::: {.proof}

2계 LHODE 

$$
y'' + p(x) y' + q(x) y = 0 
$$ {#eq-DE_ODE_thm_nsos_1}

를 생각하자. $y_1,\,y_2,\,y_3$ 가 이 방정식의 해라고 하자. 그리고 $W_{ij} = W[y_i, y_j]$ 라고 하면  $W_{ij}=  y_i y'_j - y'_i y_j$ 이다. 그렇다면 

$$
W'_{ij} = \dfrac{dW_{ij}}{dx} = y'_i y'_j + y_i y''_j - y''_iy_j - y'_i y'_j = y_i y''_j - y''_i y_j
$$ {#eq-DE_ODE_thm_nsos_2}

이다. @eq-DE_ODE_thm_nsos_1 로 부터, 

$$
\dfrac{y''_i}{y_i} + p(x) \dfrac{y'_i}{y_i} = -q(x) = \dfrac{y''_j}{y_j} + p(x) \dfrac{y_j'}{y_j} 
$$

이며 여기에 $y_i y_j$ 를 곱하면

$$
W'_{ij} = -p(x) W_{ij}
$$ {#eq-DE_ODE_differential_of_wronskian}

를 얻는다. 이제 

$$
\begin{aligned}
W(y_1, y_2, y_3) &= \det\left(\begin{bmatrix} y_1 & y_2 & y_3 \\ y'_1 & y'_2 & y'_3 \\ y''_1 & y''_2 & y''_3 \end{bmatrix}\right) = - y'_1 W_{23}' - y'_2 W'_{31} - y'_3 W'_{12} \\
&= -p(x) (y_1W_23 + y_2 W_31 + y_3 W_12) = \det\left(\begin{bmatrix} y_1 & y_2 & y_3 \\ y'_1 & y'_2 & y'_3 \\ y'_1 & y'_2 & y'_3 \end{bmatrix}\right) = 0
\end{aligned}
$$

이다. 따라서 2계 LHODE 의 선형 독립인 해는 많아야 2개이다. $\square$

:::

</br>

이제 @eq-DE_ODE_thm_nsos_1 의 꼴의 미분방정식의 한 해를 알고 있다고 하자. Frobenius 방법으로든, 직관으로 파악했든 하나의 해를 알았다면 이제 두번째 해, 즉 첫번째 해에 대해 선형독립인 나머지 해를 찾을 수 있음을 보이고자 한다. 두 해의 Wronskian $W[y_1,\,y_2] = W$ 은 $x$ 에 대한 함수이다. @eq-DE_ODE_differential_of_wronskian  로부터, 

$$
\dfrac{d}{dx}W(x) = -p(x) W(x) \implies W(x) = W(a) e^{-\int_{a}^x p(t)\,dt}
$$

를 얻는다. 또한

$$
W(x) = y_1y_2' - y_1'y_2 = y_1^2 \dfrac{d}{dx}\left(\dfrac{y_2}{y_1}\right)
$$

이므로, 

$$
\begin{aligned}
y_2(x) &= y_1(x) \int_b^x \dfrac{W(x')}{[y_1(x')]^2} \, dx' - \dfrac{y_2(b)}{y_1(b)}y_1(x) \\
&= y_1(x) W(a) \int_b^x \dfrac{\exp \left(-\int_a^{x'} p(t)\, dt\right)}{[y_1(x')]}\, dx'- \dfrac{y_2(b)}{y_1(b)}y_1(x) 
\end{aligned}
$$

이다. 여기서 $a,\,b$ 는 임의의 상수이다. 그런데 우리는 $y_1$ 과 선형독립인 $y_2$ 를 찾는 것이므로 뒤의 $y_2(b)y_1(x)/y_2(b)$ 는 없어도 무관하다. 따라서,

$$
y_2(x) = y_1(x) W(a) \int_b^x \dfrac{\exp \left(-\int_a^{x'} p(t)\, dt\right)}{[y_1(x')]}\, dx'
$$

만 생각해도 된다.

<br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE-anothor_solution_of_2nd_lhode}

#### 단순조화진동자(SHO) 의 경우

우리는 $y'' + \omega^2 y=0$ 의 한 해가 $\cos \omega x$ 임을 안다. $p(x) = 0$ 이므로 $W(x) = W_0 = \text{const.}$ 이다. 따라서, 

$$
y_2 (x) = \cos(\omega x) W_0 \int_{0}^x \dfrac{1}{\cos ^2 \omega x'}\, dx' = \dfrac{W_0}{\omega} \cos (\omega x) \tan (\omega x) = \dfrac{W_0}{\omega} \sin (\omega x)
$$

:::

</div></br>

## Sturm-Liouville theory {#sec-DE_ODE_sturm_liouville_theory}

2계 LHODE 연산자 $\mathcal{L}$ 에 대해

$$
\mathcal{L}\psi (x) = \lambda \psi (x)
$$

는 미분방정식을 고유값 문제로 바꾸게 된다. 이 경우 $\mathcal{L}$ 은

$$
\mathcal{L}\psi (x) = \left[p_0 (x) \dfrac{d}{dx^2} + p_1(x) \dfrac{d}{dx} + p_2(x)\right]\psi(x)
$$ {#eq-DE_ODE_2nd_lhode}

꼴로 주어진다. 
특정한 물리적 상황에 대한 미분방정식은, 그 해가 가저야 할 조건이 주어지며 많은 경우 그 해, 혹은 그 해의 도함수가 가져야할 경계조건으로 주어진다. 어떤 이계 미분 방정식이 $x=a,\,b$ 에서 $f(a)=f(b) =0$ 이거나 $f'(a) = f'(b)=0$ 이어야 한다면, 이 조건을 만족하는 미분가능한 함수의 집합 $X$ 는 힐베르트 공간을 이룬다. 즉 우리는 미분방정식을 벡터공간의 입장에서 다룰 수 있다. 만약 적절한 내적(inner product) 가 주어진 상황에서 $\mathcal{L}$ 연산자가 hermitian 이라면 고유값은 항상 실수이며, 전체 벡터공간을 고유벡터의 선형결합으로 표현 할 수 있다. 

</br>

### 에르미트 연산자 {#sec-DE_ODE_stum_liouville_hermitian}


@eq-DE_ODE_2nd_lhode 형태로 주어진 연산자 $\mathcal{L}$ 에서 $p'_0 (x) = p_1(x)$ 일 경우를 생각하자. 그렇다면, 


$$
\mathcal{L} \psi (x) = \left[\dfrac{d}{dx} \left(p_0(x) \dfrac{d}{dx}\right) + p_2(x)\right]\psi (x) = [p_0(x) \psi'(x)]' + p_2(x) ] \psi(x)
$$

이다. 여기서 내적이 $\langle u(x),\, v(x) \rangle = \displaystyle \int_{a}^b v^\ast(x) u(x)\, dx$ 로 정의되었다면, 

$$
\begin{aligned}
\langle \mathcal{L}u(x),\, v(x)\rangle &= \int_{a}^b \left(v^\ast ( p_0 u')' + v^\ast p_2 u\right) \, dx \\
&= {\large \left[ \right.}v^\ast p_0 u' {\large \left.\right]}_a^b +\int_a^b \left( -(v^\ast)' p_0 u' + v^\ast p_2 u\right) \, dx \\
&= {\large \left[ \right.}v^\ast p_0 u'  - (v^\ast)'p_0 u {\large \left.\right]}_a^b + \int_a^b \left[ (p_0 {v^\ast}')' u + v^\ast p_2 u\right]\, dx\\
&= {\large \left[ \right.}v^\ast p_0 u'  - (v^\ast)'p_0 u {\large \left.\right]}_a^b + \int_a^b (\mathcal{L}v)^\ast u\, dx \\
&= {\large \left[ \right.}v^\ast p_0 u'  - (v^\ast)'p_0 u {\large \left.\right]}_a^b + \langle u(x),\, \mathcal{L}v(x)\, \rangle
\end{aligned}
$$


이다. 만약 ${\large \left[ \right.}v^\ast p_0 u'  - (v^\ast)'p_0 u {\large \left.\right]}_a^b = 0$ 인 경계조건을 가지고 있다면, 

$$
\langle \mathcal{L}u(x),\, v(x)\rangle = \langle u(x),\, \mathcal{L}v(x)\, \rangle
$$

이며 이것은 벡터공간에서의 에르미트 연산자의 조건이다. 즉 일반적인 내적 벡터공간에서의 에르미트 연산자와는 달리 미분방정식에서의 에르미트 조건은 경계조건을 포함한다. 보통 $u(a)=u(b) = v(a)=v(b) = 0$ 이거나 $u'(a) =u'(b) = v'(a) = v'(b) = 0$ 인 조건을 가지게 되며 전자를 **디리클레 경계조건 (Dirichlet boundary condition)** 이라고 하고 후자를 **노이만 경계 조건 (Neumann boundary condition)** 이라고 한다. 

이제 디리클레 경계조건, 혹은 노이만 경계 조건을 만족하는 $C^2$ 함수의 집합을 $X$ 라고 하면 $X$ 는 벡터공간며 여기에 내적 $\langle u,\,v\rangle = \displaystyle \int_a^b v^\ast(x)u(x)\,dx$ 이 정의되어 있다면 $X$ 는 내적 벡터 공간이 된다. $\mathcal{L}$ 연산자는 에르미트 연산자이므로 $\mathcal{L}$ 의 고유함수로 $X$ 의 기저를 구성 할 수 있다. $\varphi_i,\, \varphi_j$ 가 각각 $\lambda_i,\, \lambda_j$ 를 고유값으로 갖는 고유함수이며 $\lambda_i\neq \lambda_j$ 라면 당연히 $\langle \varphi_i,\,\varphi_j \rangle = 0$ 이다.


</br>

### 미분방정식을 에르미트 연산자 형태로 변경하기 {#sec-DE_ODE_hermitianization_of_ode}

위에서 설명했듯이 미분연산자가 hermitian 이라면 매우 좋은 성질을 갖게 된다. 만약 자체로는 에르미트 연산자가 아니지만 약간 변형하여 에르미트 연산자로 만들 수 있다면? @eq-DE_ODE_2nd_lhode 형태의 미분방정식이 에르미트 연산자가 될 조건은 아래의 두가지 이다.

&emsp; (1) $p_0'(x) = p_1(x)$,

&emsp; (2) 경계조건 ${\large \left[ \right.}v^\ast p_0 u'  - (v^\ast)'p_0 u {\large \left.\right]}_a^b =  0$ .

만약 어떤 함수 $w(x)$ 를 곱하여, 

$$
\mathcal{L}'\psi(x) = w(x) \mathcal{L} \psi(x) = \left[w(x) p_0 (x) \dfrac{d}{dx^2} + w(x) p_1(x) \dfrac{d}{dx} + w(x) p_2(x)\right]\psi(x)
$$

의 $\mathcal{L}'$ 이 hermitian 이 되려면 $(wp_0)' =wp_1$ 이 되어야 한다. $(wp_0)' = (wp_0)\dfrac{p_1}{p_0}$ 이므로, 

$$
w(x)p_0(x) = w(a)p_0(a) \exp \left(\int_a^x \dfrac{p_1(t)}{p_0(t)}\, dt\right)
$$ {#eq-ode_weighting}

이며, 

$$
w(x) = \dfrac{1}{p_0(x)} \exp \left(\int_a^x \dfrac{p_1(t)}{p_0(t)}\, dt\right)
$$

로 놓을 수 있다. $w(a)p_0(a)$ 는 상수로 미분방정식에 영항을 끼치지 않아서 $1$ 로 놓았다. 실제로는 계산하기 편하도록 어떤 0 이 아닌 상수를 곱하여도 상관 없다. 이제 
$$
\overline{p}_0 = \exp \left(\int^x \dfrac{p_1(t)}{p_0(t)}\, dt\right),\qquad \overline{p}_1 = \dfrac{p_1(x)}{p_0(x)}\exp \left(\int^x \dfrac{p_1(t)}{p_0(t)}\, dt\right)
$$
에 대해 

$$
\mathcal{L}'\psi (x) = \left[\overline{p}_0 (x) \dfrac{d^2}{dx^2} + \overline{p}_1(x) \dfrac{d}{dx} + w(x)p_2(x)\right]\psi(x)
$$

의 미분방정식을 얻었다. 

이제 에르미트 조건을 알아보자.

$$
\begin{aligned}
\int_a^b v^\ast (x) \mathcal{L}'u(x)\, dx &= \int_a^b v^\ast (x) w(x)\mathcal{L}u(x)\, dx \\
&=  {\large \left[ \right.} v^\ast \overline{p}_0 u' - (v^\ast)' \overline{p}_0 u {\large \left. \right]}_a^b + \int_a^b (\mathcal{L}'v(x))^\ast u(x)\, dx \\
&=  {\large \left[ \right.} v^\ast \overline{p}_0 u' - (v^\ast)' \overline{p}_0 u {\large \left. \right]}_a^b + \int_a^b w(x)(\mathcal{L}v(x))^\ast u(x)\, dx
\end{aligned}
$$ {#eq-DE_ODE_hermitian_cond_1}

이제 내적을

$$
\langle u(x),\, v(x)\rangle = \int_a^b v^\ast (x) u(x) w(x)\, dx
$$ {#eq-odd_innerproduct_with_weight}

로 정의하자. 이 때 $w(x)$ 를 **무게 함수(weight function)** 이라고 한다. 그렇다면 @eq-DE_ODE_hermitian_cond_1 은

$$
\langle \mathcal{L}u(x),\, v(x)\rangle =  {\large \left[ \right.} v^\ast \overline{p}_0 u' - (v^\ast)' \overline{p}_0 u {\large \left. \right]}_a^b  + \langle u,\, \mathcal{L}v(x)\rangle
$$


이 된다. 즉 내적의 정의가 변하며 연산자 $\mathcal{L}$ 이 hermitian 이 된다.

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_legendre_function}

#### 르장드르 함수 (Legendre function)

르장드르 미분연산자

$$
\mathcal{L} = (1-x^2) \dfrac{d^2}{dx^2} -2x\dfrac{d}{dx}
$$

에 대해 $\mathcal{L}P_l(x) = -l(l+1)P_l(x)$ 를 푸는 것이 @tbl-2nd_ode_singularity 의 르장드르 미분방정식의 해이다. 자연수 $l$ 에 대한 미분방정식의 해는 $l$ 차 다항식임이 알려저 있다. $\dfrac{d}{dx}(1-x^2)=-2x$ 이므로 무게함수는 $w(x)=1$ 이다.

:::

</div>

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_chevyshev_function}

#### 체비쇼프 함수 (Legendre function)

체비쇼프 미분연산자

$$
\mathcal{L} = (1-x^2) \dfrac{d^2}{dx^2} -x\dfrac{d}{dx}
$$

에 대해 $\mathcal{L}T_n(x) = -n^2T_n(x)$ 를 푸는 것이 @tbl-2nd_ode_singularity 의 르장드르 미분방정식의 해이다. 자연수 $n$ 에 대한 미분방정식의 해는 $n$ 차 다항식임이 알려저 있다. $\dfrac{d}{dx}(1-x^2)=-2x$ 이므로 무게함수는

$$
w(x) = \dfrac{1}{1-x^2} \exp \left(\int_{a}^x \dfrac{t}{1-t^2}\, dt \right)= \dfrac{1}{\sqrt{1-x^2}}
$$

이다. 적분시 $a$ 에 대한 항은 상수곱이 되므로 무시했다.

:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_laruerre_function}

#### 라게르 함수(Laguerre function)

아래의 미분방정식 연산자 $\mathcal{L}$ 에 대한 고유값 문제 $\mathcal{L}\psi =\lambda \psi$ 를 풀고자 한다. 

$$
\mathcal{L} = x \dfrac{d^2}{dx^2} + (1-x)\dfrac{d}{dx}.
$$ {#eq-ode-laguerre_operator}

이 때 $\psi$ 는 $0\le x <\infty$ 에서 nonsingular 하며, $\psi (x\to \infty) = 0$ 이라고 하자. $p'_0\ne p_1$ 이므로 weighting function $w(x)$ 를 @eq-ode_weighting 으로 계산하면, 

$$
w(x) = \dfrac{1}{x} \exp \left(\int^x \dfrac{1-t}{t}\,dt\right) = \dfrac{1}{x} e^{\ln x - x} = e^{-x}
$$

이 미분방정식이 hermitian 이 되려면 경계조건

$$
0 = {\large \left[ \right.} v^\ast \overline{p}_0 u' - (v^\ast)' \overline{p}_0 u {\large \left. \right]}_a^b =  {\large \left[ \right.} xe^{-x} (v^\ast  u' - (v^\ast)'  u) {\large \left. \right]}_a^b
$$

을 만족해야 한다. 

:::

</div></br>

## 직교하는 다항식

### 로드리게스 공식 {#sec-ODE_DE_rodriguess_formula}

Sturm-Liouville 형태의 미분방정식

$$
p(x) y'' + q(x)y' + \lambda y = 0
$$ {#eq-DE_ODE_sturm_liourille_ode}

를 생각하자. 많은 경우 $p(x),\, q(x)$ 는 각각 2차, 1차 다항식 형태이다.

$$
p(x) = \alpha x^2 + \beta x + \gamma,\qquad q(x) = \mu x + \nu
$$

이 미분방정식의 $n$ 차 다항식 해를 $y_n = \sum_{k=0}^n c_k x^k$ 라고 이 해에 대한 $\lambda$ 를 $\lambda_n$ 이라고 하자. $c_n\neq 0$ 이다. 그렇다면 @eq-DE_ODE_sturm_liourille_ode 는 최고차항에서

$$
\lambda_n = -n(n-1)\alpha - n\mu
$$ {#eq-eigenvalue_of_n_order_polynomial}

을 만족해야 한다. 무게함수 $w(x)$ 를 생각하면 

$$
\dfrac{d}{dx}[w(x)p(x)y'] + \lambda w(x)y = 0 
$$

을 만족해야 한다. 이것을 이용하여 아래의 @thm-rodrigues_fomula 를 증명 할 수 있다. Arfken 의 수리물리학에서 Rodriguess formular 를 찾아보면 지루한 증명을 찾아 볼 수 있으나 여기서는 생략하기로 한다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-rodrigues_fomula}

아래와 같이 정의된 $y_n(x)$ 는 $\lambda$ 가 @eq-eigenvalue_of_n_order_polynomial 의 $\lambda_n$ 인 @eq-DE_ODE_sturm_liourille_ode 의 해이다.
$$
y_n(x) = \dfrac{1}{w(x)} \left(\dfrac{d}{dx}\right)^n \left[w(x)p(x)^n\right].
$$ {#eq-rodrigues_formula}

:::

</div>
<!-- ::: {.proof}


무게함수 $w(x)$ 는 $(wp)' = wq$ 를 만족하게 하는 함수임을 안다. 

$$
\begin{aligned}
p[wp^n]' &= p(w'p^n) + np^nw p' = (w'p)p^n + nwp^n p'\\
&= (wq-wp')p^n + nwp^np' \\
&= wp^n((n-1)p' + q)
\end{aligned}
$$ {#eq-DE_ODE_thm_rodriguess_formlar_1}

이제 위 식을 $n+1$ 번 미분한 후 $w$ 로 나누어 보자. $p$ 는 2차식이며 $q$ 는 1차식임에 유의하라. 

$$
\begin{aligned}
\dfrac{1}{w}\left(\dfrac{d}{dx}\right)^{n+1}p[wp^n]' &= \dfrac{p}{w} \left(\dfrac{d}{dx}\right)^{n+2}[wp^n] + \dfrac{(n+1)p'}{w}\left(\dfrac{d}{dx}\right)^{n+1}[wp^n] \\
&\qquad \qquad + \dfrac{n(n+1)p''}{w}\left(\dfrac{d}{dx}\right)^{n-1}[wp^n]
\end{aligned}
$$




$$
\begin{aligned}
\dfrac{p}{w} \left(\dfrac{d}{dx}\right)^{n+2} [wp^n] + \dfrac{(n+1)p'}{w} \left(\dfrac{d}{dx}\right)^{n+1} + \dfrac{n(n+1)p''}{2w}\left(\dfrac{d}{dx}\right)^n [wp]^n
\end{aligned}
$$


-- to be filled  --
:::

 -->

</br>

### Schlaefli 적분

@eq-rodrigues_formula 을 만족한다면 코시 적분 공식를 사용하여 

$$
y_n (x) = \dfrac{1}{2}\dfrac{n!}{2\pi i} \oint_C \dfrac{w(z)[p(z)]^n}{(z-x)^{n+1}} \, dz
$$ {#eq-DE_ODE_schlaefli_integral}

를 얻을 수 있다. 이를 **Schlaefli 적분** 이라고 한다.

</br>

### 생성 함수

::: {.callout-note appearance="minimal"}

::: {#def-DE_ODE_generating_function}
우리가 원하는 함수의 집합 $\{f_n(x)\}$ 가 $x$ 와 보조변수 $t$ 에 대해 정의된 어떤 함수 $g(x,\,t)$ 에 대해

$$
g(x,\,t) = \sum_{n} c_n f_n(x) t^n
$$

의 형태가 될 때 $g(x,\,t)$ 를 **생성 함수(generating function)** 이라고 한다. 

:::
:::

$n = 0,\,1,\ldots$ 일 때는 $t$ 에 대한 테일러 전개로 간주 할 수 있으며 $n$ 이 음의 정수를 포함한다면 로랑 전개(Laurant series) 로 간주 할 수 있다. 복소함수의 유수 정리(residue theorem) 을 사용한다면

$$
c_n f_n(x) = \dfrac{1}{2\pi i} \oint \dfrac{g(x,\,t)}{t^{n+1}}\, dt
$$

를 통해 얻을 수 있다. 여기서 적분 경로(contour) 는 $0$ 을 포함하며 $0$ 이외의 다른 특이점이 없어야 한다. 

생성함수는 @eq-DE_ODE_schlaefli_integral 을 이용하면 다음과 같이 얻을 수 있다.

$$
g(x,\,t) = \dfrac{1}{w(x)} \sum_{n=0}^\infty t^n \dfrac{n!}{2\pi i} \oint_C \dfrac{w(z)[p(z)]^n}{(z-x)^{n+1}} \, dz
$$ {#eq-DE_ODE_generating_function_using_Schlaefli_formula}


</br>

| 이름 | 방정식 | 생성 함수
|:-----:|:----------------------------|:----------------------------|
| Legendre | $\displaystyle (1-x^2) y'' -2xy' + n(n+1)y=0$ | $\displaystyle (1-2xt+t^2)^{-1/2} = \sum_{n=0}^\infty P_n(x)t^n$ |
| Chebyshev type $I$ | $(1-x^2) y'' -xy' + n^2y = 0$ | $\displaystyle \dfrac{1-t^2}{1-2xt+t^2} = T_0 (x) + 2\sum_{n=1}^\infty T_n(x)t^n$ |
| Laguerre | $xy'' + (1-x)y' + n y = 0$ | $\displaystyle \dfrac{e^{-xt/(1-t)}}{1-t} = \sum_{n=0}^\infty L_n (x) t^n$ |
| Hermite | $y'' -2xy' + 2n y = 0$ | $\displaystyle e^{-t^2+2xt} = \sum_{n=0}^\infty \dfrac{1}{n!} H_n(x)t^n$ |

: 중요한 2계 선형 ODE 의 생성 함수 {#tbl-DE_ODE_2nd_ode_generating_function}
