---
title: "상미분 방정식 I. 기본개념과 1차, 2차 상미분 방정식"

number-sections: true
number-depth: 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

</br>

## 기본 개념

미분방정식에서는 여러 용어들이 일반적인 방정식이나 다항삭과 다르게 사용된다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-DE_basic_definitions}

#### 미분방정식의 기본 개념

- 하나의 독립변수에 대한 미분방정식을 **상미분 방정식 (ordinary differential equation, ODE)** 이라고 하며, 여러 독립변수에 대한 미분방정식을 **편미분 방정식 (partial differential equation, PDE)** 라고 한다.
  
- 미분 연산을 포함하는 연산자를 **미분 연산자 (differential operator)** 라고 한다. 미분 연산자 $\mathcal{L}$ 가 미분 가능한 함수 $f,\,g$ 와 상수 $a$ 에 대해 
$$
\mathcal{L}(af(x) + g(x)) = a \mathcal{L}(f(x)) + \mathcal{L}(g(x))
$$ 
를 만족하면 $\mathcal{L}$ 을 **선형 미분 연산자(linear differential operator)** 라고 한다.  

- 일반적으로 미분방정식은 미분연산자 $\mathcal{L}$ 과 함수 $F(x)$ 에 대해 다음의 꼴로 주어진다.
$$
\mathcal{L}(f(x)) = F(x)
$$ {#eq-diff_eq_basic}

- @eq-diff_eq_basic 에서 $\mathcal{L}$ 이 선형미분연산자이고 $F(x)$ 가 미분연산자를 포함하지 않은 $x$ 의 함수 일 때 이 미분방정식을 **선형미분방정식(linear differential equation)**이라고 한다.


- 상미분방정식이 $y=y(x)$ 에 대해 주어졌다고 하자. **계수 (order)** 는 $y$ 의 최고차 도함수의 차수이며  **차수 (degree)** 는 $y$ 의 최고차 도함수의 승수이다. 예를 들어 $(y''')^4 + y^5 = F(x)$ 형태의 미분방정식이라면 계수는 3 이며 차수는 4 인 3계 4차 미분방정식이 된다. 


- 미분방정식의 각각의 항이 독립변수에 대한 함수와 종속변수의 미분의 곱으로만 이루어 졌을 때 이 미분방정식을 **제차 미분방정식 (homogeneous differential equation)** 이라고 한다. (see @exm-DE_homogeneous_function_and_differential_equation)

:::
:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_homogeneous_function_and_differential_equation}
#### Homogeneity
</br>

**일반적인 함수의 경우**

$n$ 개의 독립변수를 가진 함수 $f(x_1,\ldots,\,x_n)$ 가 어떤 $k$ 에 대해 

$$
f(tx_1,\ldots,\,tx_k) = t^k f(x_1,\ldots,\,x_k)
$$ 

를 만족할 때 이 함수를 **계수가 $k$ 인 동차 함수(homogeneous function of order $k$)** 라고 한다. 

</br>

**미분방정식의 경우**

예를 들어 아래와 같은 형태의 미분방정식에서 $F(x) = 0$ 이면 이 제차 미분방정식이다. 

$$
\sum_{k=0}^N a_k(x) y^{(k)}(x) = F(x).
$$

:::

</div></br>

### 선형 동차 상미분 방정식 (LHODE) {#sec-DE_ODE_lhode}

선형이며 동차인 미분연산자 $\mathcal{L}$ 과 함수 $F$ 에 대해 다음과 같이 주어졌다고 하자.

$$
\mathcal{L}(f(x)) = F(x).
$$

$F(x)=0$ 이면 이 미분방정식은 선형이며 동차인 미분방정식이다. 많은 경우 선형 제차 미분방정식의 해를 얻는 것이 매우 중요하다. 그 이유중 하나는 위의 미분방정식의 해 $\psi$ 를 얻었고, homogeneous 한 방정식의 해 $\phi$ 를 얻었다면 $\phi + \psi$ 도 항상 위의 방정식의 해이기 때문이다. 이제 선형 제차 상미분 방정식(linear homogeneous ordinary differential equation) 을 **LHODE** 라고 줄여 쓰기로 하자. 그리고 선형 제차 상미분 연산자 (linear homogeneous ordinary differential operator) 를 **LHODO** 라고 줄여 쓰기로 하자.

</br>

#### **중첩 원리** 

LHODE $\mathcal{L}(f(x))=0$ 의 해는 보통 여러개이며 그것의 선형결합 역시 해이다. 즉 $\mathcal{L}\psi = 0$, $\mathcal{L}\phi  = 0$ 이면 임의의 $a,\,b$ 에 대해 $\mathcal{L}(a\psi + b \phi) = 0$ 이다. 이것을 **중첩 원리 (superposition principle)** 이라고 한다.  

</br>

## 1계 ODE

미분방정식이 아래와 같은 형태로 주어졌다고 하자.

$$
\dfrac{dy}{dx} = - \dfrac{P(x,\,y)}{Q(x,\,y)}.
$$ {#eq-DE_typical_1_deg_ode}

이런 미분방정식을 일반적으로 푸는 방법은 없으며, 여기서는 많이 사용되는, 특정한 경우에 사용되는 방법을 알아보도록 하자.

</br>

### 변수 분리 {#sec-DE_separable_equations_for_1degree_ode}

가장 간단한 경우 가운데 하나로 미분방정식이 

$$
\dfrac{dy}{dx} = \dfrac{-P(x)}{Q(y)}
$$

로 주어졌을 경우 이다. 그렇다면 아래의 적분을 통해 구할 수 있다. 그렇다면 이 식은 아래와 같이 쓸 수 있다.

$$
P(x)\,dx + Q(y)\,dy = 0.
$$

위 식을 $(x_0,\,y_0)$ 에서 $(x,\,y)$ 까지 적분하면 아래의 식을 얻는다. 

$$
\int_{x_0}^x P(x')\,dx' + \int_{y_0}^y Q(y')\,dy' = 0.
$$

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_drafting_falling}

#### 마찰이 있는 낙하 

마찰이 있는 낙하의 경우 시간 $t$ 와 위치 $x$ 에 대해 미분방정식이 아래와 같이 주어진다. $\dot{x}=v$ 라고 하자.

$$
m\dot{v} = mg - bv^2.
$$

그리고 초기 조건으로 $v(0)=0$ 라고 하자. $mg=bv_0^2$ 으로 놓으면

$$
\dfrac{m}{b}\dot{v} = v_0^2 -v^2
$$

이며

$$
\left(\dfrac{1}{v_0-v} + \dfrac{1}{v_0+v}\right)dv = \dfrac{2v_0 b}{m}dt
$$

이다. 이를 적분하면

$$
\ln \dfrac{v_0 + v}{v_0 - v} = \dfrac{2v_0 b}{m}t
$$

이다. $\tau:= v_0b/m$ 에 대해 $v(t)$ 를 아래와 같이 얻는다.

$$
v= v_0 \tanh (t/\tau)
$$

:::
</div>
</br>

### 완전 미분방정식의 경우 {#sec-DE_ode_exact_differential}

@eq-DE_typical_1_deg_ode 을 다음과 같은 형태로 쓰자.

$$
P(x,\,y)\,dx + Q(x,\,y)\,dy = 0
$$ {#eq-DE_typical_1_deg_ode_2}

이 미분방정식이 어떤 $\Phi(x,\,y)$ 에 대해

$$
d\Phi = \dfrac{\partial \Phi}{\partial x}\,dx + \dfrac{\partial \Phi}{\partial y}\,dy = P(x,\,y)\,dx + Q(x,\,y)\,dy
$$ {#eq-DE_typical_1_deg_ode_exact_form}

일 때, 이 마분방정식을 **전미분 형태** 라고 한다. 즉 위의 미분 방정식은 $d\Phi (x,\,y) = 0$ 인 해 $\Phi$ 를 찾는 것이며 따라서 

$$
\Phi(x,\,y) = C = \text{constant}
$$

형태의 해를 찾는 것이다.

$\Phi(x,\,y)$ 가 $C^2$ 급 함수라면 $\dfrac{\partial^2 \Phi}{\partial x \partial y} = \dfrac{\partial^2 \Phi}{\partial y \partial x}$ 이므로

$$
\dfrac{\partial P}{\partial y} = \dfrac{\partial Q}{\partial x} = \dfrac{\partial^2 \Phi}{\partial x \partial y}
$${#eq-DE_typical_1_deg_ode_exact_form_2}

이다. 또한 @eq-DE_typical_1_deg_ode_2 의 미분방정식과 조건 @eq-DE_typical_1_deg_ode_exact_form_2 이 주어졌을 때 이 미분방정식은 전미분 형태임을 보일 수 있다. $P(x,\,y) = \dfrac{\partial \Phi}{\partial x}$ 로부터

$$
\Phi = \int_{x_0}^x P(x',\,y)\,dx' + f(y)
$$

이다. 그렇다면

$$
\begin{aligned}
\dfrac{\partial \Phi}{\partial y} &= \int_{x_0}^x \dfrac{\partial P(x',\,y)}{\partial y}\, dx' + \dfrac{\partial f}{\partial y} = \int_{x_0}^x \dfrac{\partial Q(x',\,y)}{\partial x'}\,dx' + \dfrac{\partial f}{\partial y} \\[0.3em]
&=Q(x,\,y) -Q(x_0,\,y) + \dfrac{\partial f}{\partial y}= Q(x,\,y) 
\end{aligned}
$$

이므로 $x_0$ 를 $Q(x_0,\,y) = \partial f/\partial y$ 가 되도록 잡아야 한다. 그렇다면 어떤 상수 $C_f$ 에 대해

$$
f(x,\,y) = \int_{y_0}^y Q(x_0,\,y')\,dy' + C_f
$$

이며, 따라서

$$
\Phi(x,\,y) = \int_{x_0}^x P(x',\,y)\,dx' + \int_{y_0}^y Q(x_0,\,y')\,dy' = \text{const.}
$$

이다.

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_nonseparable_exact}

아래와 같이 주어진 미분방정식을 생각하자.

$$
\dfrac{dy}{dx} = -1 - \dfrac{y}{x}.
$$

양변에 $x\,dx$ 를 곱하면 $(x+y)dx + xdy = 0$ 이며 $\partial (x+y)/\partial y = \partial x/\partial x = 1$ 이므로 전미분 형태이다. 그렇다면

$$
\begin{aligned}
\Phi(x,\,y) &= \int_{x_0}^x (x'+y)\,dx' + \int_{y_0}^y x_0 \,dy' = \dfrac{x^2}{2} + xy + C_f
\end{aligned}
$$

이므로 미분방정식의 해는 다음과 같다.

$$
\Phi(x,\,y) = \dfrac{x^2}{2}+xy=\text{const.}
$$

:::
</div>
</br>

$P(x,\,y)\,dx+Q(x,\,y)\,dy=0$ 꼴인 미분방정식이 전미분 형태가 아니지만 적분 인자 $\alpha(x,\,y)$ 를 곱했을 때

$$
\alpha(x,\,y)P(x,\,y)\,dx+\alpha(x,\,y)Q(x,\,y)\,dy=0
$$

가 전미분 형태가 되면 위의 방법을 이용하여 해를 구할 수 있다. 적분 인자는 최소한 하나 이상 존재하지만 선형 1계 미분방정식을 제외하면 적분 인자를 체계적으로 구하는 방법은 존재하지 않는다. 이에 대해서는 다음에 다루기로 하자.

</br>

### 1계 제차 상미분방정식의 경우 {#sec-DE_ODE_order_1_homogeneous_case}

1계 제차 상미분 방정식의 경우 각 항애서 $x,\,y,\,dx,\,dy$ 의 곱의 승수가 동일하다. 이 경우 $y=vx$ 놓고 $x$ 와 $v$ 에 대한 미분방정식 형태로 바꾼 후 변수분리를 통해 풀 고 다시 $x,\,y$ 에 대한 함수형태로 바꿀 수 있는 경우가 있다.


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_order_1_homogeneous_case}

아래와 같이 주어진 미분방정식을 생각하자.

$$
(2x+y)\,dx + xdy = 0
$$

$y=xv$ 로 놓으면 $dy = xdv + vdx$ 이며 미분방정식은 아래의 형태가 된다.

$$
(2v+2)\,dx + xdv = 0
$$

이 미분방정식의 해는 

$$
\ln x + \dfrac{1}{2} \ln (v+1)= C
$$

이며 $y=xv$ 이므로

$$
y = \dfrac{C}{x}-x
$$

이다.

:::
</div>
</br>

제차 상미분 방정식이 아니지만 $y=vx^m$ 으로 놓을 경우 $x,\,v$ 에 대한 제차 상미분 방정식꼴이 될 수 있다.

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_order_1_homogeneous_case}

아래와 같이 주어진 미분방정식을 생각하자.

$$
(x^2-y)\,dx + xdy = 0
$$

$y=vx^2$ 으로 놓으면

$$
0 = x^2 \,dx - vx^2 dx + 2vx^2dx + x^3dv = (1+v)x^2dx + x^3dv
$$

이며 이로부터

$$
(1+v)dx + xdv = 0
$$

을 얻는다. 즉

$$
\dfrac{dx}{x} + \dfrac{dv}{1+v}=0
$$

이므로

$$
x(1+v)= C \,(\text{constant})
$$

이다. 이로부터 방정식의 해를 다음과 같이 얻는다.

$$
y=Cx-x^2
$$

:::
</div>
</br>

### 1계 선형 상미분 방정식 {#sec-DE_ODE_1olde}

1계 선형 상미분 방정식은 일반적으로 다음과 같은 형태로 주어진다.

$$
y' + p(x)y = q(x).
$$ {#eq-DE-ODE_genral_1dgree_LHODE_form}

위 식이 전미분 형태이면 @sec-DE_ode_exact_differential 에서 소개한 방법으로 쉽게 풀 수 있으며 여기서는 전미분 형태가 아닌 경우에만 다룬다. 여기서는 적분 인자 $\alpha(x)$ 를 도입하여 아래 식이 전미분 형태가 되도록 조작하고자 한다.

$$
\alpha(x)y' + \alpha (x)p(x)y = \alpha(x)q(x)
$$

이를 위해


$$
\dfrac{d}{dx}\left(\alpha (x)\,y(x)\right) = \alpha(x) y'(x) + \alpha (x)p(x)y(x)
$$

가 되는 $\alpha(x)$ 를 어쨌든 구했다고 하자. 그렇다면 원래의 미분방정식은

$$
\dfrac{d(\alpha y)}{dx} = \alpha q
$${#eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor}

가 되며, 조건으로 보면 아래를 만족시키게 된다.
$$
\alpha' y  =  \alpha p y
$$ 

이며, 위 식을 전개하면 다음을 얻는다.

$$
\dfrac{d\alpha}{\alpha} = p(x)\,dx.
$$

당연히 $\alpha(x)$ 는 적당한 초기값에 대해 아래와 같다.

$$
\alpha(x) = \alpha_0\exp \left(\int_{x_0}^x p(x)\,dx\right)
$$

그렇다면 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 로부터

$$
\alpha(x) y(x) = \int^x \alpha(x') q(x')\,dx' + C
$$

이며, 따라서

$$
y(x) = \dfrac{1}{\alpha(x)} \left[\int^x \alpha(x') q(x')\,dx' + C\right]
$$

이다. 여기서 $y_1,\,y_2$ 를 다음과 같이 정하자.

$$
y_1 := \dfrac{1}{\alpha(x)} \int^x \alpha (x')q(x')\,dx',\qquad y_2 := \dfrac{C}{\alpha(x)}.
$$

그렇다면 $y=y_1+y_2$ 이며, 

$$
y_2' + py = 0
$$

이다. 즉 $y_2$ 는 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 의 $q(x)=0$ 인 제차 미분방정식의 해이다. 반면 $y_1$ 은 $q(x)$ 를 포함한 @eq-DE_ODE_transformed_1degree_LHODE_by_integrating_factor 을 만족한다. 

이것은 어찌 보면 당연한데 비 제차 미분방정식의 해는 제차 형태의 미분방정식의 해(일반해, general solution) 들의 선형결합과 비제차 미분방정식의 해(특이해, particular solution)의 합이다. 




<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-DE_ODE_summary}

1계 선형 미분방정식에 대해 다음이 성립한다.

($1$) 비 제차 1계 선형 미분방정식의 해는 제차 미분방정식의 선형결합을 제외하면 유일하게 결정된다.

($2$) 제차 1계 선형 미분방정식은 유일한 선형 독립 해를 가진다.


:::
</div>

::: {.proof}

($1$) $y_1,\,y_2$ 가 미분방정식 $y'+py=q$ 두 해라고 하자. 즉 $y_1'+py_1=q,\, y_2'+py_2=q$ 이면 $(y_1'-y_2')+p(y_1'-y_2') = 0$ 이며 따라서 $y_1'-y_2'$ 은 주어진 미분방정식의 제차 형태의 해이므로 특이해는 제차 미분방정식의 선형결합을 제외하면 유일하게 결정된다.

($2$) $y_1,\,y_2$ 가 제차 미분방정식 $y'+py=0$ 의 선형독립인 두 해라고 하자. 그렇다면 $y_1'/y_1 = y_2'/y_2 = -p(x)$ 이며 이로부터 어떤 상수 $C$ 에 대해 $y_1=Cy_2$ 인데 이는 선형독립인 가정에 모순이다. $\square$

:::

</br>

#### **매개변수 변환법**

1계 상미분 방정식 $y'+py=q$ 의 해를 구하는 한 방법이다. 우선 제차 형태인 $y'+py=0$ 해 $y_h$ 를 구하면

$$
y_h = C \exp \left(-\int^x p(x')\,dx'\right)
$$

이다. 여기서 $C$ 를 상수가 아닌 $x$ 에 대한 함수로 놓고 특이해를 구할 수 있는 경우가 있다. 즉 $C\to C(x)$ 로 변환한 $y_h$ 를 $y$ 로 놓고 $y'$ 을 구하면

$$
\begin{aligned}
y' &= \exp \left(-\int^x p(x')\,dx'\right)\left(-p(x)C(x) + C'(x)\right) \\[0.3em]
&= -p(x)y(x) + C'(x) \exp \left(-\int^x p(x')\,dx'\right)
\end{aligned}
$$

이며 따라서

$$
C'(x)\exp\left(-\int^x p(x')\,dx'\right) = q(x)
$$

이다. 그렇다면 특이해 $y_p$ 는 아래와 같다.

$$
y_p = C(x) \exp \left(-\int^x p(x')\,dx'\right),\quad \text{where } C(x) = \int^x \exp \left(\int^{x'} p(x')\,dx' \right) q(x'')\,dx''.
$$

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_2}

#### Arfken 7.2.3

베셀 방정식 ($n=0$) 의 라플라스 변환을 통해 아래 식을 얻는다. $f(s)$ 를 구하라.

$$
(s^2+1)f'(x) + sf(x) = 0.
$$

:::

</div>

::: {.solution}

$\dfrac{f'(x)}{f(s)} = - \dfrac{s}{s^2+1}$ 로부터 $\ln f(s) = - \dfrac{1}{2}\ln s+C$ 를 얻는다. 따라서 $f(s) = C\sqrt{s^2+1}$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_3}

#### Arfken 7.2.3

Catastrophic two-body collisions 에 의한 decay of populiation 은 아래의 1계 비선형 미분방정식에 의해 기술된다.

$$
\dfrac{dN}{dt} = -kN^2.
$$

$\tau_0 = (kN_0)^{-1}$ 에 대해 이 미분방정식의 해가 를 유도하고 다음과 같음을 보여라.

$$
N(t) = N_0 \left(1+ \dfrac{t}{\tau_0}\right)^{-1}.
$$

:::

</div>

::: {.solution}

$\dfrac{dN}{N^2} = -k\,dt$ 를 적분하면

$$
- \dfrac{1}{N(t)}+ \dfrac{1}{N_0} = -kt
$$

이며 문제의 해를 얻는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_6}

#### Arfken 7.2.6

1계 미분방정식 $\dfrac{dy}{dx}=f(x,\,y)$ 에서 함수 $f(x,\,y)$ 는 $y/x$ 의 함수이다. 즉 $\dfrac{dy}{dx}=g(y/x)$ 이다. $u=y/x$ 치환에 의해 이 미분방정식은 $u,\,x$ 에 대해 분리가능한 방정식이 됨을 보여라.

:::

</div>

::: {.solution}

$y=ux$ 이므로 $\dfrac{dy}{dx}= u + x\dfrac{du}{dx}$ 이다. 주어진 미분방정식은 $x,\,y$ 에 대해 $u+xu' = g(u)$ 이므로 아래와 같이 분리가능한 미분방정식을 얻는다.

$$
\dfrac{dx}{x} = \dfrac{du}{g(u)-u}.
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_10}

#### Arfken 7.2.10

아래와 같이 주어진 미분방정식에서 $f,\,g,\,h$ 는 $0$ 이 아니다. 

$$
f(x)\,dx + g(x)h(y)\,dy = 0.
$$

이 식이 전미분 형태가 될 필요충분조건은 $g(x)=\text{constant}$ 임을 보여라.

:::

</div>

::: {.solution}

$g(x)=\text{constant}$ 이면 전미분 형태임. 이제 방정식이 전미분 형태임을 가정하면

$$
\dfrac{\partial f(x)}{\partial y} = \dfrac{\partial g(x)h(y)}{\partial x} =0
$$

이어야 하므로 $g'(x)=0$. 즉 $g(x)=\text{constant.}$.


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_11}

#### Arfken 7.2.11

$$
y(x) = \exp \left[-\int^x p(t)\,dt\right] \left(\int^x \exp \left[\int^s p(t)\,dt\right]\,q(s)\,ds + C\right)
$$

가 아래의 미분방정식의 해임을 보여라.

$$
\dfrac{dy}{dx}+p(x)y(x) = q(x).
$$

:::

</div>

::: {.solution}

주어진 식으로부터
$$
\begin{aligned}
y' &= - p(x) y(x)+ \exp \left[-\int^x p(t)\,dt\right] \left(\exp \left[\int^x p(t)\,dt\right]\,q(x)\,ds\right)y(x) \\[0.3em]
&= -p(x)y(x) + q(x).
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_2_13}

#### Arfken 7.2.13

방사성 핵 붕괴는 아래의 법칙을 따른다.

$$
\dfrac{dN}{dt} = -\lambda N.
$$

여기서 $N$ 은 핵의 농도이고 $\lambda$ 는 특정 핵종에 따른 붕괘 상수이다. 서로 다른 두 핵종의 연속 방사성 붕괘 계열은 각각의 농도를 $N_1(t),\,N_2(t)$ 라고 할 때 아래의 미분방정식을 따른다.

$$
\begin{aligned}
\dfrac{dN_1}{dt}&= -\lambda_1 N_1,\\[0.3em]
\dfrac{dN_2}{dt}&= \lambda_1 N_1 - \lambda_2 N_2.
\end{aligned}
$$

$N_1(0)=N_0,\, N_2(0)=0$ 일 때 $N_2(t)$ 를 구하라.

:::

</div>

::: {.solution}

$N_1(t) = N_0 e^{-\lambda_1 t}$ 이므로

$$
\dfrac{dN_2}{dt} + \lambda_2 N_2 = \lambda_1 N_0 e^{-\lambda_1 t} 
$$

이다. 제차 형태에 대한 미분방정식의 해는 $N_2(t) = N_2e^{-\lambda_2 t}$ 이므로 $N_2(t) = C(t)e^{-\lambda_2 t}$ 로 놓으면

$$
C'(t) e^{-\lambda_2 t}= \lambda_1 N_0 e^{-\lambda_1 t}
$$

이다. 

$$
C'(t) = \lambda_1 N_0 e^{-(\lambda_1 - \lambda_2)t}
$$

이며 $N_2(0)=0$ 이므로 $C(0)=0$ 이다. 

**(1) $\lambda_1 \ne \lambda_2$ 일 때**

$$
C(t) = \dfrac{\lambda_1N_0}{\lambda_2-\lambda_1} e^{-(\lambda_1-\lambda_2)t} - \dfrac{\lambda_1N_0}{\lambda_2-\lambda_1} 
$$

이므로 다음을 얻는다.

$$
N_2(t) = \dfrac{\lambda_1 N_0}{\lambda_2-\lambda_1} (e^{-\lambda_1 t} - e^{-\lambda_2 t})
$$

**(2) $\lambda_1 = \lambda_2$ 일 때**

$C'(t) = \lambda_2 N_0$ 이므로 $C(t) = \lambda_2 N_0 t$ 이다. 따라서

$$
N_2(t) = \lambda_2N_0 te^{-\lambda_2t}.
$$

:::

</br>

## 계수가 상수인 ODE 의 경우

미분방정식이 다음과 같은 꼴로 주어졌다고 하자.

$$
\dfrac{d^ny}{dx^n} + a_{n-1} \dfrac{d^{n-1}y}{dx^{n-1}} + \cdots + a_1 \dfrac{dy}{dx} + a_0 y = F(x).
$$ {#eq-constant_coefficients_ode}

위 미분방정식은 $n$-계 선형 미분방정식이다. 이 경우 $y=e^{mx}$ 를 놓으면 일반해, 즉 $F(x)=0$ 일 경우의 해를 구할 수 있다. 

$$
(m^n + a_{n-1}m^{n-1} + \cdots + a_n m + a_0)e^{mx}=0
$$

이며 이를 만족 하는 $m$ 은 복소수에서 $n$ 개 존재한다. 

</br>

## 2계 선형 ODE

### Singularity {#sec-DE_ODE_sigularity}

가장 간단한 다음 꼴의 2계 ODE 를 보자.

$$
y''  + p(x) y' + q(x) y  = 0
$$ {#eq-DE_ODE_simple_2nd_ode}

이 식은 모든 항에서 $y$ 와 그 도함수가 1차이므로 homogeneous 하다. $p(x)$ 와 $q(x)$ 가 유한한 값을 가질 때 이 $x$ 를 **일반점 (ordinary point)** 이라고 하며 그렇지 않을 때는 **특이점 (singular point)** 이라고 한다. 특이점 $x_0$ 에 대해

$$
\lim_{x\to x_0} |(x-x_0)p(x)|<\infty, \qquad \lim_{x\to x_0} |(x-x_0)^2q(x)|<\infty
$$ 

이면 **정칙 특이점 (regular singularity)** 이라고 하며 그렇지 않을 때 **비정칙 특이점(irregular singularity/essential singularity)** 라고 한다. 


$x\to \infty$ 나 $x \to -\infty$ 의 경우에는 $z=1/x$ 로 치환하여 미분방정식을 $z$ 에 대한 미분방정식으로 바꾼다. $w(z) = y(z^{-1})$ 이라면, 

$$
\begin{aligned}
y'(x) &= \dfrac{dy}{dz} \dfrac{dz}{dx} = - \dfrac{1}{x}^2 \dfrac{dw}{dz} = -z^2w', \\
y'' (x) &= \dfrac{dy'}{dz}\dfrac{dz}{dx} = z^4 w'' + 2z^3 w'
\end{aligned}
$$


이므로 @eq-DE_ODE_simple_2nd_ode 는 다음과 같이 변형된다.

$$
z^4w'' + \left[ 2z^3 - z^2 p(z^{-1}) \right] w' + q(z^{-1}) w = 0.
$$ {#eq-DE_ODE_modified_simplie_2nd_ode}

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-DE_ODE_bessel_function}

#### 베셀 함수

베셀 함수는 아래와 같이 주어진다.

$$
x^2 y'' + xy' + (x^2-n^2)y = 0.
$$

@eq-DE_ODE_simple_2nd_ode 와 비교하면 $p(x) = \dfrac{1}{x},\, q(x) = 1-\dfrac{n^2}{x^2}$ 이므로 $x=0$ 은 정칙 특이점이다. 이 외에는 $x$ 가 유한한 영역에서 특이점이 없다는 것은 쉽게 알 수 있다. $z=1/x$ 로 치환하여 $x\to \infty$ 에서의 미분방정식의 행동을 보자. @eq-DE_ODE_modified_simplie_2nd_ode 는 다음과 같다.

$$
w'' + \dfrac{1}{z}w' + \dfrac{1-n^2z^2}{z^4}=0
$$

즉 $x\to \infty$ 에서 베셀방정식은 비정칙 특이점을 가진다.

:::

</div></br>


### 중요한 2계 선형 미분방정식 {#sec-DE_ODE_important_differential_equations}


| 방정식 이름 | 정칙 특이점 | 비정칙 특이점 |
|:---------------------------------|:------------:|:------------:|
| 초기하 방정식 (Hypergeometric) </br> $x(x-1) y'' + [(1+a+b)x + c]\,y' +aby=0$ | $0, 1 \infty$ | |
| 르장드르 방정식 (Legendre) </br> $(1-x^2) y'' -2xy' + l(l+1)y=0$ | $-1, 1, \infty$ | |
| 체비셰프 방정식 (Chebyshev) </br> $(1-x^2) y'' -xy' + n^2y = 0$ | $-1, 1, \infty$ | |
| 합류 초기하 방정식 (Confluent hypoergeometrc function) </br> $xy'' + (c-x)y' -ay = 0$ | $0$ | $\infty$ |
| 베셀 방정식 (Bessel) </br> $x^2y'' + xy' + (x^2-n^2)y = 0$ | $0$ |$\infty$ |
| 라게르 방정식 (Laguerre) </br> $xy'' + (1-x)y' + a y = 0$ | $0$ | $\infty$ |
| 단순 조화 진동자 (SHO) </br> $y'' + \omega^2 y' = 0$ | | $\infty$ |
| 에르미트 방정식 (Hermite) </br> $y'' -2xy' + 2\alpha y = 0$ | | $\infty$ |

: 중요한 2계 선형 ODE 와 singularity {#tbl-2nd_DE_ODE_singularity_of_odes}


대표적으로 르장드르 함수 $(1-x^2) y'' -2xy' + l(l+1)y=0$ 를 보자. 르장드르 함수는

$$
y'' - \dfrac{2xy}{1-x^2} y' + \dfrac{l(l+1)}{1-x^2} y = 0
$$
 
으로 $x=\pm 1$ 에서 regular singularity 를 가진다. 

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_4_1}

#### Arfken 7.4.1 ~ 7.4.4
</br>

($1$) 르장드르 방정식과 체비셰프 방정식이 $x=\pm 1,\, \infty$ 에서 정칙 특이점을 가짐을 보여라.

($2$) 라게르 방정식이 베셀 함수와 같이 $x=0$ 에서 정칙특이점을, $x=\infty$ 에서 비정칙 특이점을 가짐을 보여라.

($3$) 에르미트 방정식이 $x=\infty$ 이 비정칙 특이점인 것을 제외하면 특이점을 갖지 않음을 보여라.

:::

</div>

::: {.solution}

($1$) 르장드르 방정식의 경우 $p(x) = \dfrac{-2x}{1-x^2},\,q(x) = \dfrac{l(l+1)}{1-x^2}$ 이므로 $x=\pm 1$ 에서 정칙 특이점을 가진다. 또한 @eq-DE_ODE_modified_simplie_2nd_ode 형태는

$$
w'' + \dfrac{2z}{(z^2-1)}w' + \dfrac{l(l+1)z^2}{1-z^2} w= 0
$$

이므로 $z=0 (x=\infty)$ 에서 정칙 특이점을 가진다. 체비셰프 방정식의 형태를 생각하면 특이점의 정칙성은 르장드르 방정식과 동일함을 알 수 있다.

($2$) 라게르 방정식의 경우 $p(x) = (1-x)/x,\, q(x) = a/x$ 이므로 $x=0$ 에서 정칙 특이점이다. @eq-DE_ODE_modified_simplie_2nd_ode 형태는

$$
w'' + \dfrac{z+1}{z^2}y' + \dfrac{a}{z^4} w=0
$$

이므로 $z=0$ 에서 비정칙 특이점을 가진다.

($3$) 에르미트 방정식은 유한한 값에서 특이점을 갖지 않음을 쉽게 알 수 있다. @eq-DE_ODE_modified_simplie_2nd_ode 형태는

$$
w'' + \dfrac{2z^2+2}{z^2}y' + \dfrac{2\alpha}{z^4}w = 0
$$

이므로 $z=0 (x=\infty)$ 는 비정칙 특이점이다. 


:::

</br>

## 프로베니우스 방법을 이용한 급수해 {#sec-DE_ODE_Frobenius}

### 프로베니우스 방법 {#sec-DE_ODE_power_series_soluiton}

@eq-DE_ODE_simple_2nd_ode 형태의 2계 LHODE 를 생각하자. 이 경우 $y$ 를 $x$ 의 급수로 놓고 해를 구하는 것을 Frobenius 방법이라고 한다. 즉,

$$
y(x) = \sum_{i=0}^\infty a_i x^{s+i} ,\qquad a_0 \ne 0
$$ {#eq-ode_expansion_about_zero}

로 놓고 미분방정식에 대입하여 계수 $a_i$ 와 $s$ 를 구한다. 이 때 $a_0 \ne 0$ 임에 유의하라. 

</br>

### 단순조화진동자의 해 {#sec-DE_ODE_frobenius_sho}

예를 들어 $y'' + \omega^2 y = 0$ 의 경우, 

$$
\begin{aligned}
&\sum_{i=0}^\infty a_i (s+i)(s+i-1)x^{s+i-2} + \omega^2 \sum_{i=0}^\infty a_j x^{s+i} = 0 \\
\implies & a_0 s(s-1)x^{s-2} + a_1 (s+1)s x^{s-1} \\[0.3em]
&\qquad \qquad \qquad + \sum_{i=0}^\infty \left[a_{i+2}(s+i+2)(s+i+1) +\omega^2 a_j\right]x^{s+i} = 0
\end{aligned}
$$

이로부터 우리는 세가지 조건을 얻는다.

&emsp; ($1$) $a_0 s(s-1) =0$, 

&emsp; ($2$) $a_1s(s+1) = 0$, 

&emsp; ($3$) $a_{i+2}(s+i+2)(s+i+1) + \omega^2 a_j = 0$

$a_0\ne 0$ 이므로 ($1$) 의 조건에 의해 $s(s-1)=0$ 이어야 한다. 이 방정식은 $s$ 를 결정하는 중요한 방정식으로 **결정방정식(indicial equation)** 이라고 한다. ($2$) 의 조건에서 $s=-1$ 일 경우 $a_0 = 0$ 이어야 하므로 조건에 위배된다. 따라서 남은 조건은 $s=0$ 이고 $a_1$ 을 자유로 두거나, $s=1$ 이며 $a_1=0$ 으로 두는 것 밖에 없다. 그리고 ($3$) 조건에 의해

$$
a_{i+2} = \dfrac{-\omega^2}{(i+1)(i+2)}a_i \implies  a_{2k} = (-1)^n \dfrac{\omega^{2k}}{(2k)!} a_0,\, a_{2k+1} = (-1)^n \dfrac{\omega^{2k}}{(2k+1)!} a_1
$$

를 만족해야 한다. $s=0$ 일 경우, 

$$
\begin{aligned}
y(x){\large\mid}_{s=0} &= a_0 \left[ \sum_{k=0}^\infty \dfrac{(-1)^k (\omega)^{2k}}{(2k)!} x^{2k} \right] + a_1 \left[ \sum_{k=0}^\infty \dfrac{(-1)^k (\omega)^{2k}}{(2k+1)!} x^{2k+1} \right]\\[0.3em]
&= a_0 \cos (\omega x) + \dfrac{a_1}{\omega} \sin (\omega x)
\end{aligned}
$$

이다. $s=1$ 인 경우는 같은 방법으로

$$
y(x) {\large \mid}_{s=1} =  \dfrac{a_0}{\omega}\sin (\omega x)
$$

임을 알 수 있다. 

</br>

### $x_0$ 주위로의 멱급수 전개

@eq-ode_expansion_about_zero 는 $x_0=0$ 근처의 전개이다. 이것을 임의의 $x_0$ 근처에서 다음과 같이 전개하여 미분방정식의 해를 구하는 것도 가능하다.

$$
y(x) = \sum_{i=0}^\infty a_i (x-x_0)^{s+i} ,\qquad a_0 \ne 0
$$

$x_0$ 를 정칙 특이점으로 잡으면 많은 경우 미분방정식의 해를 찾는 데 유용하지만 비정칙 특이점의 경우는 Frobenius 방법으로 해를 구할 수 없다.

</br>

### 해의 대칭성 {#sec-DE_ODE_symmetry_of_solutions}

미분연산자 $\mathcal{L}(x)$ 에 대해 아래와 같이 주어지는 제차 상미분 방정식을 생각하자.

$$
\mathcal{L}(x)y(x) = 0.
$$

이 미분연산자가 $\mathcal{L}(-x) = \mathcal{L}(x)$ 일 때 이 미분연산자는 **even parity** 를 가진다고 하며 $\mathcal{L}(-x) = -\mathcal{L}(x)$ 일 때 **odd parity** 를 가진다고 한다. 일단 even/odd 패리티를 가지며 $y(x)$ 가 이 미분방정식의 해 일 때

$$
0 = \mathcal{L}(x) y(x) = \mathcal{L}(-x) y(-x) = \pm \mathcal{L}(x) y(-x)
$$

이므로 $y(-x)$ 역시 해임을 알 수 있다. $y(x)$ 와 $y(-x)$ 가 선형 독립일 경우, 즉 $y(-x) \ne \pm y(x)$ 일 경우 

$$
y_\text{even} := y(x) + y(-x),\qquad y_\text{odd} := y(x) - y(-x) 
$$

역시 서로 독립인 이 미분방정식의 해이다. $y(x)$ 와 $y(-x)$ 가 선형 종속이라면 $y(-x) = \pm y(x)$ 이므로 여기에 대해 생각 할 필요가 없다. 

@tbl-2nd_DE_ODE_singularity_of_odes 의 미분방정식을 보면 르장드르, 체비셰프, 베셀, 단순조화진동자, 그리고 에르미트 방정식의 경우는 even parity 를 가지며 라게르 방정식의 경우는 even 이나 odd parity 를 갖지 않는다. 

</br>

### 베셀 방정식의 해 {#sec-DE_ODE_frobenius_bessel}

베셀 방정식은 아래와 같이 주어진다.

$$
x^2 y'' + xy' + (x^2-n^2)y = 0.
$$ {#eq-DE_ODE_frobenius_bessel_1}

이제 해를 $y = \sum_{j=0} a_j x^{s+j}$ 로 가정하면 위의 미분방정식으로부터 다음을 얻는다.

$$
\begin{aligned}
\sum_{j=0}^\infty a_j (s+j)(s+j-1)x^{s+j} + \sum_{j=0}^\infty a_j (s+j) x^{s+j} + \sum_{j=0} a_j x^{s+j-2} - \sum_{j=0}^\infty a_j n^2 x^{s+j} = 0.
\end{aligned}
$$

$x^s$ 에 대한 계수를 비교하면 아래와 같은 결정방정식(indicial equation)을 얻는다.

$$
0=a_0 [s(s-1) + s-n^2] = a_0 [s^2-n^2],
$$ {#eq-DE_ODE_indication_equation_for_bessel_equation}

$a_0 \ne 0$ 이어야 하므로 $s = \pm n$ 을 얻는다. 이제 $x^{s+1}$ 의 계수를 비교하면 다음을 얻는다.

$$
0 = a_1[(s+1)s + s+1 - n^2] = a_1 (s+1-n)(s+1+n)
$$

$s=\pm n$ 을 생각하면 $a_1=0$ 일 수 밖에 없다. 이제 $x^{s+j}$ 에 대해 비교하자. 방정식이 $n^2$ 에 대한 방정식이므로 $n \ge 0$ 이라고 생각하자.


**(1) $s=n \ge 0$ 인 경우 **

$s=n$ 이라면 아래의 점화식(recurrence relation) 을 얻는다.

$$
a_{j+2} = -\dfrac{a_j}{(j+2)(2n+j+2)}
$$ 

$a_0 \ne 0,\, a_1 = 0$ 이므로 $a_{2k}$ 만 의미있으며 정리하면 다음을 얻는다.

$$
a_{2k} = (-1)^k \dfrac{a_0 n!}{2^{2k} k! (n+k)!}.
$$

$n$ 에 대한 방정식의 해를 $J_n(x)$ 라고 하면 (이 함수를 베셀 함수라고 한다) 아래와 같다.

$$
J_n(x) = a_0 2^n n! \sum_{j=0}^\infty \dfrac{(-1)^j}{j!(n+j)!}\left(\dfrac{x}{2}\right)^{n+2j}
$$

**(2) $s=-n < 0$ 인 경우**

이 경우에 대한 해를 $J_{-n}$ 으로 표기한다. 그런데 멱급수의 계수에 대해 아래의 점화식을 얻는다.

$$
a_{j+2} = - \dfrac{a_j}{(j+2)(j-2n+2)}.
$$

$n$ 이 정수 일 때 $j=2(n-1)$ 에서 $a_{j+2}$ 가 발산하며 따라서 이 경우에는 프로베니우스 방법을 통해 해를 얻을 수 없다.

</br>

지금까지 프로베니우스 방법을 이용하여 단순조화진동자와 베셀방정식에 대한 해를 얻었다. 급수를 이용한 프로베니우스 방법은 항상 사용 할 수 있는 것은 아니다.

</br>

### 정칙 특이점과 비정칙 특이점 {#sec-DE_ODE_regular_and_irregular_singularities_in_frobenius_method} 

프로베니우스 방법을 제대로 사용할지 여부는 결정방정식의 해와 미분방정식에서의 비정칙 특이점의 특이성이 정도에 따른다. 예를 들어 

$$
y'' - \dfrac{6}{x^2}y = 0
$$ {#eq-DE_ODE_singularity_1}

의 경우 결정방정식 $s^2-s-6=0$ 으로부터 $s=3$ 혹은 $s=-2$ 임을 안다. 제차 미분방정식이므로 점화식이 존재하지 않고 단지 $x^3,\, x^{-2}$ 의 답을 얻을 수 있다.

이제 아래의 미분방정식을 보자.
$$
y'' - \dfrac{6}{x^3}y = 0.
$${#eq-DE_ODE_singularity_2}

이 경우 $y=\sum_j a_j x^{s+j}$ 에 대한 결정방정식은 $a_0=0$ 뿐이다. 이것은 $a_0\ne 0$ 이어야 하는 조건에 위배되므로 최소한 이 방법으로는 해를 얻을 수 없다.


.... boring part ..

</br> 

### Fuchs' theorem {#sec-DE_ODE_fuchs_theorem}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-DE_ODE_fuchs_theorem}

#### Fuch 의 정리

아래와 같은 꼴의 미분방정식을 생각하자.

$$
\displaystyle y''+p(x)y'+q(x)y=F(x)
$$

이 방정식은 $p(x),\, q(x),\, F(x)$ 가 $x=a$ 에서 해석적 이거나 $a$ 가 정칙 특이점이라면 프로베니우스 방법에 의한 해를 가진다. 즉 이 미분방정식의 $x=a$ 근처의 해는 어떤 양수 $s$ 에 대해 

$$
y_1=\sum _{n=0}^{\infty }a_{n}(x-a)^{n+s},\quad a_{0}\ne 0
$$

이거나 $y_1$ 함수에 $\ln (x-a)$ 를 곱한것과 다른 $y_1$ 꼴의 함수를 더한 아래의 형태이다.

$$
y=y_1\ln(x-a)+\sum _{n=0}^{\infty }b_{n}(x-a)^{n+r},\quad b_{0}\neq 0.
$$

:::

</div></br>


### 연습문제 {.unnumbered}


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_5_1}

#### Arfken 7.5.1, 유일성 정리

$y(x)$ 가 2계 제차 선형 미분방정식의 해이고 $x=x_0$ 에서 $y(x_0)=y_0,\, y'(x_0)=y'_0$ 라고 하자. $y(x)$ 가 유일함을 보여라. 즉 기울기 $y'_0$ 를 가지고 $(x_0,\,y_0)$ 를 통과하는 미분방정식의 해는 유일함을 보여라.

:::

</div>

::: {.solution}

$y_1,\,y_2$ 가 $y''+p(x)y' + q(x) = 0$ 와 주어진 초기조건을 만족하는 두 해라고 하자. $y_1(x)-y_2(x) = \overline{y}(x)$ 라고 하면 $\overline{y}''+p(x)\overline{y}' + q\overline{y}=0$ 이며 

... to be completed ...
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_5_2}

#### Arfken 7.5.2

@eq-DE_ODE_simple_2nd_ode 의 해를 $x=x_0$ 에 대한 프로베니우스 방법으로 구한다고 하자. $x_0$ 가 일반점일 경우 결정방정식은 $s=0,\,1$ 의 해를 가짐을 보여라.

:::

</div>

::: {.solution}

$x_0$ 가 일반점이므로 $p(x),\,q(x)$ 역시 $\sum_{j=0} b_j(x_0)^{n+j}$ 형태로 표현 할 수 있다. 멱급수 형태인 $y(x) = \sum_j a_j (x-x_0)^{j+s}$ 를 @eq-DE_ODE_simple_2nd_ode 에 적용하면 다음을 얻는다.
$$
\begin{aligned}
0 &= \sum_{j=0}a_j(j+s)(j+s-1) (x-x_0)^{j+s-2} + \sum_{j=0} a_j(j+s) p(x) (x-x_0)^{j+s-1} \\[0.3em]
&\qquad + \sum_{j=0} a_j q(x) (x-x_0)^{j+s}
\end{aligned}
$$

이로부터 $a_0(s)(s-1) = 0$ 의 결정방정식을 얻으며 이 해는 $s=0,\,1$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_5_4}

#### Arfken 7.5.4

@sec-DE_ODE_frobenius_sho 에서 단순조화진동자의 해를 구할 때 두번째 계수 $a_1$ 를 without irrevocably losing anything 하게 $0$ 으로 놓을 수 있는지, 아니면 무조건 $0$ 으로 놓아야 할 경우는 어떤 경우인지 확인하라.

:::

</div>

::: {.solution}

멱급수 해 $y=\sum_j a_j x^{j+s}$ 를 사용한다. 

($a$) 르장드르 방정식 : $(1-x^2) y'' -2xy' + l(l+1)y=0$

$$
\begin{aligned}
0 &= \sum_{j=0}^\infty a_j(s+j)(s+j-1)x^{s+j-2} - \sum_{j=0}^\infty a_j(s+j)(s+j-1)x^{s+j} \\[0.3em]
&\quad -2\sum_{j=0}^\infty a_j (s+j)x^{s+j} + l(l+1) \sum_{j=0}^\infty a_j x^{s+j} 
\end{aligned}
$$

이므로 $a_0 s(s-1) x^{s-2} + a_1 s(s+1) x^{s-1}=0$ 이어야 한다. 첫번째 항으로부터 $s=0$ 혹은 $s=1$ 이어야 함을 안다. $s=0$ 일 경우 $a_1$ 은 어떤 수여도 상관 없으므로 필요하다면 $a_1=0$ 으로 놓을 수 있으며 $s=1$ 일 경우 $a_1=0$ 으로 놓아야 한다.

($b$) 체비셰프 방정식 : $(1-x^2) y'' -xy' + n^2y = 0$

르장드르 방정식의 형태와 비교했을 때 르장드르 방정식의 경우와 같다.

($c$) 베셀 방정식 : $x^2y'' + xy' + (x^2-n^2)y = 0$

@sec-DE_ODE_frobenius_bessel 의 @eq-DE_ODE_indication_equation_for_bessel_equation 와 그 이후를 보라. $a_1=0$ 일 수 밖에 없다. 

($d$) 에르미트 방정식 : $y'' -2xy' + 2\alpha y = 0$

르장드르 방정식의 형태와 비교했을 때 르장드르 방정식의 경우와 같다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_5_5}

#### Arfken 7.5.5

아래와 같은 초기하 방정식 (hypergeometric equation) 의 멱급수해를 고하고 그 수렴을 확인하라.

$$
x(x-1)y'' + [(1+a+b) x -c]y' + aby=0.
$$
:::

</div>

::: {.solution}

멱급수 해 $y=\sum_j a_j x^{j+s}$ 를 사용한다. 

$$
\begin{aligned}
0 &= \sum_j a_j (s+j)(s+j-1)x^{s+j} - \sum_j a_j (s+j)(s+j-1)x^{s+j-1} \\[0.3em]
&\quad + \sum_j a_j(1+a+b)(s+j)x^{s+j} - \sum_j ca_j (s+j)x^{s+j-1} + \sum_j ab a_j x^{s+j}
\end{aligned}
$$

로부터 결정방정식

$$
a_0[s(s-1) + cs] = a_0s (s+c-1)=0,
$$

과 점화식

$$
a_{j+1} = \dfrac{(s+j + a)(s+j+b)}{(s+j+1)(s+j+c)}a_j
$$

을 얻는다. 결정방정식으로부터 $s=0$ 혹은 $s=1-c$ 임을 안다.

**(1)$s=0$ 인 경우**

$$
a_{j+1} = \dfrac{(j+a)(j+b)}{(j+1)(j+c)}a_j
$$

이며 $j\to \infty$ 극한에서 $a_{j+1} = a_j$ 이다. 따라서 멱급수해는 $|x|<1$ 에서만 정의된다.

**(2) $s=1-c$ 인 경우**

$$
a_{j+1} = \dfrac{(j+1+a-c)(j+1+b-c)}{(j+2-c)(j+1)} a_j
$$

이며 역시 $j \to \infty$ 극한에서 $a_{j+1}= a_j$ 이다. 따라서 멱급수해는 $|x|<1$ 에서만 정의된다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ODE_arfken_7_5_6}

#### Arfken 7.5.6
아래와 같은 합류 초기하 방정식 (confluenthypergeometric equation) 의 멱급수해를 고하고 그 수렴을 확인하라.

$$
xy'' + (c-x)y' -ay=0.
$$


:::

</div>

::: {.solution}

멱급수 해 $y=\sum_j a_j x^{j+s}$ 를 사용한다. 

$$
\begin{aligned}
0 &= \sum_j a_j (s+j)(s+j-1)x^{s+j-1} + \sum_j ca_j(s+j)x^{s+j-1} - \sum_j a_j (s+j)x^{s+j} -\sum_j aa_j x^{s+j}
\end{aligned}
$$

로부터 결정방정식

$$
a_0s(s+c-1)=0
$$

과 점화식

$$
a_{j+1} = \dfrac{(s+j + a)}{(s+j+1)(s+j+c)}a_j
$$

을 얻는다. 결정방정식으로부터 $s=0$ 혹은 $s=1-c$ 임을 안다.

**(1)$s=0$ 인 경우**

$$
a_{j+1} = \dfrac{(j+a)}{(j+1)(j+c)}a_j
$$

이며 따라서 멱급수해는 수렴한다.

**(2) $s=1-c$ 인 경우**

$$
a_{j+1} = \dfrac{(j+1+a-c)}{(j+2-c)(j+1)} a_j
$$
이며 따라서 멱급수해는 수렴한다.

:::