---
title: "Fig-complex"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 

```{r, engine = 'tikz'}
#| label: fig-compex_contour
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.8]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw [thick, -latex] (-1, 0) -- (4, 0) node[below] {$x$};
\draw [thick, -latex] (0, -1) -- (0, 4) node[left] {$y$};

\draw[teal, thick] plot[variable=\t,domain=0.5:3.5, samples=100, smooth,thick] ({\t}, { sin( (\t-31) * 50) + 2});

\filldraw [] (0.5, 1.0) circle (1pt) node [left] {$z_0$} ;
\filldraw [] (3.5, 2.90) circle (1pt) node [right] {$z_n$} ;
\draw[] (0.97, 1.20) -- (1.03, 1.07) node [below] {$z_1$};
\draw[] (1.46, 1.49) -- (1.54, 1.37) node [below] {$z_2$};
\draw[] (1.95, 1.88) -- (2.04, 1.77) node [below] {$z_3$};

\filldraw [blue] (0.75, 1.05) circle (0.5pt) node [above] {$\xi_0$};
\filldraw [blue] (1.25, 1.26) circle (0.5pt) node [above] {$\xi_1$};

\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-compex_contour_z0
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2.0]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}


\draw [thick, -latex] (-0.5, 0) -- (3, 0) node[below] {$x$};
\draw [thick, -latex] (0, -0.5) -- (0, 3) node[left] {$y$};

\filldraw [] (1, 1.0) circle (0.5pt) node [below] {$z_0$} ;
\coordinate (a1) at (0.2, 1.0);
\coordinate (a2) at (0.6, -0.2);
\coordinate (a3) at (1.3, 0.1);
\coordinate (a4) at (2, 0.6);
\coordinate (a5) at (2.5, 2.0);
\coordinate (a6) at (1.4,2.2);
\coordinate (a7) at (0.3 , 2.2);
\coordinate (O) at ($(a1)-(1,2)$);
\draw [teal, thick, -latex]  plot[smooth, tension=.8] coordinates {(a1) (a2) (a3) (a4) (a5) (a6) (a7) (a1)};
\node[above] at (a6) {$C$};
\draw[red, thick, -latex, semithick] (1.0, 1.5) arc (90:450:0.5);
\draw[-latex] (1.0, 1.0) -- (1.5, 1.0);
\node[right] at (1.5, 1.0) {$C'$};
\node[above] at (1.25, 1.0) {$r$};
%\filldraw [] (a1) circle (1pt) node [below] {$a_1$} ;
%\filldraw [] (a2) circle (1pt) node [below] {$a_2$} ;
%\filldraw [] (a3) circle (1pt) node [below] {$a_3$} ;
%\filldraw [] (a4) circle (1pt) node [below] {$a_4$} ;
%\filldraw [] (a5) circle (1pt) node [below] {$a_5$} ;
%\filldraw [] (a6) circle (1pt) node [below] {$a_6$} ;
%\filldraw [] (a7) circle (1pt) node [below] {$a_7$} ;
\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-complex_tayler_expansion
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.8]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (z0) at (1, 1.0);
\coordinate (z1) at (2.5, 2.5);
\coordinate (zp) at (2.201, 1.497);
\draw [-latex] (-1, 0) -- (4, 0) node[below] {Re$(z)$};
\draw [-latex] (0, -1) -- (0, 4) node[left] {Im$(z)$};

\filldraw [] (z0) circle (1pt) node [left] {$z_0$} ;
\filldraw [] (z1) circle (1pt) node [right] {$z_1$};
\filldraw [] (zp) circle (1pt) node [right] {$z^\prime$};
\draw [thick] (1, 1.0) circle (1.3) ;
\draw [thick] (1, 1.0) circle (2.121) ;

\draw[violet, thick, -latex] (z0) -- (2.052, 0.236);
\draw[teal, thick, -latex] (z0) -- (1.655, 3.017);

\node[below] at (1.4, 0.5) {$|z^\prime-z_0|$};
\node[below] at (1.1, 2.75) {$|z_1-z_0|$};


\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-complex_lauranrt_expansion
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.8]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (p1) at (0.9987502603949663, 0.04997916927067833);
\coordinate (p2) at (1.6978754426714426, 0.04997916927067833);
\coordinate (q1) at (0.9987502603949663, -0.04997916927067833);
\coordinate (q2) at (1.6978754426714426, -0.04997916927067833);



\draw [thick] (0, 0) circle (0.7) ;
\draw [thick] (0, 0) circle (2.0);
\filldraw [] (0,0) circle (1pt) node [left] {$z_0$} ;
\draw[teal, very thick] (p1) -- (p2);
\draw[teal, very thick] (q1) -- (q2);
\draw[teal, very thick, -latex] (p1) arc (2.865:90:1) node [above] {$C_2$};
\draw[teal, very thick] (0, 1.0) arc (90:357.135:1);
\draw[teal, very thick, -latex] (p2) arc (1.686:90:1.7) node[above] {$C_1$};
\draw[teal, very thick] (0, 1.7) arc (90:358.314:1.7);

\draw[red, thick, -latex] (0, 0) -- ({0.7*cos(310)}, {0.7*sin(310)});
\node[left] at ({0.35*cos(310)}, {0.35*sin(310)}) {$r$};

\draw[red, thick, -latex] (0, 0) -- ({2*cos(105)}, {2*sin(105)});
\node[left] at ({1.3*cos(105)}, {1.3*sin(105)}) {$R$};

\draw[dashed, blue] (0, 0) -- (2.5, 0) node[below] {$\begin{array}{cc}\text{Contour}\\ \text{line} \end{array}$};
\filldraw[] ({1.4*cos(60)}, {1.4*sin(60)}) circle(1pt) node[right] {$z$};


\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-complex_branch_1
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (z0) at (0, 0);
\coordinate (z1) at ({cos(50)}, {sin(50)});
\coordinate (zp) at (2.201, 1.497);
\draw [-latex] (-1.7, 0) -- (1.7, 0) node[below] {Re$(z)$};
\draw [-latex] (0, -1.7) -- (0, 1.7) node[left] {Im$(z)$};


\draw[red, very thick, -latex,] ({cos(135)}, {sin(135)}) arc (135:495:1);
\draw[thick, -latex] (0.3, 0) arc (0:50:0.3);
\node [right] at (0.3, 0.2) {$\theta$};
\node [above] at(1.1, 0.0) {$A$};
\node [above right] at(0.0, 1.0) {$B$};
\node [above] at(-1.1, 0) {$C$};
\node [below right] at(0.0, -1.0) {$D$};
\draw[] (z0) -- (z1);

\end{tikzpicture}
```

</br>


```{r, engine = 'tikz'}
#| label: fig-complex_branch_2
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (z0) at (2, 0);
\coordinate (z1) at ({cos(50)}, {sin(50)});
\coordinate (zp) at (2.201, 1.497);
\draw [-latex] (-0.3, 0) -- (3.7, 0) node[below] {Re$(z)$};
\draw [-latex] (0, -1.7) -- (0, 1.7) node[left] {Im$(z)$};


\draw[red, very thick, -latex,] ({2+cos(25)}, {sin(25)}) arc (25:385:1);
\draw[thick, ] (0.4, 0) arc (0:20.5:0.4);
\node [right] at (0.4, 0.1) {$\theta$};

\draw[] (0, 0) -- ({2+ cos(65)}, {sin(65)});
\draw[dashed] (2, -1) -- (2, 1);
\filldraw [] (3.01,0) circle (1pt) node [above right] {$A$} ;
\filldraw [] (2,1) circle (1pt) node [above] {$B$} ;
\filldraw [] (1,0) circle (1pt) node [below left] {$C$} ;
\filldraw [] (2,-1) circle (1pt) node [below left] {$D$} ;
\filldraw [] (2,0) circle (1pt) ;
\end{tikzpicture}
```

</br>



```{r, engine = 'tikz'}
#| label: fig-complex_branch_3
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (z1) at (1, 0);
\coordinate (z2) at (-1, 0);
\coordinate (P) at ({1+ cos(70)}, {sin(70)});
\draw [-latex] (-2, 0) -- (2, 0) node[below] {Re$(z)$};
\draw [-latex] (0, -0.5) -- (0, 1.5) node[left] {Im$(z)$};

\draw [red, very thick] (z1) -- (z2) ; 
\draw [thick] (z1) -- (P) node[above] {$P$};
\draw [thick] (P) -- (z2);

\draw[thick, ] (-0.6, 0) arc (0:21.86:0.4);
\node [right] at (-0.55, 0.1) {$\theta$};

\draw[thick, ] (1.4, 0) arc (0:70:0.4);
\node [right] at (1.4, 0.2) {$\varphi$};


\filldraw [] (z1) circle (1pt) node [below] {$+1$} ;
\filldraw [] (z2) circle (1pt) node [below] {$-1$} ;

\node [above] at (0.3, 0.5) {$r$};

\node [right] at (1.2, 0.6) {$\rho$};

\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-complex_branch_4
#| code-fold: true
#| output: asis
#| fig-width: 7
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw [-latex] (-5, 0) -- (5, 0) node[below] {Re$(z)$};
\draw [-latex] (0, -1.3) -- (0, 1.3) node[left] {Im$(z)$};

\draw[teal, very thick, -latex,] ({3+cos(190)}, {sin(190)}) arc (190:280:1);
\draw[teal, very thick, -latex] ({3+cos(280)}, {sin(280)}) arc (280:445:1);
\draw[teal, very thick] ({3+cos(85)}, {sin(85)}) arc (85:170:1);

\draw[teal, very thick, -latex] ({3+cos(170)}, {sin(170)}) -- (0.5, {sin(170)});
\draw[teal, very thick,] (0.5, {sin(170)}) -- ( {-3+cos(10)}, {sin(170)});

\draw[teal, very thick, -latex,] ({-3+cos(10)}, {sin(10)}) arc (10:100:1);
\draw[teal, very thick, -latex,] ({-3+cos(100)}, {sin(100)}) arc (100:265:1);
\draw[teal, very thick,] ({-3+cos(265)}, {sin(265)}) arc (265:350:1);

\draw[teal, very thick, -latex] ({-3+cos(350)}, {sin(350)}) -- (-0.5, {sin(350)});
\draw[teal, very thick,] (-0.5, {sin(350)})-- ({3+cos(190)}, {sin(190)});

\draw[red, very thick] (-3, 0) -- (3, 0);

\filldraw [] (4,0) circle (1.5pt) node [above right] {$A$} ;
\filldraw [] (1.3, {sin(170)}) circle (1.5pt) node[above] {$B$};
\filldraw [] (-1.3, {sin(170)}) circle (1.5pt) node[above] {$C$};
\filldraw [] (-4,0) circle (1.5pt) node [above left] {$D$} ;
\filldraw [] (-1.3, {-sin(170)}) circle (1.5pt) node[below] {$E$};
\filldraw [] (1.3, {-sin(170)}) circle (1.5pt) node[below] {$F$};
\end{tikzpicture}
```

</br>
```{r, engine = 'tikz'}
#| label: fig-complex_cauchy_principal_value_1
#| code-fold: true
#| output: asis
#| fig-width: 8
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.5]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}



\fill [gray!30, domain=0.4:3, variable=\x]
  (0, 2.5)
  -- plot ({\x}, {1/\x})
  -- (3, 0)
  -- (0, 0)
  -- cycle;

\fill [gray!30, domain=-0.4:-3, variable=\x]
  (0, -2.5)
  -- plot ({\x}, {1/\x})
  -- (-3, 0)
  -- (0, 0)
  -- cycle;

\draw [thick, -latex] (-4, 0) -- (4, 0) node[below, scale=1.3] {$x$};
\draw [thick, -latex] (0, -3) -- (0, 3);

\draw [] plot[domain=-0.4:-3.5, variable=\x] ({\x}, {1/\x});
\draw [] plot[domain=0.4:3.5, variable=\x] ({\x}, {1/\x});
\draw[dashed] (0, 2.5) -- (0.4, 2.5);
\draw[dashed] (3, 0.333) -- (3, 0) node[below, scale=1.3] {$x_0+\delta$};

\draw[dashed] (0, -2.5) -- (-0.4, -2.5);
\draw[dashed] (-3, -0.333) -- (-3, 0) node[above, scale=1.3] {$x_0-\delta$};

\node[below right, scale=1.3] at (0, 0) {$x_0$};
\end{tikzpicture}
```



```{r, engine = 'tikz'}
#| label: fig-complex_cauchy_principal_value_2
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.3]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw [thick,-latex] (-5, 0) -- (5, 0) node[below, scale=1.3] {Re$(z)$};
\draw [thick, -latex] (0, -0.5) -- (0, 5);

\draw[teal, very thick, -latex,] (3, 0) arc (0:25:3) node[black,right, scale=1.3] {$C_2$};
\draw[teal, very thick, -latex,] ({3*cos(25)}, {3*sin(25)}) arc (25:180:3);
\draw[teal, very thick, -latex] (-3, 0) -- (-1.5, 0);
\draw[teal, very thick] (-3, 0) -- (-0.5, 0) ;
\node[above, scale=1.3 ] at (-0.2, 0.5) {$C_1$};
\draw[teal, very thick, -latex] (-0.5, 0) arc (180:0:0.5);
\draw[teal, very thick, -latex] (0.5, 0) -- (1.5, 0);
\draw[teal, very thick, ] (1.5, 0) -- (3, 0);
\draw[red, thick, dashed] (0, 0) -- ({0.5*cos(40)}, {0.5*sin(40)}) node [black, scale=1.3, right, xshift=2] {$r$};
\node[black, scale=1.3, above left] at (3, 0) {$R$};
\node[black, scale=1.3, below right] at (0, 0) {$x_0$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-complex_cauchy_principal_value_3
#| code-fold: true
#| output: asis
#| fig-width: 12
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\node [] at (-3, 5) {$(A)$};
\draw [thick,-latex] (-4.5, 0) -- (4.5, 0) node[below, scale=1.3] {Re$(z)$};
\draw [thick, -latex] (0, -0.5) -- (0, 4) node[above, scale=1.3] {Im$(z)$};

\draw[teal, very thick, -latex,] (3, 0) arc (0:25:3) node[black,right, scale=1.3] {$C_R$};
\draw[teal, very thick,] ({3*cos(25)}, {3*sin(25)}) arc (25:180:3);
\draw[teal, very thick, -latex] (-3, 0) -- (-0.5, 0) node[black, below, scale=1.3] {$C_I$};
\draw[teal, very thick] (-0.5, 0) -- (3, 0) ;
\filldraw[black] (0, 0.3) circle (1pt) node [right, scale = 1.3] {$i\varepsilon$};
\draw[thick, -latex] (0, 0) -- ({3*cos(150)}, {3*sin(150)});
\node[above]  at ({1.5*cos(150)}, {1.5*sin(150)}) {$R$};

\begin{scope}[shift={(10,3)}]
\node [] at (-3, 2) {$(B)$};
\draw [thick,-latex] (-4.5, 0) -- (4.5, 0) node[below, scale=1.3] {Re$(z)$};
\draw [thick, -latex] (0, -4) -- (0, 0.5) node[above, scale=1.3] {Im$(z)$};

\draw[teal, very thick, -latex,] (3, 0) arc (0:-20:3) node[black,right, scale=1.3] {$C_R$};
\draw[teal, very thick,] ({3*cos(-20)}, {3*sin(-20)}) arc (-20:-180:3);
\draw[teal, very thick, -latex] (-3, 0) -- (-0.5, 0) node[black, above, scale=1.3] {$C_I$};
\draw[teal, very thick] (-0.5, 0) -- (3, 0) ;
\filldraw[black] (0, -0.3) circle (1pt) node [right, scale = 1.3] {$i\varepsilon$};
\draw[thick, -latex] (0, 0) -- ({3*cos(210)}, {3*sin(210)});
\node[below]  at ({1.5*cos(210)}, {1.5*sin(210)}) {$R$};
\end{scope}
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-complex_infinite_integral
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=1.3]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw [thick,-latex] (-5, 0) -- (5, 0) node[below, scale=1.3] {Re$(z)$};
\draw [thick, -latex] (0, -0.5) -- (0, 5) node[right, scale=1.3] {Im$(z)$};;

\draw[teal, very thick, -latex,] (3, 0) arc (0:80:3) node[black,above, scale=1.3] {$C_R$};
\draw[teal, very thick,] ({3*cos(80)}, {3*sin(80)}) arc (80:180:3);
\draw[teal, very thick, -latex] (-3, 0) -- (1.5, 0) node[black, below, scale=1.3] {$C_I$};
\draw[teal, very thick, ] (1.5, 0) -- (3, 0);
\draw[thick, -latex] (0, 0)-- ({3*cos{130}}, {3*sin(130)});
\node[above, black, scale=1.3] at ({1.5*cos{130}}, {1.5 *sin(130)}) {$R$};
\filldraw[black] (1, 0.5) circle (1pt) node [right, scale = 1.3] {$z_1$};
\filldraw[black] (-2.2, 1.4) circle (1pt) node [right, scale = 1.3] {$z_2$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-complex_integral_without_symmetry
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (O) at (0, 0);
\coordinate (P1) at (0, 3);
\coordinate (P2) at ({3*cos(60)}, {3*sin(60)});
\coordinate (P3) at ({3*cos(120)}, {3*sin(120)});

\draw[teal, very thick, -latex] (0, 0) -- (1.5, 0) node[above, black, scale=1.3] {$C_1$};
\draw[teal, very thick] (1.4, 0) -- (3, 0);
\draw[teal, very thick, -latex,] (3, 0) arc (0:60:3) node[black,above, scale=1.3] {$C_R$};
\draw[teal, very thick,] ({3.0*cos(58)}, {3.0*sin(58)}) arc (58:120:3);
\draw[teal, very thick, -latex] ( {3.0*cos(120)}, {3.0*sin(120)}) -- ({1.5*cos(120)}, {1.5*sin(120)}) node [left, black, scale=1.3] {$C_2$};
\draw[teal, very thick] ({1.6*cos(120)}, {1.6*sin(120)}) -- (O);

\filldraw[black] (O) circle (1.5pt);
\filldraw[black] ({cos(60)}, {sin(60)}) circle (1.5pt);
\filldraw[black] ({cos(180)}, {sin(180)}) circle (1.5pt);
\filldraw[black] ({cos(300)}, {sin(300)}) circle (1.5pt);

\draw[red, thick, -latex] (0.6, 0) arc (0:120:0.6);
\node[above, scale=1.3] at (0, 0.6) {$\frac{3\pi}{2}$};

\end{tikzpicture}
```

