---
title: "Fig-complex-test"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 

```{r, engine = 'tikz'}
#| label: fig-complex_integral_avoiding_branch
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\coordinate (O) at (0, 0);
\coordinate (P1) at (0, 3);
\coordinate (P2) at ({3*cos(60)}, {3*sin(60)});
\coordinate (P3) at ({3*cos(120)}, {3*sin(120)});

\draw[teal, very thick, -latex] (0.1, 0) -- (1.5, 0) node[above, black, scale=1.3] {$C_1$};
\draw[teal, very thick] (1.4, 0) -- (3, 0);
\draw[teal, very thick, -latex,] (3, 0) arc (0:60:3) node[black,above, scale=1.3] {$C_R$};
\draw[teal, very thick,] ({3.0*cos(58)}, {3.0*sin(58)}) arc (58:120:3);
\draw[teal, very thick, -latex] ( {3.0*cos(120)}, {3.0*sin(120)}) -- ({1.5*cos(120)}, {1.5*sin(120)}) node [left, black, scale=1.3] {$C_2$};
\draw[teal, very thick] ({1.6*cos(120)}, {1.6*sin(120)}) -- ({0.1*cos(120)}, {0.1*sin(120)});

\draw[teal, very thick] (0.1, 0) arc (0:120:0.1);

\filldraw[black] (O) circle (1.5pt);
\filldraw[black] ({cos(60)}, {sin(60)}) circle (1.5pt);
\filldraw[black] ({cos(180)}, {sin(180)}) circle (1.5pt);
\filldraw[black] ({cos(300)}, {sin(300)}) circle (1.5pt);

\draw[red, thick, -latex] (0.6, 0) arc (0:120:0.6);
\node[above, scale=1.3] at (0, 0.6) {$\frac{3\pi}{2}$};
\node[above, scale=1.3] at ({0.1*cos(30)}, {0.1*sin(30)}) {$C_\varepsilon$};

\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-complex_exploiting_branch_cuts
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[red, thick] (0.0, 0) -- (3, 0);
\filldraw[color=red, fill=white, thick] (0, 0) circle (1.5pt);

\draw[teal, very thick, -{Latex[length=3mm]}] ({3*cos(2)}, {3*sin(2)}) arc (2:80:3) node[black, above, scale=1.3] {$C_R$};
\draw[teal, very thick, -{Latex[length=3mm]}] ( {3*cos(80)}, {3*sin(80)}) arc (80:280:3);
\draw[teal, very thick,] ( {3*cos(280)}, {3*sin(280)}) arc (280:358:3);
\draw[teal, very thick, -{Latex[length=3mm]}] ({3*cos(2)}, {-3*sin(2)}) -- ({3*cos(2)-2}, {-3*sin(2)}) node[below, black, scale=1.3] {$C_2$};
\draw[teal, very thick, ] ({3*cos(2)-2}, {-3*sin(2)}) -- ({0.3*cos(20.43)}, {-0.3*sin(20.43)});
\draw[teal, very thick, -{Latex[length=3mm]}] ({0.3*cos(20.43)}, {-0.3*sin(20.43)}) arc ({360-20.43}:170:0.3) node [left, black, scale=1.3] {$C_\varepsilon$};
\draw[teal, very thick] ({-0.3}, {0}) arc (180:20.43:0.3);
\draw[teal, very thick, -{Latex[length=3mm]}] ({0.3*cos(20.43)}, {0.3*sin(20.43)}) -- ({3*cos(2)-1}, {3*sin(2)}) node[above, black, scale=1.3] {$C_1$};
\draw[teal, very thick] ({3*cos(2)-1}, {3*sin(2)}) -- ({3*cos(2)}, {3*sin(2)});

\filldraw[black] (0, 1) circle (1pt);
\filldraw[black] (0, -1) circle (1pt);

\end{tikzpicture}
```

</br>

```{r, engine = 'tikz'}
#| label: fig-complex_exploiting_periodicity_1
#| code-fold: true
#| output: asis
#| fig-width: 5
#| fig-align: center
#| fig-cap: "적분 경로"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[teal, very thick, -{Latex[length =3mm]}] (-3, -2) -- (-0.5, -2) node [black, below, scale=1.3] {$A$};
\draw[teal, very thick] (-0.5, -2) 
  -- (3, -2) node[black,right , scale=1.3] {$R$} 
  -- (3, 0) node [black, right, scale=1.3] {$i\pi + R$};
\draw[teal, very thick, -{Latex[length =3mm]}]  (3, 0) -- (1.5, 0) node[black, above, scale=1.3] {$B$};
\draw[teal, very thick] (1.5, 0) -- (0.3, 0);
\draw[teal, very thick] (0.3, 0) arc (0:180:0.3);
\draw[teal, very thick, -{Latex[length =3mm]}] (-0.3, 0) -- (-2, 0) node[black, above, scale=1.3] {$B^\prime$};
\draw[teal, very thick] (-2, 0) 
  -- (-3, 0) node[black, left, scale=1.3] {$i\pi - R$}
  -- (-3, -2) node [black, left, scale=1.3] {$-R$};

\draw[thick, dashed] (0, -2.5) -- (0, 0.5);
\filldraw[blue, thick] (0, 0) circle (1pt);
\node[below right, scale=1.3] at (0, -2) {$O$};

\end{tikzpicture}
```