---
title: "미분형식과 적분형식"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 

{{< include ../../latexmacros.qmd >}}

</br>

## 미분 형식

텐서를 공부해보면 직교좌표계를 벗어나는 경우 매우 복잡해 진다는 것을 알게 된다. 심지어 구면좌표나 원통좌표와 같은 전통적인 좌표계를 도입할 때조차도 그렇다. 이러한 어려움의 상당 부분은 좌표계로 표현된 메트릭이 위치에 의존하게 되고, 일정한 좌표값을 갖는 선이나 면이 곡선화된다는 사실에서 기인한다. 물리학에서 가장 중요한 상황들은 국소적으로 직교좌표계 기반의 단순하고 친숙한 조건과 유사해지기 때문에, 미소 변위(infinitesimal displacement)를 다루는 기하학을 적용하면 이러한 복잡한 문제 대부분을 피할 수 있다.

**미분형식(differential forms)**의 미적분학은 곡선좌표계를 다루는 자연스럽고 강력한 도구로 인정받고 있으며, 고전적 맥락과 현대의 굽은 시공간 연구 모두에서 널리 사용된다. 이 분야의 선구자인 엘리 카르탕(Élie Cartan)이 개발한 이 미적분학은 벡터 해석학의 개념과 정리를 놀라울 정도로 통합하여, 미분기하학과 이론 물리학에서 미분형식의 활용이 확산되는 결과를 가져왔다.

미분형식은 물리학에서 기하학의 역할을 이해하는 중요한 접근법을 제공하며, 논의되는 공간의 연결성(위상수학적 특성)은 물리적 함의를 지닙니다. 단순한 예로, 원 위에서 정의된 좌표는 모든 각도에서 단일값(single-valued)이면서 연속적일 수 없다는 사실에서도 이를 확인할 수 있다. 한편 위상수학(topology)의 보다 복잡한 물리적 결과물에는 게이지 변환(gauge transformation), 플럭스 양자화(flux quantization), 보옴-아하로노프 효과(Bohm-Aharanov effect), 기본 입자 이론의 발전, 일반상대성이론 현상 등이 포함된다. (이 중 상당수는 본문의 범위를 벗어난다.)

</br>

### 들어가며 {#sec-Tensor_introduction_to_differential_form}

우선 3차원 공간에서의 미분형식에서 시작한다. 여기서는 일단 3차원에서 다루지만 다차원이나 메트릭에 제한되지 않는다. 기본이 되는 양은 **미분(differentials)** 이라고 불리는 $dx,\,dy,\,dz$ 이다. 이 미분은 기존의 변화를 말한다기 보다는 일종의 연산자로 작용한다. 이 미분을 이용하면 다음과 같은 표현이 가능하다. (이를 **1-형식(1-form)** 이라고 한다.)

$$
\bf{\omega}= A(x,\,y,\,z)\,dx + B(x,\,y,\,z)\, dy + C(x,\,y,\,z)\,dz.
$$ {#eq-Tensor_example_of_1_form}

이 1-형식은 선적분과 관련되어 있다. 

**2-형식(2-form)** 은 다음과 같으며 표먼 적분과 관련되어 있다.

$$
\bf{\omega} = F(x,\,y,\,z) \, dx \wedge dy + G(x,\,y,\,z)\, dy \wedge dz + H(x,\,y,\,z)\, dz\wedge dx.
$${#eq-Tensor_example_of_2_form}

위와 같이 두 외적을 $\wedge$ 를 이용해 곱하는 것을 **외적(exterior product)** 혹은 **쐐기곱(wedge product)** 라고 한다.

**3-형식(3-form)** 은 공간 적분과 관련되어 있으며 아래의 꼴이다.

$$
\bf{\omega} = K(x,\,y,\,z) \, dx \wedge dy \wedge dz.
$${#eq-Tensor_example_of_3_form}


쐬기 혹은 wedge 라고 불리는 $\wedge$ 기호는 각각의 미분을 결함하여 좀 더 복잡한 무언가를 만드는데 사용되며, **외대수(exterior algebra)** 혹은 그라스만 대수(Grassmann algebra) 라고 불리는 규칙을 따른다. 일부 문서에서는 독자가 외대수에 익숙하다고 생각하고 $\wedge$ 기호를 빼버리기도 한다. 2차원 혹은 3차원으로 고정시키지 않기 위해 미분을 $dx_i$ 와 같이 사용하기도 하며 여러개의 미분을 외대수로 결합시킬 수 있다. $p$ 개의 미분을 결합시킨 것을 **$p$-형식($p$-form)** 이라고 한다.

미분형식은 미분다양체에서의 미적분학을 체계화 하기 위해 발전했다. 미분다양체는 느슨하게 말하자면 국소적으로 무한번 미분 가능한 점들의 집합이다. 

</br>

### 외대수 (Exterior algebra) {#sec-Tensor_exterior_algebra}

외대수의 연산은 permutationally antisymmetic 하도록 정의된다. 기저가 되는 1-형식을 $dx_i$ 와 같이 표기하고 임의의 형식 $\omega_j$ 는 $p_j$-형식이라고 하자. 이 때 다음 규칙을 따른다. 아래 식에서 $a,\,b$ 는 임의의 스칼라이다. 

&emsp;($1$) **분배 규칙**: $p_1=p_2$ 일 때 $(a\omega_1 + b\omega_2) \wedge \omega_3 = a \, \omega_1 \wedge \omega_3 + b\,  \omega_2 \wedge \omega_3$,

&emsp;($2$) **Associativity**: $(\omega_1 \wedge \omega_2) \wedge \omega_3 = \omega_1 \wedge (\omega_2 \wedge \omega3)$,

&emsp;($3$) **스칼라곱**: $a(\omega_1 \wedge \omega_2) = (a\omega_1) \wedge \omega_2$, 

&emsp;($4$) **반대칭성**: $dx_i \wedge dx_j = - dx_j \wedge dx_i$.

</br>

위의 규칙으로부터 다음을 알 수 있다.

- $dx_i \wedge dx_i = 0$

- 외적의 순서가 중요하다. 

- 여러 미분을 결합한 외적에 대해서는 괄호를 할 필요가 없다.

</br>

위의 규칙중에서 가장 중요한 것은 반대칭성이다. $p$-형식에서 외적이 구성되는 순서가 중요하다는 의미이며 또한 외적에 방향성(orientation) 이 존재한다는 의미이다. 



</br>

### 호지 연산자 {#sec-Tensor_hodge_operator}

호지 연산자(Hodge operator, 혹은 star operator) $\ast$ 는 미분형식의 dual form 으로 $d$ 차원의 $p$-형식에 대해 $(d-p)$-형식을 반환한다. 이를 원래 형식에 대한 **쌍대 형식(dual form)** 이라고 한다. 즉 3 차원 1-형식 에 대해 호지 연산자를 적용하면 3차원 2-형식이 된다. 앞으로 보겠지만 미분형식으로 계산하는 것보다 호지 연산자를 이용하여 계산하는 것이쉬운 경우가 많이 있다. <u>원래의 기저가 직교 기저가 아닐 경우 연산이 매우 복잡해지므로 여기서는 원래의 기저가 서로 직교하는 직교 기저, 그중에서도 유클리드 메트릭과 민코프스키 메트릭을 갖는 공간에서만 생각하기로 하자.</u> 

$p$-형식인 $\omega$ 의 쌍대 형식 $\ast\omega$ 를 구하는 것은 우선 $\omega$ 에 포함되지 않은 1-형식들의 외적 $\omega'$ 을 구하는 것으로부터 시작한다. 그리고 두 개의 절대값이 1인 수를 곱해준다.


($1$) $\omega$ 의 인덱스와 $\omega'$ 의 인덱스를 $\omega$ 부터 나란히 적은 다음에 그것이 $(1,\,2,\,\ldots,\,p)$ 의 짝수번의 호환으로 표현되는지, 홀수번이 호환으로 표현되는지(행렬식에서 많이 했던 짓) 에 따라 각각 $+1,\, -1$ .

($2$) 유클리드 혹은 민코프스키 메트릭만 사용하므로 대각성분을 제외한 메트릭의 성분은 모두 $0$ 이다. $\omega$ 에 속한 기저중 $-1$ 을 메트릭의 대각 성분으로 갖는 기저의 갯수 $\mu$ 에 대해 $(-1)^\mu$.   


위의 ($1$), ($2$) 에 의해 결정되는 두 수를 각각 $\omega'$ 앞에 곱해준 것이 $\ast \omega$ 이다.

예를 들어 4차원의 2-형식 $\omega = dx_1 \wedge dx_3$ 을 생각하자. $\omega'=dx_2 \wedge dx_4$ 에 대해 $(1, 3, 2, 4)$ 는 $(2, 3)$ 이므로 $\ast \omega = -  dx_2 \wedge dx_4$ 이다. 

유클리드 3차원 공간에서는 다음이 성립한다.

$$
\boxed{
\begin{gather}
*1 = dx_1 \wedge dx_2 \wedge dx_3, \\[0.3em]
*dx_1 = dx_2 \wedge dx^3,\qquad *dx_2 = dx_3 \wedge dx_1,\qquad dx_3 = dx_1 \wedge dx_2,\\[0.3em]
*(dx_1 \wedge dx_2) = dx_3,\qquad (dx_2 \wedge dx_3) = dx_1, \qquad (dx_3 \wedge dx_1) = dx_2,\\[0.3em]
*(dx_1 \wedge dx_2 \wedge dx_3) = 1.
\end{gather}}
$$ {#eq-Tensor_hodge_operator_for_3d_euclidean_space}

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_hodge_operator_in_minkowski_space}

#### 민코프스키 공간에서의 호지 연산자
</br>
1-형식 기저를 $(dt,\,dx_1,\,dx_2,\,dx_3)$ 로 하고 메트릭 텐서가 아래와 같다고 하자.

$$
\left[\begin{array}{rrrr} 1 & 0 & 0 & 0 \\ 0 & -1 & 0 & 0 \\ 0 & 0 & -1 & 0 \\ 0 & 0 & 0 & -1 \end{array}\right]
$$

여기서 $i,\,j,\,k$ 를 $1,\,2,\,3$ 의 cyclic permutation 이라고 하면

$$
\boxed{
\begin{gather}
\ast 1 = dt \wedge dx_1 \wedge dx_2 \wedge dx_3, \\[0.3em]
\ast dt = dx_1 \wedge dx_2 \wedge dx_3,\qquad \ast dx_i = dt \wedge dx_j \wedge dx_k, \\[0.3em]
\ast (dx_j \wedge dx_k) = dt \wedge dx_i,\qquad *(dt \wedge dx_i) = -(dx_j \wedge dx_k), \\[0.3em]
\ast(dt \wedge dx_1 \wedge dx_2 \wedge dx_3) = -1
\end{gather}}
$${#eq-Tensor_hodge_operator_for_minkowski_space}

이다.

:::
</div>


</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_miscellaneous_differential_forms}

#### 여러가지 미분 형식
</br>
$\R^3$ 에서 $A=A_x\,dx + A_y \,dy+ A_z\,dz$ 와 $B=B_x\,dx+B_y\,dy+B_z\,dz$ 라는 두 1-형식을 생각하자.

$$
\begin{aligned}
A\wedge B &= (A_yB_z-A_zB_y) (dy \wedge dz) + (A_zB_x - A_xB_z)(dz \wedge dx) \\[0.3em]
&\qquad + (A_xB_y -A_yB_x)(dx \wedge dy)
\end{aligned}
$$

이며,

$$
*(A\wedge B) = (A_yB_z-A_zB_y)\,dx + (A_zB_x - A_xB_z)\, dy + (A_xB_y -A_yB_x)\,dz
$$

이다. 이제 벡터 $\bf{A}=(A_x,\,A_y,\,A_z),\, \bf{B}=(B_x,\,B_y,\,B_z)$ 를 생각하면, 

$$
*(A \wedge B) = (\bf{A}\times \bf{B})_x\,dx + (\bf{A}\times \bf{B})_y\,dy + (\bf{A}\times \bf{B})_z\,dz
$$

임을 알 수 있다. 

이제 다른 1-형식 $C=C_x\,dx + C_y\,dy+C_z\,dz$ 과 $\bf{C}=(C_x,\,C_y,\,C_z)$ 에 대해  $(A\wedge B \wedge C)$ 를 계산해 보면 다음이 성립함을 알 수 있다. 

$$
A \wedge B \wedge C = \det\left(\begin{bmatrix} A_x & A_y & A_z\\ B_x & B_y & B_z \\ C_x & C_y & C_z\end{bmatrix}\right)(dx \wedge dy \wedge dz) = \bf{A} \cdot (\bf{B}\times \bf{C})(dx \wedge dy \wedge dz)
$$

따라서

$$
*(A \wedge B \wedge C) = \bf{A} \cdot (\bf{B}\times \bf{C})
$$

이다.

:::
</div>

<br>

## 형식의 미분

### 외미분 {#sec-Tensor_exterior_derivatives}

외대수와 이에 따른 외적에 대한 미분, 즉 외미분이 존재한다. $\omega,\,\omega'$ 이 각각 $p$-, $p'$-형식이라고 하자. 그리고 $f$ 는 일반적인 함수, 즉 $0$-형식 이라고 하자. 이 때 다음이 성립한다.

$$
\boxed{
  \begin{gather}
  d(\omega + \omega') = d\omega + d\omega', \quad(p=p')\tag{1}\\[0.3em]
  d(f\omega) = (df)\wedge \omega + fd\omega, \tag{2}\\[0.3em]
  \quad d(\omega \wedge \omega') = d\omega \wedge \omega' + (-1)^p \omega \wedge d\omega',\quad \tag{3}\\[0.3em]
  d(d\omega) = 0, \tag{4}\\[0.3em]
  df = \sum_j \dfrac{\partial f}{\partial x_j}\tag{5}\, dx_j.
\end{gather}
}
$$ {#eq-Tensor_exteror_derivative}

위 식은 외미분에 대한 공리(axiom) 이다. 따라서 일관성을 요구할 뿐 증명을 필요로 하지 않는다. 


</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_exterior_derivative}

#### 외미분
</br>

@eq-Tensor_exteror_derivative 의 ($3$) 은 $(-1)^p$ 때문에 약간 의아 할 수 있다. 이것을 우선 이것을 확인해 보자. $\omega = a\,dx_1 \wedge \cdots \wedge dx_p$, $\omega' = b\, dx_1 \wedge \cdots \wedge dx_{p'}$ 라고 해 보자. 

$$
\omega \wedge \omega' = ab\, [dx_1 \wedge \cdots \wedge dx_p]\wedge [dx_1 \wedge \cdots \wedge dx_{p'}].
$$

이제 $d(\omega \wedge \omega')$ 을 생각해 보자.

$$
\begin{aligned}
d(\omega \wedge \omega') &= d(ab)\, [dx_1 \wedge \cdots \wedge dx_p]\wedge [dx_1 \wedge \cdots \wedge dx_{p'}] \\[0.3em]
&= \sum_\mu \left[\dfrac{\partial a}{\partial x_\mu} b + a\dfrac{\partial b}{\partial x^\mu}\right] \,dx_\mu \wedge [dx_1 \wedge \cdots \wedge dx_p]\wedge [dx_1 \wedge \cdots \wedge dx_{p'}] \\[0.3em]
&= \left[\sum_\mu \left(\dfrac{\partial a}{\partial x_\mu} \right) dx_\mu \wedge [dx_1 \wedge \cdots \wedge dx_p] \right]\wedge \left(b\, [dx_1 \wedge \cdots \wedge dx_{p'}] \right)  \\[0.3em]
&\qquad + (-1)^p\left(a\,[dx_1 \wedge \cdots \wedge dx_{p'}]\right)\left[\sum_{\mu} \left(\dfrac{\partial b}{\partial x_\mu}\right)  dx_\mu \wedge[dx_1 \wedge \cdots \wedge dx_{p'}] \right] \\[0.3em]
&=d\omega \wedge \omega' + (-1)^p \omega \wedge d\omega'
\end{aligned}
$$

이다. 여기서 $dx_\mu \wedge[dx_1 \wedge \cdots \wedge dx_p]= (-1)^p[dx_1 \wedge \cdots \wedge dx_p]\wedge dx_\mu$ 를 사용하였다. 

($4$) 의 $d(d\omega)=0$ 은 때때로 푸앙카레 소정리(Poincaré lemma) 라고도 한다. 이 공리는 필요하며, 다른것과 일관된다. 일단 이것이 없다면 $d(dx_i)$ 를 형식으로 만들 수 없다. 다른 공리와의 일관성을 보기 위해 $\R^2$ 에서의 예를 들어 보자. ($5$) 로 부터

$$
df = \dfrac{\partial f}{\partial x}dx + \dfrac{\partial f}{\partial y}dy
$$

이며 ($2$) 와 외적의 반대칭성으로부터

$$
\begin{aligned}
d(df) = \dfrac{\partial}{\partial x}\dfrac{\partial f}{\partial x} dx \wedge dx + \dfrac{\partial}{\partial y}\dfrac{\partial f}{\partial x} dy\wedge dx + \dfrac{\partial }{\partial x}\dfrac{\partial f}{\partial y}  dx \wedge dy + \dfrac{\partial }{\partial y}\dfrac{\partial f}{\partial y}  dy \wedge dy = 0
\end{aligned}
$$

임을 알 수 있다. 푸앙카레 소정리는 전미분 함수는 불변량임을 의미한다. 

:::
</div>

</br>

### 3차원 공간에서의 외미분 {#sec-Tensor_exterior_derivatives_in_3d}

3차원 공간에서의 스칼라 함수 $f=f(x,\,y,\,z)$ 에 대해

$$
df = \dfrac{\partial f}{\partial x}\,dx + \dfrac{\partial f}{\partial y}\,dy + \dfrac{\partial f}{\partial z}\,dz
$$ {#eq-Tensor_exterior_derivative_1}

이다. 여기서 1-형식 $\omega = A_x\,dx + A_y \,dy + A_z\,dz$ 에 대해

$$
\begin{aligned}
d\omega &= \sum_{r=x,y,z} \sum_{s=x,\,y,\,z}\dfrac{\partial A_s}{\partial r}\, dr \wedge ds  \\[0.3em]
&= \left[\dfrac{\partial A_z}{\partial y} - \dfrac{\partial A_y}{\partial z}\right] (dy \wedge dz) + \left[\dfrac{\partial A_x}{\partial z} - \dfrac{\partial A_z}{\partial x}\right] (dz \wedge dx) + \left[\dfrac{\partial A_y}{\partial x} - \dfrac{\partial A_x}{\partial y}\right] (dx \wedge dy)
\end{aligned}
$$ {#eq-Tensor_exterior_derivative_2}

이며, 

$$
\ast(d(A_x\,dx + A_y \,dy + A_z\,dz)) = (\nabla \times \bf{A})_x\, dx + (\nabla \times \bf{A})_y\, dy + (\nabla \times \bf{A})_z\, dz
$$ {#eq-Tensor_exterior_derivative_of_1-form_in_3dim}

임을 알 수 있다. 

이제 2 형식 $B_x (dy \wedge dz) + B_y (dz \wedge dx) + B_z (dx \wedge dy)$ 에 대한 외미분을 생각해 보자.

$$
\begin{aligned}
d(B_x (dy \wedge dz) + B_y (dz \wedge dx) + B_z (dx \wedge dy)) &= \left[\dfrac{\partial B_x}{\partial x} + \dfrac{\partial B_y}{\partial y} + \dfrac{\partial B_z}{\partial z}\right]( dx \wedge dy \wedge dz) \\[0.3em]
&= (\nabla \bf{\cdot B})(dx \wedge dy \wedge dz)
\end{aligned}
$$

이며, 따라서

$$
\ast d(B_x (dy \wedge dz) + B_y (dz \wedge dx) + B_z (dx \wedge dy)) = (\nabla \bf{\cdot B})
$$ {#eq-Tensor_exterior_derivative_of_2-form_in_3dim}


이다. 

이제 @eq-Tensor_exterior_derivative_1 을 다시 보자 $df$ 는 1-형식 이므로 @eq-Tensor_exterior_derivative_2 과 푸앙카레 소정리를 생각하면 

$$
0=d(df)= (\nabla \times (\nabla f))_x (dy\wedge dz) + (\nabla \times (\nabla f))_y (dz\wedge dx) + (\nabla \times (\nabla f))_z (dx\wedge dy) 
$$

이다. 즉 위 식은 우리가 잘 아는 항등식 $\nabla \times (\nabla f)=0$ 과 동치이다. 우리가 아는 다른 하나의 항등식 $\nabla \bf{\cdot} (\nabla \times \bf{A})=0$ 역시 

$$
0 = d(d(A_x\,dx + A_y\,dy + A_z\,dz))= (\nabla \bf{\cdot} (\nabla \times \bf{A}))(dx \wedge dy \wedge dz)
$$

과 동치임을 알 수 있다. 

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_maxwell_equation}

#### 멕스웰 방정식
</br>

멕스웰 방정식은 형식의 미분 형식으로 표현할 때 메우 우아하고 간결하게 표현 될 수 있다. 이 표기법에서 전자기장 텐서의 독립적인 성분은 $(cdt,\,dx,\,dy,\,dz) = (dx_0,\,dx_1,\,dx_2,\,dx_3)$ 기저에서의 2-형식으로 다음과 같이 쓸 수 있다.

$$
\boxed{
\begin{aligned}
\quad F & :=-\dfrac{E_x}{c} dx_0 \wedge dx_1- \dfrac{E_y}{c} dx_0 \wedge dx_2- \dfrac{E_z}{c} dx_0 \wedge dx_3 \\[0.3em]
&\qquad\qquad  + B_x dx_2\wedge dx_3 + B_y dx_3 \wedge dx_1+ B_z dx_1\wedge dy. \quad
\end{aligned}
}
$${#eq-Tensor_maxewll_equation}

또한 장의 소스들은 아래와 같은 3-형식으로 쓸 수 있다.

$$
\boxed{
\begin{aligned}
\quad J &:= c\rho (dx_1\wedge dx_2\wedge dx_3) -  J_x (dx_0\wedge dx_2\wedge dx_3) \\[0.3em]
&\qquad \qquad- J_y (dx_0\wedge dx_3 \wedge dx) - J_z (dx_0\wedge dx_1\wedge dy).
\end{aligned}
}
$${#eq-Tensor_electromagnetic_source_equation}

이제 멕스웰 방정식은 $dF=0$ 으로 부터 간단하게 얻어진다.

$$
\begin{aligned}
dF =& -\left[\dfrac{\partial E_x/c}{\partial x_2}\,dx_2+ \dfrac{\partial E_x/c}{\partial x_3}\,dx_3\right] \wedge (dx_0\wedge dx)-\left[\dfrac{\partial E_y/c}{\partial x_1}\,dx_1+ \dfrac{\partial E_y/c}{\partial x_3}\,dx_3\right] \wedge (dx_0\wedge dx_2) \\[0.3em]
& -\left[\dfrac{\partial E_z/c}{\partial x}\,dx_1+ \dfrac{\partial E_z/c}{\partial x_2}\,dx_2\right] \wedge (dx_0\wedge dx_3)  + \left[\dfrac{\partial B_x}{\partial x_0}\,dx_0+ \dfrac{\partial B_x}{\partial x_1}\,dx_1\right] \wedge (dx_2\wedge dx_3) \\[0.3em]
& +\left[\dfrac{\partial B_y}{\partial x_0}\,dx_0+ \dfrac{\partial B_y}{\partial x_2}\,dx_2\right] \wedge (dx_3 \wedge dx_1) + \left[\dfrac{\partial B_z}{\partial x_0}\,dx_0+ \dfrac{\partial B_z}{\partial x_3}\,dx_3\right] \wedge (dx_1\wedge dx_2) \\[0.3em]
=& \left[\dfrac{\partial E_z/c}{\partial x_2}-\dfrac{\partial E_y/c}{\partial x_3} + \dfrac{\partial B_x}{\partial x_0}   \right](dx_0\wedge dx_2\wedge dx_3) + \left[\dfrac{\partial E_x}{\partial x_3} - \dfrac{\partial E_z}{\partial x_1} + \dfrac{\partial B_y}{\partial x_0}\right](dx_0\wedge dx_3 \wedge dx_1) \\[0.3em]
&+ \left[\dfrac{\partial E_y}{\partial x_1} - \dfrac{\partial E_x}{\partial x_2} + \dfrac{\partial B_z}{\partial x_0}\right](dx_0\wedge dx_1\wedge dx_2)  + \left[\dfrac{\partial B_x}{\partial x_1} + \dfrac{\partial B_y}{\partial x_2} + \dfrac{\partial B_z}{\partial x_3}\right](dx_1\wedge dx_2\wedge dx_3)
\end{aligned}
$$

이므로 $dF=0$ 으로부터, 그리고 $(x_0,\,x_1,\,x_2,\,x_3) \to (ct,\,x,\,y,\,z)$ 변환을 수행하면 

$$
\nabla \times \bf{E} = - \dfrac{\partial \bf{B}}{\partial t},\qquad \nabla \bf {\cdot B} = \bf{0}
$$

을 얻는다. 

이제 $\ast F$ 를 보자

$$
\begin{aligned}
\ast F = & \dfrac{E_x}{c} dx_2\wedge dx_3 + \dfrac{E_y}{c} dx_3 \wedge dx_1+ \dfrac{E_z}{c} dx_1\wedge dx_2+ B_x dx_0\wedge dx_1+ B_y dx_0\wedge dx_2+ B_z dt\wedge dx_3
\end{aligned}
$$

이며,

$$
\begin{aligned}
d(\ast F)=& \left[\dfrac{\partial E_x/c}{\partial x_1}\,dx_1+ \dfrac{\partial E_x/c}{\partial x_0}\,dx_0\right]\wedge (dx_2\wedge dx_3) + \left[\dfrac{\partial E_y}{\partial x_0}\,dx_0+ \dfrac{\partial E_y/c}{\partial x_2}\,dx_2 \right] \wedge (dx_3 \wedge dx_1) \\[0.3em]
&+\left[\dfrac{\partial E_z/c}{\partial x_3} \, dx_3 + \dfrac{\partial E_z/c}{\partial x_0}\,dx_0\right]\wedge (dx_1\wedge dx_2) + \left[\dfrac{\partial B_x}{\partial x_2}\,dx_2+ \dfrac{\partial B_x}{\partial x_3}\,dx_3\right]\wedge (dx_0\wedge dx_1) \\[0.3em]
&+ \left[\dfrac{\partial B_y}{\partial x_1}\,dx_1+ \dfrac{\partial B_y}{\partial x_3}\,dx_3\right] \wedge (dx_0\wedge dx_2) + \left[\dfrac{\partial B_z}{\partial x_1}\,dx_1+ \dfrac{\partial B_z}{\partial x_2}\,dx_2 \right]\wedge (dx_0\wedge dx_3) \\[0.3em]
=& \left[\dfrac{\partial E_x/c}{\partial x_1} +\dfrac{\partial E_y/c}{\partial x_2} + \dfrac{\partial E_z/c}{\partial x_3}\right](dx_1\wedge dx_2\wedge dx_3) + \left[\dfrac{\partial E_x/c}{\partial x_0} -\dfrac{\partial B_z}{\partial x_2} + \dfrac{\partial B_y}{\partial x_3}\right](dx_0\wedge dx_2\wedge dx_3) \\[0.3em]
=& \left[\dfrac{\partial E_y/c}{\partial x_0} - \dfrac{\partial B_x}{\partial x_3} + \dfrac{\partial B_z}{\partial x_1}\right](dx_0\wedge dx_3 \wedge dx_1) + \left[\dfrac{\partial E_z/c}{\partial x_0} - \dfrac{\partial B_y}{\partial x_1} + \dfrac{\partial B_x}{\partial x_2}\right](dx_0\wedge dx_1\wedge dx_2)
\end{aligned}
$$

이며 $d(\ast F)=\mu_0J$ 로부터 (그리고 $\varepsilon_0 \mu_0 = 1/c^2$ 을 이용하면 )

$$
\nabla \bf{\cdot E} = \dfrac{\rho}{\epsilon_0},\qquad \nabla \times \bf{B} = \dfrac{1}{c^2} \dfrac{\partial \bf{E}}{\partial t} + \mu_0 \bf{J} 
$$

을 얻는다. 마지막으로 $dJ = \dfrac{1}{\mu_0} d(d(\ast F))=0$ 이므로 

$$
dJ = \left[\dfrac{\partial \rho}{\partial t} + \dfrac{\partial J_x}{\partial x} + \dfrac{\partial J_y}{\partial y} + \dfrac{\partial J_z}{\partial z}\right] (dt \wedge dx \wedge dy \wedge dz) 
$$

로 부터 전하에 대한 연속 방정식 (equation of continuity)

$$
\dfrac{\partial \rho}{\partial t} + \nabla \bf{\cdot J} = 0
$$

을 얻는다. 

요약하자면, @eq-Tensor_maxewll_equation, @eq-Tensor_electromagnetic_source_equation 로 정의된 $F,\, J$ 에 대해 맥스웰 방정식은 아래의 간단한 두 식으로 정리된다.

$$
dF=0,\qquad d(\ast F)= J
$$

또한 연속 방정식은 위의 정의로부터 자연스럽게 유도된다.


:::
</div>

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_6_1}
#### Arfken 4.6.1

두 1-형식 $\omega_1 = xdy +ydx$ 와 $\omega_2 = xdy - ydx$ 에 대해 다음을 계산하라.

($a$) $d\omega_1$,

($b$) $d\omega_2$, 

($c$) ($a$), ($b$) 가운데 $0$ 이 아닌 것에 대해 $d(d\omega_i)=0$ 임을 보여라.

:::

</div>

</br>

::: {.solution}

($1$) $d\omega_1 = dx \wedge dy -  dx \wedge dy = 0$.

($2$) $d\omega_2 = dx \wedge dy - dy \wedge dx = 2 dx \wedge dy$.

($3$) $d(dx \wedge dy) =  0$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_6_2}
#### Arfken 4.6.2

$\omega_3 = xy\,dz +xz\, dy - yz\, dx$ 에 대해 $d(d\omega_3)=0$ 임을 보여라.

:::

</div>

</br>

::: {.solution}
$$
\begin{aligned}
d\omega_3 &= ydx \wedge dz + x dy \wedge dz + z dx \wedge dy + x dz \wedge dy - z dy \wedge dx - y dz \wedge dx \\
&= -2y dz \wedge dx + 2z dx \wedge dy
\end{aligned}
$$

이며
$$
d(d\omega_3) = -2 dx \wedge dy \wedge dx + 2 dx \wedge dy \wedge dy = 0
$$

이다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_6_3}
#### Arfken 4.6.3

@exr-Arfken_4_6_1, @exr-Arfken_4_6_3 의 $\omega_2,\,\omega_3$ 에 대해 $d(\omega_2 \wedge \omega_3)$ 를 아래의 두 방식으로 계산하여 결과가 같음을 보여라.

($a$)  외적을 계산하고 미분하라.

($b$) 두 형식의 곱에 대한 미분 공식을 이용하라.
:::

</div>

</br>

::: {.solution}

($a$) 

$$\begin{aligned}
\omega_2 \wedge \omega_3 &= (x dy - y dx) \wedge (xy\,dz +xz\, dy - yz\, dx) \\
&= x^2 y dy \wedge dz  + xy^2 dz \wedge dx 
\end{aligned}
$$

이므로

$$
\begin{aligned}
d(\omega_2 \wedge \omega_3) = 4xy dx \wedge dy \wedge dz.
\end{aligned}
$$

($b$) $d(\omega_2 \wedge \omega_3) = d \omega_2 \wedge \omega_3 + (-1)\omega_2 \wedge d\omega_3$ 임을 이용하면

$$
\begin{aligned}
d(\omega_2 \wedge \omega_3) &= (2dx\wedge dy) \wedge (xy\,dz +xz\, dy - yz\, dx) - (xdy - ydx)\wedge (-2y dz \wedge dx + 2z dx \wedge dy) \\
&= 4xy dx \wedge dy \wedge dz.
\end{aligned}
$$

:::

</br>

## 형식의 적분 

### 1-형식의 적분

2 차원 공간에서의 1-형식 $\omega = A_x \,dx + A_y\, dy$ 을 생각하자. $P$ 에서 시작해서 $Q$ 에서 끝나는 경로 $C$ 에 대해 형식을 적분한다고 하자. 즉

$$
\int_C \omega = \int_C {\Large [} A_x \,dx + A_y \, dy{\Large ]}.
$$

이 적분은 일반적인 선적분으로 해석한다. 이 경로 $C$ 를 $(x(t),\,y(t))$ 로 매개화 한다고 하자. 여기서 $t$ 는 $t_P$ 에서 $t_Q$ 까지 단조증가한다. 그렇다면

$$
\int_C \omega = \int_{t_P}^{t_Q} \left[A_x \dfrac{dx}{dt} + A_y \dfrac{dy}{dt}\right]\, dt
$$

이며, 최소한 이론적으로 이 적분을 계산 할 수 있다. 

어떤 경우 이 적분은 경로와 무관하고 오직 시작점 $P$ 와 끝점 $Q$ 에만 의존할 때가 있다. 보존력(conservative force) 를 생각해보라. 형식 $\omega$ 가 어떤 함수 $f$ 의 미분일 때 즉,

$$
\omega = df
$$

일 때 $\omega$ 를 완전 형식(exact form) 이라고 한다. $\R^2$ 에서는

$$
d\omega = \dfrac{\partial f}{\partial x}{dx} + \dfrac{\partial f}{\partial y}dy
$$

이다. $\omega$ 가 $\omega = df$ 의 완전 형식이라면

$$
\int_P^Q \omega = f(Q) - f(P)
$$


</br>

### 2-형식의 적분

2차원 공간에서의 2 형식 $\omega = B(x,\,y)\, dx \wedge dy$ 의 아래와 같은 적분을 생각하자. 

$$
\int_S \omega = \int_S B(x,\,y)\, dx \wedge dy.
$$

여기서 변수를 $x,\,y$ 에서 $u,\,v$ 로 변경시키는 것을 생각하자. $x=au+bv,\, y = eu+fv$ 라고 하면

$$
dx \wedge dy = (adu + bdv)\wedge (edu + fdv) = (af-be)du \wedge dv =\det \left(\begin{bmatrix} a & b \\ e & f \end{bmatrix}\right) du \wedge dv
$$

2 차원 2-형식에서 변수를 변경 시킬 때 자연스럽게 야코비 행렬이 나타났다. 이것은 단지 2차원 2-형식 에서의 상황이 아니라 모든 차원의 모든 형식에서 나타난다. 즉 우리가 일견 부자연스러운 $k$-형식($k$-form)과 $\wedge$ 연산자를 도입한 것은 이러한 변환이 자연스럽게 나타나도록 하기 위한 것이다. 여기서 유의해야 할 것은 $dx \wedge dy = - dy \wedge dx$ 라는 것이다. 즉 형식에 방향(orientation) 이 있다는 것이다.

즉 $(x_1,\,x_2,\ldots)$ 에서 $(q_1,\,q_2,\ldots)$ 로 좌표를 변환한다면 야코비 행렬 $J$ 에 대해

$$
dx_1 \wedge dx_2 \cdots = J dq_1 \wedge dq_e \wedge \cdots
$$

가 된다. 3차원의 경우 @exr-Arfken_4_7_1 을 보라.

</br>

### 스토크스 정리


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-Tensor_stokes_theorem}

$n$ 차원 공간의 단순 연결 영역 $R$ 에서 정의된 $p$-차원 미분다양체를 생각하자. $R$ 의 경계를 $\partial R$ 로 표기하며 $p-1$ 차원이다. $\omega$ 가 $R$ 에서 정의된 $p-1$-형식 $\omega$ 에 대해 그 미분을 $d\omega$ 라고 하면 다음이 성립한다.

$$
\int_R d\omega = \int_{\partial R}\omega .
$$ {#eq-Tensor_stokes_theorem}

:::

</div>

</br>

엄밀한 증명은 이곳의 범위를 넘어선다. 단순한 스케치만 하겠다. $\omega$ 가 다음과 같다고 하자.

$$
\omega = A(x_1,\dots,\,x_p)\, dx_2 \wedge \cdots \wedge dx_p
$$

그렇다면

$$
d\omega = \dfrac{\partial A}{\partial x_1}\,dx_1 \wedge \cdots \wedge dx_p
$$

이다. $\int_R d\omega$ 

$$
\begin{aligned}
\int_R d\omega &= 
\end{aligned}
$$


@thm-VectorCalculus_hemlhomtz_1

</br>


### 연습문제 {.unsigned}


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_7_1}
#### Arfken 4.7.1

$(x,\,y,\,z) \to (u,\,v,\,w)$ 선형변환을 생각하자. $A(x,\,y,\,z)\, dx \wedge dy \wedge dz$ 에 대한 적분을 이와 동등한 $du \wedge dv \wedge dw$ 형태의 적분으로 바꾼다면 야코비 행렬과 동등한 행렬식이 도입됨을 보여라.


:::

</div>
</br>

::: {.solution}

변환 행렬 $\bf{A}=[a_{ij}]$ 를 생각하자. $\bf{x}=\begin{bmatrix} x & y & z\end{bmatrix}^T$, $\bf{u}=\begin{bmatrix} u & v & w\end{bmatrix}^T$ 에 대해 $\bf{x}=\bf{Au}$ 라고 하자. 

$$
\begin{aligned}
dx \wedge dy \wedge dz &= (a_{11} du + a_{12}dv + a_{13}dw)\wedge (a_{21} du + a_{22}dv + a_{23}dw) \\ &\qquad  \wedge (a_{31} du + a_{32} dv + a_{33}dw) \\[0.3em]
&=(a_{11}a_{22}a_{33}-a_{11}a_{23}a_{32} + a_{12}a_{23} a_{31}- a_{12}a_{21}a_{33} \\[0.3em]
&\qquad + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31}) (du \wedge dv \wedge dw)\\[0.3em]
&= \det(\bf{A})\, (du \wedge dv \wedge dw) = J (du \wedge dv \wedge dw) 
\end{aligned}
$$

:::



