---
title: "탠서 해석"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 

{{< include ../../latexmacros.qmd >}}

</br>

## 텐서의 기초

### 공변벡터, 반변벡터, 아인슈타인 표기법 {#sec-Tensor_contravariant_covariant_einstein}

#### **공변벡터와 반변벡터** 

여기서는 유한차원 벡터공간 $V$ 와 그 쌍대공간 $V^\ast$ 에 대해 생각한다. $V$ 의 기저 $(e_1,\ldots,\,e_n)$ 의 각각의 $e_j$ 에 대해 $\theta^i\in V^\ast$ 가 존재하여 $\theta^i(e_j)=\delta^i_j$ 이며, $(\theta^1,\ldots,\,\theta^n)$ 이 $V^\ast$ 의 기저가 되며 이를 $(e_i)$ 기저에 대한 **쌍대 기저(dual basis)** 라고 한다. $V^\ast$ 의 원소를 **공변벡터(covariant vector 혹은 covector)** 라고 하고 $V$ 의 원소를 **반변벡터(contravariant vector)** 라고 한다. 선택된 $V$ 의 기저 $(e_i) = (e_1,\ldots,\,e_n)$ 에 대해 $(\theta^i)=(\theta^1,\ldots,\,\theta^n)$ 는 $V^*$ 의 기저이다.

</br>

#### **기저에 대한 표현과 아인슈타인 표기법**

$x\in V$ 에 대해 $x=\sum_i x^ie_i$, $\omega \in V^\ast$ 에 대해 $\omega = \sum_j\omega_j \theta^j$ 라고 하자. 이같이 반변벡터의 경우 기저는 아래첨자로, 성분은 위첨자로 표기하는 것이 표준이다. 공변벡터의 경우 기저는 위첨자로 성분은 아래첨자로 표기하는 것이 표준이다. 이 때 다음이 성립한다.
$$
x^i = \theta^i(x),\qquad \omega_i = \omega(e_i).
$$ {#eq-Tensor_componant_of_contravariant_and_covariant_vector}


$\omega\in V^\ast,\, x\in V$ 에 대해 $\omega (x)$ 는 다음과 같다$^1$.[$^1$ 이 때 $\omega (x)$ 를 *natural pairing* 이라고 한다.]{.aside} 

$$
\omega (x) =\sum_{i, j} \omega_j \theta^j(x^i e_i) = \sum_{i, j} \omega_j x^i \theta^j(e_i) = \underbrace{\sum_i \omega_ix^i \equiv \omega_i x^i}_{\text{Einstein notation}}
$$ {#eq-Tensor_natural_pariaing}


@eq-Tensor_natural_pariaing 의 오른쪽 두 항에서 아래첨자와 위첨자에 같은 인덱스 기호가 붙을 경우 인덱스합을 생략하기도 한다. 즉 $\sum_i \omega_iv^i$ 를 $\omega_iv^i$ 와 같이 표기하는데 이것을 **아인슈타인 표기법 (Einsteine notation)** 이라고 한다. 

</br>

### 기저의 변환 {#sec-Tensor_rule_of_transformation}

기저변환 $R$ 에 의해 $V$ 에서 기저를 $(e_1,\ldots,\,e_n)$ 에서 $(e'_1,\ldots,\,e'_n)$ 으로 아래와 같이 변경한다고 하자. $e_i$ 는 $(e'_j)$ 의 선형결합이며 이를 다음과 같이 표기한다.

$$
e_i = {R_i}^j e'_j, \qquad \text{i. e.}\qquad e'_j = {\left(R^{-1}\right)_j}^ke_k.
$$ {#eq-Tensor_basis_transform}

이 때 

$$
{R_i}^j {(R^{-1})_j}^k = {\delta_i}^k
$$

이어야 한다. 

$$
\begin{aligned}
x&=x^ie_i = x'^je'_j = x'^j{\left(R^{-1}\right)_j}^i e_i, \\[0.3em]
&=x'^je'_j = x^ie_i = x^i{R_i}^j e'_j
\end{aligned}
$$

이므로

$$
x^i = x'^j {\left(R^{-1}\right)_j}^i ,\qquad x'^j = x^i {R_i}^j 
$$ {#eq-Tensor_transform_of_contavariant_vector_component}

이어야 한다. 즉 $v\in V$ 의 성분은 기저의 변환에 대해 반대로(contra-) 변하므로(정확히는 역행렬에 따라 변하므로) 반변벡터라는 이름이 붙었다. 또한 이로부터

$$
{R_i}^j = \dfrac{\partial (x')^j}{\partial x^i},\qquad {\left(R^{-1}\right)_i}^j= \dfrac{\partial x^j}{\partial (x')^i}
$$ {#eq-Tensor_elements_of_basis_transform }

임을 안다. 이에 반해 

$$
\delta^i_j = \theta'^i(e'_j) = {\left(R^{-1}\right)_j}^k \theta'^i(e_k) 
$$

이다. 양변에 $(R_l)^j$ 를 곱하고 $j$ 에 대해 더하면

$$
{R_l}^i = (R_l)^j {(R^{-1})_j}^k \theta'^i (e_k) = \delta_l^k \theta'^i(e_k) = \theta'^i(e_l)
$$

이다. $\theta'^i$ 는 $(\theta^j)$ 의 선형결합으로 표현되며 $\theta'^i={X^i}_j \theta^j$ 라고 하면 

$$
{X^i}_l = {X^i}_j \theta^j(e_l) = \theta'^i(e_l) = {R_l}^i
$$

이므로 다음을 얻는다.
$$
\theta^i = {\left(R^{-1}\right)_j}^i \theta'^j,\qquad \theta'^j = {R_i}^j \theta^i.
$$ {#eq-Tensor_transform_of_dual_basis}

또한
$$
\omega'_j = \omega(e'_j)= {\left(R^{-1}\right)_j}^i \omega(e_i)= {\left(R^{-1}\right)_j}^i  \omega_i
$$ 

로 부터 다음을 얻는다.

$$
\omega_i = {R_i}^j \omega'_j, \qquad \omega'_j = {\left(R^{-1}\right)_j}^i  \omega_i.
$${#eq-Tensor_transform_of_covariant_vector_component}

즉 $\omega \in V^\ast$ 의 성분은 기저 변환과 같은 행렬을 통해 변하므로 공변벡터 라는 이름이 붙었다. 


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_invairanice_of_scalar}

$x\in V,\, \omega\in V^\ast$ 에서 $x^i\omega_i$ 는 좌표변환에 대해 불변임을 보여라.

:::

</div>

::: {.solution}
$x'^i\omega'_i = {R_j}^i x^j {(R^{-1})_i}^k\omega_k = (RR^{-1})_j^k x^j \omega_k = \delta_j^k x_j \omega_k = x^j\omega_j$
:::


</br>

### 텐서 {#sec-Tensor_tensor}

#### **텐서**

::: {.callout-note icon="false"}

#### **텐서**

::: {#def-Tensor_definitino_of_tensor}


$\F$-벡터공간 $V$ 에 대해 $V_1,\,V_2,\ldots,\,V_k$ 이 $V$ 이거나 $V$ 의 쌍대공간 $V^\ast$ 라고 하자. 이 때 $V_1 \times \cdots \times V_k \to \F$ 함수이며 각각의 벡터공간에 대해 다중선형인 함수를 **텐서 (tensor)** 라고 하며 이 때 $k$ 를 텐서의 **차수(rank)** 라고 한다. 차수가 $k$ 인 텐서를 $k$-텐서 라고 한다. 즉 각각의 $i\in \{1,\ldots,\,k\}$ 와 $v^{(i)},\,u^{(i)} \in V_i$, $c\in \F$ 에 대해 

$$
T(\ldots,\,v^{(i)} + cu^{(i)},\ldots) = T(\ldots,v^{(i)},\ldots) + c T(\ldots,u^{(i)},\ldots)
$$

이어야 한다. 
:::

:::




#### **기저에 대한 텐서의 첨자 표기**

우선 2 텐서에 대해 다룬다. $T$ 가 $V\times V$ 에서 정의된 2-텐서라고 하자. 그리고 $V$ 의 기저 $(e_i)$ 를 생각하자. 

$$
T_{ij} := T(e_i,\,e_j)
$$

라고 하자. 기저 $(e_i)$ 에 대해 $u=\sum u^i e_i,\, v = \sum v^i e_i$ 라고 하면

$$
T(u,\,v) = \sum_{i, j} u^iv^jT(e_i,\,e_j) \equiv T_{ij} u^iv^j
$$

이다. 즉 기저에 대한 텐서 값과 벡터의 성분을 알면 텐서값을 계산 할 수 있다. 반대로 $S$ 가 $V^\ast \times V^\ast$ 에서 정의된 2 텐서일 때 $V^\ast$ 의 기저 $(\theta^i)$ 에 대해

$$
S^{ij} := S(\theta^i,\,\theta^j)
$$

라고 정의하고 $\omega,\, \eta \in V^\ast$ 를 $\omega = \sum_i \omega_i \theta^i,\, \eta = \sum_i \eta_i \theta^i$ 라고 하면 
$$
S(\omega,\, \eta) = \sum \omega_i \eta_j S(\theta^i,\, \theta^j) \equiv  S^{ij}\omega_i \eta_j
$$

이다. $V \times V^\ast$ 에서 정의된 텐서 $A$ 를 생각하자. 

$$
{A_i}^j = A(e_i,\,\theta^j)
$$ 

로 정의하면
$$
A(v,\,\omega) = \sum_{i,j} v^i\omega_j A(e_i,\,\theta^j) \equiv {A_i}^j v^i\omega_j
$$

이다. 또한 이것을 확장하여 $V$ 와 $V^\ast$ 의 곱에서 정의된 임의의 $k$ 텐서에 대해서도 텐서의 위첨자-아래첨자 표기법을 사용 할 수 있다. 즉

$$
{{T^{i_1 i_2}}_{i_3 i_4}}{}^{i_5} 
$$

는 $V^\ast \times V^\ast \times V \times V \times V^\ast\to \F$ 텐서이다. 

#### **텐서와 기저의 변환**

기저 $(e_i)$ 에서 $(e'_j)$ 로의 변환 $R$ 이 $e_i = {R_i}^j e'_j$ 일 때 2차 텐서의 변환은 다음과 같다.

$$
\begin{aligned}
T'_{ij} &:= T(e'_i,\,e'_j) = T\left({\left(R^{-1}\right)_i}^k e_k,\, {\left(R^{-1}\right)_j}^l  e_l \right) = {\left(R^{-1}\right)_i}^k {\left(R^{-1}\right)_j}^l T_{kl} , \\[0.3em]
S'^{ij} &:= S(\theta'^i,\, \theta'^j) = S\left({R_k}^i\theta_i, {R_l}^j\theta^l\right) = {R_k}^i{R_l}^j  S^{kl}, \\[0.3em]
{{A'}_i}^j &= A(e'_i,\,\theta'^j) ={\left(R^{-1}\right)_i}^k {R_l}^j {A_k}^l.
\end{aligned}
$$ {#eq-Tensor-transform_of_rank_2_tensor}

이 식을 보면 알 수 있듯이 이것은 2차 이상의 텐서에 대해서도 그대로 적용된다. 텐서의 공변성분은 공변벡터의 변환을 따르고 반변성분은 반변벡터의 변환을 따른다.

</br>

::: {.callout-note icon="false"}

#### **$(p,q)$ 텐서 **

::: {#def-Tensor_pq_tensor}

벡터공간 $V$ 에 대해

$$
\underbrace{V^\ast \times \cdots \times V^\ast}_{p-\text{times}} \times \underbrace{V \times \cdots \times V}_{q-\text{times}} \to \F
$$

인 텐서를 **$(p,q)$ 텐서** 라고 한다.

:::

:::

$(p,\,q)$ 텐서의 변환규칙은 아래와 같다.

$$
{T^{i_1,\ldots,\,i_p}}_{j_1,\ldots,\,j_q} = {R_{l_1}}^{k_1}\cdots {R_{l_p}}^{i_p} {(R^{-1})_{j_1}}^{l_1}\cdots {(R^{-1})_{j_q}}^{l_q}{T'^{k_1,\ldots,\,k_p}}_{l_1,\ldots,\,l_q}
$$ {#eq-Tensor-transform_of_pq_tensor}


</br>

::: {.callout-note icon="false"}

#### **대칭 텐서와 교대텐서**

::: {#def-Tensor_symmetric_and_antisymmetric_tensor}

$k$ 텐서 $T\in\mathfrak{S}^k(V)$ 가 임의의 두 $v_i,\,v_j$ 에 대해

$$
T(\ldots,\,v_j,\ldots,\,v_i,\ldots) = T(\ldots,\,v_i,\ldots,\,v_j,\ldots)
$$ {#eq-Tensor_definition_of_symmetric_tensor}


이면 $T$ 를 **대칭 텐서(symmetric tensor)** 라고 한다. 역시 $k$ 텐서 $A(V,\ldots,V)또한 임의의 두 $v_i,\,v_j$ 에 대해

$$
A(\ldots,\,v_j,\ldots,\,v_i,\ldots) = - A(\ldots,\,v_i,\ldots,\,v_j,\ldots) 
$${#eq-Tensor_definition_of_alternating_tensor}

인 텐서 $A$ 를 **교대 텐서 (alternatig tensor)** 혹은 **반대칭 텐서 (antisymmetric tensor)** 라고 한다.


:::

:::


2차 텐서의 경우 대칭 텐서는 다음을 만족한다.

$$
T^{ij} = T^{ji},\quad T_{ij} = T_{ji}.
$$

2차 교대 텐서의 경우는 다음을 만족한다.

$$
A^{ij} = - A^{ji},\qquad A_{ij} = - A_{ji}.
$$


또한 텐서는 다음과 같이 대칭 텐서와 반대칭 텐서의 합으로 나타 낼 수 있다.

$$
A^{kl} = \dfrac{A^{kl} + A^{lk}}{2} + \dfrac{A^{kl}- A^{kl}}{2}.
$$

2차 혼합 대칭 텐서의 경우 ${A^i}_j = {A^j}_i$ 일 때 $A^i_j$ 와 같이 쓰기도 한다. 


</br>

#### **등방 텐서**

좌표 변환에 대해서도 그 성분이 변하지 않는 **등방 텐서(isotropic tensor)** 라고 한다. 정의에 의해 $\delta^i_j = \theta^i(e_j)$ 이며, Chain rule 을 이용하면

$$
\delta^i_j = \theta^i(e_j) = \dfrac{\partial x^i}{\partial x'^k}\theta'^k\left(\dfrac{\partial x'^l}{\partial x^i} e'_l\right) = \dfrac{\partial x^i}{\partial x'^k}\dfrac{\partial x'^l}{\partial x^i}\theta'^k\left( e'_l\right) = \delta'^k_l
$$

이다. 즉 좌표 변환에 대해 텐서 값이 변하지 않는 크로네커 델타는 등방 텐서이다.


</br>


#### **계량 텐서**

$\F$-벡터공간 $V$ 에 대해, 정확히는 다양체 $M$ 의 탄젠트 공간 $V=T_pM$ 에서 정의되는 **계량 텐서 (metric tensor)** $g \in \mathcal{T}^2(V)$ 는 다음의 성질을 가진다.

&emsp;($1$) **대칭성** : $g(u,\,v) = g (v,\,u)$, 

&emsp;($2$) **비축퇴성** : $\forall u\in V,\, g(v,\,u)=0 \iff v=0$

계량텐서는 내적벡터공간의 내적과 같이 벡터공간에 부여되는 구조이다. 이 때 계량텐서가 $0$ 이 아닌 모든 $u,\,v\in V$ 에 대해 $g(u,\,v) > 0$ 이면 이 텐서를 **리만 계량(Riemann metric)** 이라고 하고 아래와 같이 주어졌을 때 **로런츠 계량(Lorentz metric)** 이라고 한다. 텐서의 인덱스 규칙에 따라 $g_{ij} = g(e_i,\,e_j)$ 라고 하자. 로런츠 계량은 아래와 같이 주어진다.

$$
g_{ij} = \left[\,\begin{array}{rrrr} 1 & 0 & 0 & 0 \\ 0 & -1 & 0 & 0 \\ 0 & 0 & -1 & 0 \\ 0 & 0 & 0 &-1\end{array}\,\right].
$$ {#eq-Tensor_lorentz_metric}

계량의 정의에 의해 아래의 대칭성이 성립한다는 것을 알 수 있다.

$$
\boxed{ g_{ij} = g_{ji}}.
$$ {#eq-Tensor_symmetric_property_of_metric_tensor}


이 때 내림 사상 $\flat : V\to V^\ast$ 을 다음과 같이 정의한다.

$$
\flat(v) (u) := g(v,\,u).
$$ {#eq-Tensor_flat_map}

$g$ 가 쌍선형 사상이므로 $\flat$ 은 선형사상이며 $g$ 의 비축퇴성으로 인해 $\flat$ 은 가역사상이다.

이 때, $v=v^ie_i,\, u=u^je_j$ 에 대해 
$$
\flat (v^ie_i)(u^ie_i) = g(v^ie_i,\, u^je_j) = \sum_{i,j}v^iu^jg(e_i,\,e_j) = g_{ij}v^iu^j
$$

이므로 $v_j = g_{ij}v^i$ 로 놓으면 $g(v,\,u) = v_ju^j$ 이다. 

$\flat$ 이 가역사상이므로 $\flat$ 의 역사상이 존재한다. 이를 $\sharp$ 라고 하자. 그렇다면 $v^j = (g_{ij})^{-1}v_i$ 이며 $(g_{ij})^{-1}$ 은 아래 인덱스를 위 인덱스로 바꾸저 주는 역할을 하므로 $g^{ji}$ 와 같이 쓸 수 있다. 즉

$$
g^{ij} = (g_{ji})^{-1}
$$

이다. 이제 $v_i = {g_i}^j v_j = {g_i}^j g_{jk}v^k$ 이며 $v_i = g_{ik}v^k$ 이므로 ${g_i}^j = g_{ik}(g_{jk})^{-1}= g_{ik}g^{kj}$ 임을 알 수 있다. 같은 방식으로 ${g^i}_j = g^{ik}g_{kj}$ 임을 안다. 이를 정리하면 정해진 계랑 $g_{ij}$ 에 대해

$$
\boxed{
  g^{ij} = (g_{ji})^{-1},\qquad {g_i}^j = g_{ik}g^{kj},\qquad {g^i}_j = g^{ik}g_{kj}
}
$$ {#eq-Tensor_metric_tensor_and_its_variations}

이다.

</br>



### 텐서 연산

#### **축약**

다음을 보자.

$$
(B')^{i}_i = \dfrac{\partial (x')^i}{\partial x^k}\dfrac{\partial x^l}{\partial (x')^i} B^k_{l}= \dfrac{\partial x^l}{\partial x^k}B_l^k = \delta^l_k B_{l}^k =  B_{k}^k
$$

혼합 텐서의 경우 chain rule 로 인해 식을 위와 같이 간단하게 줄일 수 있다. 이것을 **축약(contraction)** 이라고 한다. 

</br>

#### **텐서곱**

텐서의 랭크가 어떻든, 공변성(즉 위첨자, 아래첨자)이 어떻든 간에 두 텐서의 성분을 곱하여 새로운 텐서를 만들 수 있다. 이 때 원래 있던 두 텐서의 위첨자, 아래첨자는 그대로 유지된다. 예를 들어 

$$
A^i_k B^j_{lm} = C^{ij}_{klm},\qquad A^j B^{i}_{lk} = F^{ij}_{lk}
$$

와 같은 방식이다. 위의 식에서 왼쪽 식에 대한 좌표변환을 보면

$$
\begin{aligned}
(F')^{ij}_{lk} &= \dfrac{\partial (x')^i}{\partial x^p}\dfrac{\partial (x')^j}{\partial x^q}\dfrac{\partial x^s}{\partial (x')^l}\dfrac{\partial x^s}{\partial (x')^k}A^q B^{p}_{st} \\[0.3em]
&= \left[\dfrac{\partial (x')^j}{\partial x^q} A^p \right]\left[\dfrac{\partial (x')^i}{\partial x^p}\dfrac{\partial x^s}{\partial (x')^l}\dfrac{\partial x^s}{\partial (x')^k} B^{p}_{st}\right]\\[0.3em]
&= (A')^j (B')^{i}_{lk}
\end{aligned}
$$

이다. 


</br>

#### **역변환**

$$
(A')^j = \dfrac{\partial (x')^j}{\partial x_i}A^i
$$

이다. 또한 그 역변환은 

$$
A^i = \dfrac{\partial x^i}{\partial (x')^j} (A')^j
$$

이다. 여기서 당연히

$$
\left[\dfrac{\partial (x')^j}{\partial x_i}\right]^{-1} \ne \dfrac{\partial x^i}{\partial (x')^j}
$$

이 아니며, 등호가 성립하는 것은 데카르트 좌표계에서 뿐이다. 

</br>

#### **몫 규칙**

정해진 벡터 $A_j$, $B_i$ 에 대해

$$
K^{j}_i A_j = B_i
$$ {#eq-Tensor_quotient_rule_1}

를 만족하는 $K_i^j$ 를 구한다고 하자. $K^j_i$ 가 rank 2 혼합 텐서로 표기되어 있지만 아직까지는 위의 식이 좌표와 무관하게 성립한다는 것 이외의 성질은 모른다고 하자. 우리는 여기서 $K_i^j$ 가 혼합 텐서가 되는 것을 보일 것이다. 이 방정식이 좌표변환에 대해 불변이므로 

$$
(K')^{j}_i (A')_j = (B')_i
$$ {#eq-Tensor_quotient_rule_2}

역시 만족해야 한다. $B$ 가 공변 벡터이므로

$$
(B')_i = \dfrac{\partial x^m}{\partial x^i} B_m =\dfrac{\partial x^m}{\partial x^i} K^j_m A_j = \dfrac{\partial x^m}{\partial x^i}K^j_m \dfrac{\partial (x')^n}{\partial x^j}(A')_n
$${#eq-Tensor_quotient_rule_3}

이다. 이 식을 @eq-Tensor_quotient_rule_2 와 같이 쓰기 위해 마지막 식의 인덱스 가운데 $n$ 과 $j$ 를 교환하자.

$$
(B')_i = \dfrac{\partial x^m}{\partial x^i}K^n_m \dfrac{\partial (x')^j}{\partial x^n}(A')_j.
$${#eq-Tensor_quotient_rule_4}

위 식과 @eq-Tensor_quotient_rule_2 를 생각하면

$$
\left[(K')^j_i - \dfrac{\partial x^m}{\partial x^i}\dfrac{\partial (x')^j}{\partial x^n} K^n_m\right](A')_j = 0
$${#eq-Tensor_quotient_rule_5}

임의의 $A'$ 에 대해 성립해야 하므로

$$
(K')^j_i = \dfrac{\partial x^m}{\partial x^i}\dfrac{\partial (x')^j}{\partial x^n} K^n_m
$$

이다. 즉 우리는 $K$ 에 대해 아무 것도 모른 채로 @eq-Tensor_quotient_rule_2 가 좌표변환에 무관하게 성립한다는 가정만으로 $K$ 가 rank 2 혼합 텐서가 될 수 밖에 없다는 것을 보였다. 이것은 일반적인 텐서 방정식에 대해 모두 성립하며 예를 들어

$$
KA_{ij}=B_{kl}
$$

를 만족하는 $K$ 는 $K^{ij}_{kl}$ 의 변환을 따르는 4차 텐서 일 수 밖에 없다. 

</br>

### 스피너

양자역학 이전까지 스칼라, 벡터 와 랭크 $n$ 텐서로 물리량을 모두 기술 할 수 있다고 생각했다. 그러나 특히 반정수 스핀 입자의 발견으로 이것이 불가능하다는 것을 알게 되었다. 스핀 $0$ 입자는 스칼라로, 스핀 $1$ 입자는 벡터로 기술 할 수 있지만 전자, 양성자, 중성자와 같은 스핀 $1/2$ 입자는 좌표 변환에 대해 지금까지 알아온 방법으로는 기술 할 수 없었다. 스피너에 대해서는 이후 군론에서 다루기로 하자.

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_1}
#### Arfken 4.1.1

어떤 텐서가 어떤 좌표계에서 모든 성분이 $0$ 이라면 이 텐서는 모든 좌표계에서 $0$ 임을 보여라.

:::

</div>

::: {.solution}

$\displaystyle (A')^{ijk..}_{lmn...} = \dfrac{\partial (x')^i}{\partial x^{i'}} \cdots \dfrac{\partial x^{l'}}{\partial (x')^l}\cdots A^{i'j'k'}_{l'm'n'} = 0$


:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_2}
#### Arfken 4.1.2

두 텐서 $A_{ij}$, $B_{kl}$ 이 어떤 좌표계에서(위첨자 $0$ 으로 표시한다)

$$
A^0_{ij} = B^0_{ij}
$$

라면 이 두 텐서는 동일함을 보여라.

:::

</div>

::: {.solution}

$A_{ij}= \dfrac{\partial x^k}{\partial (x^0)^i}\dfrac{\partial x^l}{\partial (x^0)^j}A^0_{kl} = \dfrac{\partial x^k}{\partial (x^0)^i}\dfrac{\partial x^l}{\partial (x^0)^j}B^0_{kl} = B_{ij}$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_3}
#### Arfken 4.1.3
(문제가 이상하다..)

4 차원 벡터 가 두 관성계에서 마지막 세 성분이 $0$ 이 된다. 이중 두번째 관성계는 첫번째 관성계에서 $x_0$ 축을 중심으로 한 회전이 아니라고 하자. 즉 최소한 하나의 $\partial (x')^i/\partial x^0,\, (i=1,\,2,\,3)$ 는 $0$ 이 아니다. 이 때 $0$ 번째 성분은 모든 좌표계에서 $0$ 임을 보여라.

:::

</div>

::: {.solution}

4차원 벡터 $A$ 가 첫번째 좌표계에서 $(A^0,\, A^1,\,A^2,\,A^3)$ 이며 두번째 좌표계에서 $(A'^0,\,A'^1,\,A'^2,\,A'^3)$ 이고 $A^1=A^2=A^3=A'^1=A'^2=A'^3=0$ 이다. $(A')^0$ 에 대해

$$
(A')^0 = \dfrac{\partial (x')^0}{\partial x^\alpha}A^{\alpha} =  \dfrac{\partial (x')^0}{\partial x^0}A^{0}
$$

이다. $\partial (x')^i/\partial x^0 \ne 0$ 인 $i$ 에 대해  
$$
0 = (A')^i = \dfrac{\partial x'^i}{\partial x^\alpha}A^\alpha = \dfrac{\partial x'^i}{\partial x^0}A^0
$$

이므로 $A^0=0$ 이며 따라서 $A'^0 = 0$ 이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_4}
#### Arfken 4.1.4

좌표축에 대한 $90^\circ$, $180^\circ$ 회전을 생각하여 3차원 공간에서의 rank 2 텐서 가운데 등방 텐서인 것은 $\delta^i_j$ 의 스칼라 곱 밖에 없음을 보여라.
:::

</div>

::: {.solution}
.. to be done..


:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_5}
#### Arfken 4.1.5

일반상대성 이론에서 사용되는 4 차원 랭크 4 텐서 리만-크리스토펠 곡률 텐서 $R_{iklm}$ 은 다음과 같은 대칭 관계를 만족한다.

$$
R_{iklm} = - R_{ikml} =  - R_{kilm}
$$ {#eq-Tensor_Arfket_4_1_5_1}

$0$ 부터 $3$ 까지의 인덱스를 사용하여 전체 256 성분중에 독립적인 성분이 36 개임을 보이고 또한

$$
R_{iklm} = R_{lmik}
$${#eq-Tensor_Arfket_4_1_5_2}

를 사용하면 독립적인 생분의 갯수를 21 개 로 줄일 수 있음을 보여라. 마지막으로 성분이

$$
R_{iklm} + R_{ilmk} + R_{imkl} = 0
$${#eq-Tensor_Arfket_4_1_5_3}

을 만족한다면 독립적인 성분의 갯수는 20개로 줄게 됨을 보여라. 단 마지막 식은 사용된 4개의 인덱스가 모두 다를 경우에만 성립한다.

:::

</div>

::: {.solution}

4 차원 rank 4 텐서이므로 $4^4=256$ 개의 성분을 가진다. 

($1$) @eq-Tensor_Arfket_4_1_5_1 : 첫번째 인덱스는 두번째 인덱스와 달라야 하며, 세번째 인덱스는 네번째 인덱스와 달라야 한다. 또한 반대칭 성질이 있으므로 첫 두개의 인덱스 에서 6가지 경우, 마지막 두 인덱스의 6가지 경우, 총 36가지의 독립적인 성분이 존재한다. $R_{iklm}$ 에서 $i<k$, $l<m$ 인 경우. 

($2$) @eq-Tensor_Arfket_4_1_5_2 : 36 가지중 첫 두 인덱스와 마지막 두 인덱스가 같은 경우는 6가지 이며 이것을 제외한 30개에 대해 대칭성이 존재하므로 30/2+6=21 개의 독립적인 성분이 존재한다.

($3$) @eq-Tensor_Arfket_4_1_5_3 : 4개의 인덱스가 모두 다른 경우에 하나의 제한조건이 포함되므로 하나의 독립 변수를 줄인다. 따라서 총 20개의 독립 성분이존재한다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_6}
#### Arfken 4.1.6

3차원 반대칭 랭크 4 텐서 $T_{iklm}$ 는 몇개의 독립적인 성분을 가지는가?

:::

</div>

::: {.solution}

$i,\,k,\,l,\,m$ 가운데 최소한 2개는 같으므로 성분이 모두 $0$ 이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_7}
#### Arfken 4.1.7

$T_{...i}$ 는 랭크 $n$ 텐서이다. $\partial T_{...i}/\partial x^j$ 는 랭크 $n+1$ 텐서 임을 보여라.
:::

</div>

::: {.solution}

$T'_{...k} = [n \text{ 개의 좌표 편미분의 곱}] T'_{...i}$ 이므로

$$
\dfrac{\partial T'_{...i}}{\partial x'^j} = \dfrac{\partial x_k}{\partial x'^j}[n \text{ 개의 좌표 편미분의 곱}]\dfrac{\partial T_{...i} }{\partial x_k}
$$

이다. 따라서 랭크 $n+1$ 텐서이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_8}
#### Arfken 4.1.8

$T_{ijk...}$ 는 랭크 $n$ 텐서이다. $\sum_j \partial T_{ijk...}/\partial x^j$ 는 랭크 $n-1$ 텐서 임을 보여라.

:::

</div>

::: {.solution}

contraction 에 의해 랭크 $n-1$ 텐서가 된다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_1_9}
#### Arfken 4.1.9

이중 합 $K_{ij}A^iB^j$ 가 어떤 벡터 $A^i,\,B^j$ 에 대해서도 불변이라면 $K_{ij}$ 가 랭크 2 텐서 임을 보여라.

:::

</div>

::: {.solution}

몫 규칙에 의해 자명하지만 일단 연습삼아...
$$
K_{ij}A^iB^j = K'_{lm}A'^lB'^m = K'_{lm}\left[\dfrac{\partial x'^l}{\partial x^i}A^i\right] \left[\dfrac{\partial x'^m}{\partial x^j}B^j\right]
$$

이므로 

$$
\left[K_{ij} -\dfrac{\partial x'^l}{\partial x^i} \dfrac{\partial x'^m}{\partial x^j}K'_{lm} \right] A^iB^j=0
$$

이다. 임의의 $A^iB^j$ 에 대해 성립해야 하므로 $[\cdots ]=0$ 이어야 한다. 따라서 $K_{ij}$ 는 랭크 2 텐서이다.

:::

</br>

## 유사텐서와 쌍대텐서

### 유사벡터 와 유사텐서 {#sec-Tensor_pseudo_vector_and_pseudo_tensor}

지금까지 우리는 좌표의 회전에 대해서만 양의 변화를 보았다. 이제 반사(reflection) 이나 반전(inversion) 과 같은 변화를 살펴보자(이를 improper rotation 이라고 한다)

벡터 $A$ 는 회전, 혹은 그 행렬식이 $1$ 인 변환 $R$ 에 대해 $A'=RA$ 와 같이 변환된다. 반전과 같이 행렬식이 $-1$ 인 변환 $R^-$ 에 대해서는 상황이 다르다. 반전(Inversion) 을 생각하자. 위치나 속도와 같은 벡터들은 반전에 대해 $A'=R^- A$ 와 같이 변환된다. 그러나 각운동량, 토크, 각속도와 같은 벡터 물리량은 $A'=\det (R^-) R^- A$ 와 같이 변환된다. 이렇게 좌표와 다른 방식의 대칭성을 가지고 변화하는 벡터를 **유사 벡터 (pseudo vectors)**(혹은 axial vectors) 라고 한다. 

이런 유사벡터 의 개념은 임의의 rank 를 가진 텐서로 확장 될 수 있다. 어떤 직교 변환 $R$ 에 대해 일반적인 텐서 변환식에 $\det(R)$ 을 곱한 것으로 변화하는 텐서를 pseudotensor 라고 한다.

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_levi_civita}

#### 레비-시비타(Levi-Civita) 기호

인덱스가 3개인 레비-시비타 기호 $\varepsilon_{ijk}$ 의 정의는 다음과 같다.

$$
\begin{aligned}
\varepsilon_{123}=\varepsilon_{231}=\varepsilon_{312} &= +1, \\
\varepsilon_{132} = \varepsilon_{213} = \varepsilon_{321} &= -1,\\
\text{모든 다른 }\varepsilon_{ijk}&= 0.
\end{aligned}
$$ {#eq-Tensor_levi-civita}

</br>

$3\times 3$ 행렬 $A$ 에 대해
$$
\sum_{i,j,k}\varepsilon_{ijk} A_{1i}A_{2j}A_{3k} = \det (A)
$$

임을 알 수 있다. 


랭크 3 pseudotensor $\eta_{ijk}$ 가 어떤 데카르트 좌표계에서 $\varepsilon_{ijk}$ 와 같다고 하자. 그리고 $S$ 를 $\R^3$ 에서의 어떤 직교변환 행렬이라고 하자. Pseudotensor 의 정의에 의해

$$
\eta'_{ijk} = \det(S) \sum_{p,q,r} a_{ip}a_{jq}a_{kr} \varepsilon_{pqr}
$$

이다. 행렬식을 생각하면

$$
\eta'_{ijk} = \left(\det{S}\right)^2 \varepsilon_{ijk}
$$

임을 알 수 있다. 직교변환 행렬 $S$ 에 대해 $\det (S)= \pm 1$ 이므로 $\eta'_{ijk}= \varepsilon_{ijk}$ 이다. 

이로부터 우리는 $\varepsilon_{ijk}$ 가 rank 3 pseudotensor 이며 isotropic 함을 알 수 있다. 즉 회전 변환에 대해 불변이며, improper rotation 에 대해 서는 $-1$ 을 곱한 것과 같다.

:::
</div>

</br>

### 쌍대 텐서 {#sec-Tensor_dual_tensor}

3차원 공간에서의 임의의 2차 반대칭 텐서 $C$ 는 다음과 같이 표현 할 수 있다.

$$
C=\begin{bmatrix} 0 & C^{12}& -C^{31} \\ - C^{12} & 0 & C^{23} \\ C^{31} & -C^{23} & 0\end{bmatrix}
$$

$C$ 에 대해 아래와 같은 벡터 $\overline{C}$ 를 $C$ 에 대한 **쌍대 텐서(dual tensor)** 라고 한다.

$$
\overline{C} := (C_1,\,C_2,\,C_3) = (C^{23},\, C^{31},\, C^{12}).
$$

즉

$$
\overline{C}_i = \dfrac{1}{2} \varepsilon_{ijk} C^{jk}
$$

이다. 

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_2_2}
#### Arfken 4.2.2

반대칭 랭크 2 텐서와 벡터와의 1-1 대응은 3차원 공간에서만 가능하다는 것을 보여라.

:::

</div>

::: {.solution}

$n$ 차원 공간에서의 반대칭 랭크 $2$ 텐서 $A$ 의 독립적인 성분의 갯수는 $\dfrac{n^2-n}{2}$ 이며 $n$ 차원 공간의 벡터의 성분의 갯수는 $n$ 개이므로 1-1 대응이 성립하려면

$$
\dfrac{n^2-n}{2}=n
$$

이어야 한다. 즉 $n=3$ 뿐이다. ($n=0$ 은 무의미하다.)

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_2_3}
#### Arfken 4.2.3

$\nabla \bf{\cdot}\nabla \times \bf{A}$ 와 $\nabla \times \nabla \phi$ 를 $\R^3$ 에서의 텐서 표기법으로 쓰고 각각 $0$ 임을 보여라.

:::

</div>

::: {.solution}

$$
\begin{aligned}
\nabla \bf{\cdot}\nabla \times \bf{A} &= \varepsilon_{ijk}\dfrac{\partial }{\partial x^i}\dfrac{\partial A_k}{\partial x^j} = 0 \\[0.3em]
\left(\nabla \times \nabla \phi\right)_k &= \epsilon_{ijk}\dfrac{\partial^2 \phi}{\partial x^i\partial x^j}=0
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_2_4}
#### Arfken 4.2.4

아래의 랭크 4 텐서는 등방임을 보여라. 즉 좌표의 회전에 독립적인 값이다.

($a$) $A^{ik}_{jl} = \delta^i_j \delta^k_l$,

($b$) $B^{ij}_{kl} = \delta^{i}_k \delta^j_l + \delta^i_l \delta^j_k$,

($c$) $C^{ij}_{kl} = \delta^{i}_k \delta^j_l - \delta^i_l \delta^j_k$.
:::

</div>

::: {.solution}
($a$)

$$
\begin{aligned}
A'^{pq}_{rs} &= \dfrac{\partial x'^p}{\partial x_i}\dfrac{\partial x'^q}{\partial x^k}\dfrac{\partial x^j}{\partial x'^r}\dfrac{\partial x^l}{\partial x'^s}A^{ik}_{jl} = \dfrac{\partial x'^p}{\partial x_i}\dfrac{\partial x'^q}{\partial x^k}\dfrac{\partial x^j}{\partial x'^r}\dfrac{\partial x^l}{\partial x'^s}  \delta^i_j \delta^k_l \\[0.3em]
&= \dfrac{\partial x'^p}{\partial x_i}\dfrac{\partial x'^q}{\partial x^k}\dfrac{\partial x^i}{\partial x'^r}\dfrac{\partial x^k}{\partial x'^s} = \dfrac{\partial x'^p}{\partial x'^r}\dfrac{\partial x'^q}{\partial x'^s} = \delta^p_r \delta^q_s = A^{pq}_{rs}
\end{aligned}
$$

($b$)
$$
\begin{aligned}
B'^{pq}_{rs} &= \dfrac{\partial x'^p}{\partial x^i}\dfrac{\partial x'^q}{\partial x^j}\dfrac{\partial x^k}{\partial x'^r}\dfrac{\partial x^l}{\partial x'^s}B^{ij}_{kl} = \dfrac{\partial x'^p}{\partial x^i}\dfrac{\partial x'^q}{\partial x^j}\dfrac{\partial x^k}{\partial x'^r}\dfrac{\partial x^l}{\partial x'^s}\left( \delta^{i}_k \delta^j_l + \delta^i_l \delta^j_k\right) \\[0.3em]
&=  \dfrac{\partial x'^p}{\partial x^i}\dfrac{\partial x'^q}{\partial x^j}\dfrac{\partial x^i}{\partial x'^r}\dfrac{\partial x^j}{\partial x'^s} +  \dfrac{\partial x'^p}{\partial x^i}\dfrac{\partial x'^q}{\partial x^j}\dfrac{\partial x^j}{\partial x'^r}\dfrac{\partial x^i}{\partial x'^s} \\[0.3em]
&= \delta^p_q \delta^q_s + \delta^p_s \delta^q_r = B^{pq}_{rs}
\end{aligned}
$$

($c$) ($b$) 로부터 $C'^{pq}_{rs} = \delta^{p}_r \delta^q_s - \delta^p_s \delta^q_r=C^{pq}_{rs}$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_2_5}
#### Arfken 4.2.5

두개의 인덱스를 가진 레비-시비타 기호 $\varepsilon_{ij}$ 는 2차원에서 랭크 2 슈도텐서임을 보여라. 이것은 @exr-Arfken_4_1_4 에서 보인 $\delta^i_j$ 의 유일성에 위배되는가?

:::

</div>

::: {.solution}
@exm-Tensor_levi_civita 의 2차원 버젼이다. $\delta^{i}_j$ 는 3차원서 등방 텐서이며 $\epsilon_{ij}$ 는 2차원에서 등방 텐서이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_2_7}
#### Arfken 4.2.7

반대칭 2차 텐서 $B^{ij}$ 에 대해 $A_k = \dfrac{1}{2}\varepsilon_{ijk}B^{ij}$ 라고 하자. 다음이 성립함을 보여라.

$$
B^{mn} = \varepsilon^{mnk}A_k.
$$

:::

</div>

::: {.solution}

$\varepsilon^{mnk}\varepsilon_{ijk} =\delta^m_i \delta^n_j - \delta^m_j\delta^n_i$ 임을 이용한다. 
$$
\begin{aligned}
\varepsilon^{mnk}A_k = \dfrac{1}{2}\varepsilon^{mnk}\varepsilon_{ijk}B^{ij} = \dfrac{1}{2}(\delta^m_i \delta^n_j - \delta^m_j\delta^n_i)B^{ij} =\dfrac{1}{2} (B^{mn} -B^{nm}) = B^{mn}
\end{aligned}
$$

:::

</br>

## 일반화된 좌표계에서의 텐서

### 메트릭 텐서 {#sec-Tensor_metric_tensor}

이제 일반적인 거리 공간(metric space) 에서 생각하자. 일단은 3차원 공간에 한정한다. 일반화된 좌표를 $q^i$ 라고 표기하기로 하자. 공변 기저 벡터(covariant basis vector) $\bf{\varepsilon}_i$ 를 다음과 같이 정의한다.

$$
\bf{\varepsilon}_i := \dfrac{\partial x}{\partial q^i} \hat{\bf{e}}_x + \dfrac{\partial y}{\partial q^i}\hat{\bf{e}}_y + \dfrac{\partial z}{\partial q^i}\hat{\bf{e}}_z
$$ {#eq-Tensor_covariaint_basis_vector}

3차원 공간에서는 $\bf{\varepsilon}_1,\,\bf{\varepsilon}_2, \, \bf{\varepsilon}_3$ 로 기저를 구성 할 수 있다. 이 세 벡터는 서로 단위 벡터가 아닐 수도 있으며, 서로 직교하지 않을 수도 있다. 이제 임의의 벡터 $\bf{A}$ 는 공변 기저 벡터에 대해 다음과 같이 쓸 수 있다.

$$
\bf{A} := A^1 \bf{\varepsilon}_1 + A^2 \bf{\varepsilon}_2 + A^3 \bf{\varepsilon}_3.
$$ {#eq-Tensor_representation_of_vector_using_covariant_basis}

여기서 주의해야 할 것인 벡터 $\bf{A}$ 는 좌표 변환에 대해 고정되어 있으며 변하는 것은 기저와 좌표값 $A^1,\,A^2,\,A^3$ 라는 것, 그리고 기저와 좌표값은 서로 반대 방향으로 변환된다는 것이다. 또한 공변 기저 벡터는 위치에 따라 달라진다는 것이다. 이제 미소 변위 $(ds)^2$ 를 생각하면

$$
(ds)^2 = \sum_{i, j} (\bf{\varepsilon}_i dq^i) \bf{\cdot} (\bf{\varepsilon}_j dq^j)  = \left(\bf{\varepsilon}_i \bf{\cdot \varepsilon}_j \right) dq^i dq^j 
$$

와 같이 쓸 수 있다. **공변 메트릭 텐서(covariant metric tensor)** $g_{ij}$ 를 아래와 같이 정의한다.

$$
g_{ij}:= \left(\bf{\varepsilon}_i \bf{\cdot \varepsilon}_j \right) .
$$ {#eq-Tensor_covariant_metric_tensor}

그렇다면 

$$
(ds)^2 = g_{ij}dq^i dq^j
$${#eq-Tensor_dispacement_and_metric_tensor}

이다. $(ds)^2$ 은 회전 및 반사에 대해 불변이며 몫 규칙에 다라 $g_{ij}$ 는 공변 랭크 2 텐서이다. 또한 @eq-Tensor_covariant_metric_tensor 로부터 $g_{ij}$ 가 대칭 텐서라는 것을 알 수 있다. 

공변 메트릭 텐서 $g_{ij}$ 에 대해 반변 메트릭 텐서 $g^{ij}$ 가

$$
g^{ik}g_{kj}= g_{jk}g^{ki} = \delta^i_j
$$ {#eq-Tensor_covariant_and_contravariant_metric_tensor}

가 되도록 정한다. 또한 메트릭 텐서는 공변벡터와 반변벡터간의 변환을 위해 사용 될 수 있다. 즉

$$
g_{ij}F^j = F_i, \qquad \text{and}\qquad g^{ij}F_j = F^i
$$ {#eq-Tensor_conversion_using_metric_tensor}

이제 @eq-Tensor_representation_of_vector_using_covariant_basis 과 @eq-Tensor_conversion_using_metric_tensor 로부터 다음을 알 수 있다.

$$
\bf{A} = A^i\bf{\varepsilon}_i = A^i \delta^{k}_i \bf{\varepsilon}_k = \left(A^i g_{ij}\right)\left(g^{jk} \bf{\varepsilon}_k\right) = A_j \bf{\varepsilon}^j
$$ {#eq-Tensor_two_representation_of_a_vector}

즉 벡터는 반변기저에 대해 공변 성분으로, 혹은 공변 기저에 대해 반변 성분으로 표현 할 수 있다.

</br>

### 공변기저와 반변기저 {#sec-Tensor_covariant_and_contravariant_basis}

공변 기저 벡터 $\bf{\varepsilon}_i$ (@eq-Tensor_covariaint_basis_vector) 에 대해 반변 기저 벡터는 다음과 같이 정의된다.

$$
\bf{\varepsilon}^i :=\dfrac{\partial q^i}{\partial x}\hat{\bf{e}}_x + \dfrac{\partial q^i}{\partial y}\hat{\bf{e}}_y + \dfrac{\partial q^i}{\partial z}\hat{\bf{e}}_z.
$$ {#eq-Tensor_contravariant_basis_vector}

그렇다면

$$
\bf{\varepsilon}^i \bf{\cdot \varepsilon}_j = \dfrac{\partial q^i}{\partial x}\dfrac{\partial x}{\partial q^j} + \dfrac{\partial q^i}{\partial y}\dfrac{\partial y}{\partial q^j} + \dfrac{\partial q^i}{\partial z}\dfrac{\partial z}{\partial q^j} = \dfrac{\partial q^i}{\partial q^j} = \delta^i_j
$$ {#eq-Tensor_inner_product_of_two_basis_vector}

이다. 또한 다음이 성립함을 보일 수 있다.(@exr-Arfken_4_3_3)

$$
(\bf{\varepsilon}^i\bf{\cdot \varepsilon}^j)(\bf{\varepsilon}_j\bf{\cdot \varepsilon}_k) = \delta^i_k
$$ {#eq-Tensor_equality_of_product_of_two_innerproduct_of_basis}

@eq-Tensor_covariant_metric_tensor, @eq-Tensor_covariant_and_contravariant_metric_tensor 와 위 식으로부터 반변 메트릭 텐서를 알 수 있다. 

$$
g^{ij} = \bf{\varepsilon}^i\bf{\cdot \varepsilon}^j.
$${#eq-Tensor_contravariant_metric_tensor}

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Tensor_some_metric_tensor}

#### 구면좌표계에서의 메트릭 텐서
</br>

$(r,\,\theta,\, \varphi)$ 로 기술되는 원통좌표계를 생각하자. @eq-Tensor_covariaint_basis_vector 로부터

$$
\begin{aligned}
\bf{\varepsilon}_r &= \sin \theta \cos \varphi \hat{\bf{e}}_x + \sin \theta \sin \varphi \hat{\bf{e}}_y + \cos\theta \hat{\bf{e}}_z, \\[0.3em] 
\bf{\varepsilon}_\theta &= r \cos \theta \cos \varphi  \hat{\bf{e}}_x + r \cos \theta \sin \varphi  \hat{\bf{e}}_y - r \sin \theta  \hat{\bf{e}}_z, \\[0.3em]
\bf{\varepsilon}_\varphi &= - r\sin \theta \sin \varphi \hat{\bf{e}}_x + r \sin \theta \cos \varphi \hat{\bf{e}}_y.
\end{aligned}
$$

이며 @eq-Tensor_contravariant_basis_vector 로부터

$$
\begin{aligned}
\bf{\varepsilon}^r &= \sin \theta \cos \varphi \hat{\bf{e}}_x + \sin \theta \sin \varphi \hat{\bf{e}}_y + \cos\theta \hat{\bf{e}}_z, \\[0.3em] 
\bf{\varepsilon}^\theta &= \dfrac{\cos \theta \cos \varphi}{r}  \hat{\bf{e}}_x + \dfrac{\cos \theta \sin \varphi}{r}  \hat{\bf{e}}_y - \dfrac{\sin \theta}{r}  \hat{\bf{e}}_z, \\[0.3em]
\bf{\varepsilon}_\varphi &= - \dfrac{\sin \varphi}{r\sin \theta} \hat{\bf{e}}_x + \dfrac{\cos \varphi}{r \sin \theta} \hat{\bf{e}}_y.
\end{aligned}
$$

이다. 즉

$$
\begin{aligned}
g_{11} &= \bf{\varepsilon}_r \bf{\cdot \varepsilon}_r = 1, \\[0.3em]
g_{22} &=  \bf{\varepsilon}_\theta \bf{\cdot \varepsilon}_\theta = r^2, \\[0.3em]
g_{33} &=  \bf{\varepsilon}_\varphi \bf{\cdot \varepsilon}_\varphi = r^2 \sin^2 \theta.
\end{aligned}
$$

이며 다른 $g_{ij}=0$ 이다. 이를 행렬로 표현하면 아래와 같다. 

$$
[g_{ij}] = \begin{bmatrix} 1 & 0 & 0 \\ 0 & r^2 & 0 \\ 0 & 0 & r^2 \sin^2\theta\end{bmatrix},\qquad [g^{ij}] = \begin{bmatrix} 1 & 0 & 0 \\ 0 & r^{-2} & 0 \\ 0 & 0 & (r \sin\theta)^{-2}\end{bmatrix}
$$

:::
</div>

</br>

### 그래디언트의 공변 표현 {#sec-Tensor_covariant_representation_of_gradient}

일반화된 좌표 $\{q^i\}$ 에 대한 스칼라 함수 $\psi$ 의 그래디언트는

$$
(\nabla \psi)_j = \dfrac{\partial \psi}{\partial q^i}\dfrac{\partial q^i}{\partial x^j}
$$

이다. @eq-Tensor_contravariant_basis_vector 을 이용하면

$$
\nabla \psi = \dfrac{\partial \psi}{\partial q^i}\dfrac{\partial q^i}{\partial x^j}\hat{\bf{e}}_j = \dfrac{\partial \psi }{\partial q^i}\bf{\varepsilon}^i
$$ {#eq-Tensor_grandient_in_general_coordinate}

이다.

</br>

### 공변 미분 {#sec-Tensor_covariant_derivatives}

데카르트 좌표계의 표준 기저 벡터와는 다르게 공변/반변 기저 벡터 $\bf{\varepsilon}_i$/$\bf{\varepsilon}^j$ 는 모든곳에서 일정한 양이 아니다. 일단 반변 벡터의 변환에서 시작하자. 

$$
(V')^i = \dfrac{\partial x^i}{\partial q^k} V^k
$$

이며, 양변을 $q^j$ 로 미분해주면

$$
\dfrac{\partial (V')^i}{\partial q^j} = \dfrac{\partial x^i}{\partial q^k} \dfrac{\partial V^k}{\partial q^j} + \dfrac{\partial^2 x^i}{\partial q^j \partial q^k} V^k
$$

이다. @eq-Tensor_covariaint_basis_vector 로 부터

$$
\dfrac{\partial (\bf{V}')^i}{\partial q^j} = \dfrac{\partial V^k}{\partial q^j}\bf{\varepsilon}_k + V^k \dfrac{\partial \bf{\varepsilon}_k}{\partial q^j}
$$ {#eq-Tensor_covariant_derivative_1}

임을 안다.

여기서 $\partial \bf{\varepsilon}_k/\partial q^j$ 를 $\{\bf{e}_{\mu}\}$ 기저에 대해 전개한다면 **2종 크리스토펠 기호(Christoffel symbols of the second kind)** $\Gamma^\mu_{jl}$ 를 도입하여 
$$
\boxed{
\dfrac{\partial \bf{\varepsilon}_k}{\partial q^j} = \Gamma^\mu_{jk}\bf{\varepsilon}_{\mu}
}
$$ {#eq-Tensor_christoffel_symbol_of_2nd_kind}

와 같이 쓸 수 있다. 공변기저와 반변기저의 직교성(@eq-Tensor_inner_product_of_two_basis_vector) 을 생각하면

$$
\boxed{
    \Gamma^m_{jk} := \bf{\varepsilon}^m \bf{\cdot} \dfrac{\partial \bf{\varepsilon}_k}{\partial q^j}
}
$$ {#eq-Tensor_christoffel_symbol_of_2nd_kind_2}

임을 안다. 또한

$$
\boxed{
\Gamma^m_{jk} = \Gamma^m_{kj}}
$$ {#eq-Tensor_christoffel_symbol_of_2nd_kind_3}

임을 보일 수 있다. (@exr-Arfken_4_3_4)

@eq-Tensor_covariant_derivative_1 에 @eq-Tensor_christoffel_symbol_of_2nd_kind 를 대입하면

$$
\dfrac{\partial \bf{V}'}{\partial q^j} = \dfrac{\partial V^k}{\partial q^j}\bf{\varepsilon}_k + V^k \Gamma^m_{jk}\bf{\varepsilon}_m 
$$

이며 우변의 두번째 항의 더미 인덱스 $k,\, m$ 을 서로 바꾸면

$$
\dfrac{\partial \bf{V}'}{\partial q^j} = \left(\dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{jm}\right) \bf{\varepsilon}_k
$$ {#eq-Tensor_covariant_derivative_2}

위 식 @eq-Tensor_covariant_derivative_2 의 $(\cdots)$ 을 $\bf{V}$ 에 대한 **공변 미분(covariant derivative)** 이라고 한다. 공변 미분에 대해 아래와 같은(아프켄의 표현을 빌자면 어색한(awkward)) 표기법이 표준적으로 널리 사용된다고 한다.

$$
V^k_{;j} := \dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{jm},\qquad \text{so }\quad \dfrac{\partial \bf{V}'}{\partial q^j} = V^k_{;j}\bf{\varepsilon}_k.
$$ {#eq-Tensor_covariant_derivative_3}

위의 표현은 반변 벡터에 대한 공변 미분이다. 공변 벡터에 대한 공변 미분은 연습문제(@exr-Arfken_4_3_6) 로 넘긴다.

</br>

::: {.callout-note icon="false"}

#### 주의

@eq-Tensor_covariant_derivative_3 에서 $\dfrac{\partial V^k}{\partial q^j}$ 와 $\Gamma^k_{jm}$ 의 인덱스 모양을 보면 텐서 같지만 텐서가 가져야 할 변환 규칙을 따르지 않기 때문에 텐서가 아니다. 오직 @eq-Tensor_covariant_derivative_3 형태의 값만이 탠서이다. 


:::


</br>

### 크리스토펠 기호의 계산

메트릭 텐서를 이용해 크리스토펠 기호 값을 편하게 계산할 수 있다. 우선 1종 크리스토펠 기호를 다음과 같이 정의한다.

$$
\boxed{
[ij,\,k] := g_{mk}\Gamma^m_{ij}
}
$$ {#eq-Tensor_definition_of_christoffel_symbol_of_first_kind}

@eq-Tensor_christoffel_symbol_of_2nd_kind_3 로부터 $[ij,k] = [ji,k]$ 임을 안다. <u>참고로 2종 크리소토펠 기호와 마찬가지로 1종 크리스토펠 기호도 텐서가 아니다.</u>

우선
$$
[ij, k]  = g_{mk}\Gamma^{m}_{ij} = g_{mk} \bf{\varepsilon}^m \bf\cdot \dfrac{\partial \bf{\varepsilon}_i}{\partial q^j} = \bf{\varepsilon}_k \bf{\cdot}  \dfrac{\partial \bf{\varepsilon}_i}{\partial q^j}
$$ {#eq-Tensor_1st_kind_christoffel_symbol}

임을 안다. 또한 $g_{ij}= \bf{\varepsilon}_i \bf{\cdot \varepsilon}_j$ 이므로

$$
\dfrac{\partial g_{ij}}{\partial q^k} = \dfrac{\partial \bf{\varepsilon}_i}{\partial q^k} \bf{\cdot \varepsilon}_j + \bf\varepsilon_i \bf{\cdot}\dfrac{\partial \bf{\varepsilon}_j}{\partial q^k} = [ik, j] + [jk, i]
$$ {#eq-Tensor_derivative_of_metric_tensor_and_1st_kind_christoffel_symbol}

임을 안다. 이로부터

$$
\begin{aligned}
\dfrac{1}{2}\left[\dfrac{\partial g_{ik}}{\partial q^j} + \dfrac{\partial g_{jk}}{\partial q^i} - \dfrac{\partial g_{ij}}{\partial q^k}\right] = [ij, k]
\end{aligned}
$$ {#eq-Tensor_derivative_of_metric_tensor_and_1st_kind_christoffel_symbol_2}

을 얻는다. 이제 @eq-Tensor_definition_of_christoffel_symbol_of_first_kind 의 양 변에 $g^{nk}$ 를 곱하고 $k$ 에 대해 더해보자. 좌변에 대해서는 $\sum_k [ij, k]g^{nk}$ 이며 우변에 대해서는

$$
g^{nk}g_{mk}\Gamma^m_{ij} = \delta^n_m \Gamma^m_{ij} =  \Gamma^n_{ij}
$$

이므로 $\Gamma^n_{ij} = \sum_k g^{nk}[ij,k]$ 을 얻는다. @eq-Tensor_derivative_of_metric_tensor_and_1st_kind_christoffel_symbol_2 를 사용하고, 아인슈타인 합 규칙을 사용해 $\sum_k$ 를 제거하면

$$
\boxed{
\Gamma^n_{ij} = \dfrac{1}{2}g^{nk}\left[\dfrac{\partial g_{ik}}{\partial q^j} + \dfrac{\partial g_{jk}}{\partial q^i} - \dfrac{\partial g_{ij}}{\partial q^k}\right] }
$$ {#eq-Tensor_1st_and_2nd_christoffel_symbol}

이다. 이제 우리는 메트릭 텐서와 메트릭 텐서의 미분으로 부터 크리스토펠 기호의 값을 구할 수 있게 되었다. 

</br>

### 텐서 미분 연산자 {#sec-Tensor_tensor_derivative_operator}


... to be done ...


</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_1}
#### Arfken 4.3.1

3차원 공간에서 $\bf{\varepsilon}_1,\, \bf\varepsilon_2,\, \bf\varepsilon_3$ 가 right-handed 시스템을 이루며 수직이라고 하자. 

$$
\bf\varepsilon^i = \dfrac{\bf\varepsilon_j \times \bf{\varepsilon}_k}{\bf{\varepsilon}_j \times \bf\varepsilon_k \cdot \bf\varepsilon_i},\qquad i,\,j,\,k=1,\,2,\,3 \text{ and cyclic permutation}
$$

임을 보여라.


:::

</div></br>

::: {.solution}

$\bf\varepsilon_m\bf{\cdot \varepsilon}^i =\delta^i_m$ 이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_2}
#### Arfken 4.3.2

공변 벡터 $\bf\varepsilon_i$ 가 서로 직교할 때 다음을 보여라

&emsp;($1$) $g_{ij}$ 는 diagonal.

&emsp;($2$) $g^{ii}=1/g_{ii}$.

&emsp;($3$) $\|\bf\varepsilon^i\| = 1/\|\bf\varepsilon_i\|$. 


:::

</div></br>

::: {.solution}

($1$) $g_{ij}=\bf\varepsilon_i \bf{\cdot \varepsilon}_j$ 이므로 $g_{i\ne j}=0$.

($2$) $g^{ij}g_{jk}=\delta^i_k$.

($3$) ($2$) 로부터 $\|\bf\varepsilon^i\|^2 = 1/\|\bf\varepsilon_i\|^2$. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_3}
#### Arfken 4.3.3

@eq-Tensor_equality_of_product_of_two_innerproduct_of_basis 이 성립함을 보여라.

:::

</div></br>

::: {.solution}

$x,\,y,\,z$ 를 $x^1,\,x^2,\,x^3$ 로 표기하자. 
$$
\begin{aligned}
(\bf{\varepsilon}^i\bf{\cdot \varepsilon}^j)(\bf{\varepsilon}_j\bf{\cdot \varepsilon}_k) &= \sum_{j=1}^3\left[\sum_{m=1,2,3}\dfrac{\partial q^i}{\partial x^m} \dfrac{\partial q^j}{\partial x^m}\right]\left[\sum_{n=1,2,3}\dfrac{\partial x^n}{\partial q^j} \dfrac{\partial x^n}{\partial q^k}\right] \\[0.3em]
&= \sum_{m, n}\dfrac{\partial q^i}{\partial x^m} \underbrace{\left[\sum_j\dfrac{\partial q^j}{\partial x^m}\dfrac{\partial x^n}{\partial q^j} \right]}_{\large{=\delta^n_m}}\dfrac{\partial x^n}{\partial q^k} \\[0.3em]
&= \sum_m \dfrac{\partial q^i}{\partial x^m}\dfrac{\partial x^m}{\partial q^k}  = \dfrac{\partial q^i}{\partial q^k} = \delta^i_k
\end{aligned}
$$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_4}
#### Arfken 4.3.4

$\Gamma^m_{jk} = \Gamma^m_{kj}$ (@eq-Tensor_christoffel_symbol_of_2nd_kind_3) 이 성립함을 보여라.

:::

</div></br>

::: {.solution}
@eq-Tensor_covariaint_basis_vector, @eq-Tensor_contravariant_basis_vector 으로부터 
$$
\Gamma^m_{jk} = \bf{\varepsilon}^m \bf{\cdot} \dfrac{\partial \bf{\varepsilon}_k}{\partial q^j} = \dfrac{\partial^2 x^i}{\partial q^j\partial q^k}(\bf{\varepsilon}^m \cdot {\hat{\bf{e}}}_i) =\dfrac{\partial^2 x^i}{\partial q^j\partial q^k} \dfrac{\partial q^m}{\partial x^i}
$$

이며 $j,\,k$ 를 교환해도 그 값이 바뀌지 않으므로 $\Gamma^m_{jk} = \Gamma^m_{kj}$ 임을 알 수 있다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_5}
#### Arfken 4.3.5

원통 좌표계에서의 공변 메트릭 텐서와 반변 메트릭 텐서를 구하라.

:::

</div></br>

::: {.solution}

원통 좌표계를 $(\rho,\,\theta,\,z)$ 로 표기한다. @eq-Tensor_covariaint_basis_vector 로 부터 

$$
\begin{aligned}
\bf{\varepsilon}_\rho &= \cos\theta \hat{\bf{e}}_x + \sin \theta \hat{\bf{e}}_y, \\[0.3em]
\bf{\varepsilon}_\theta &= -\rho \sin \theta \hat{\bf{e}}_x + \rho \cos \theta \hat{\bf{e}}_y,\\[0.3em]
\bf{\varepsilon}_z &= \hat{\bf{e}}_z
\end{aligned}
$$

이다. @eq-Tensor_contravariant_basis_vector 로부터

$$
\begin{aligned}
\bf{\varepsilon}^\rho &= \cos\theta \hat{\bf{e}}_x + \sin \theta \hat{\bf{e}}_y, \\[0.3em]
\bf{\varepsilon}^\theta &= -\rho^{-1} \sin \theta \hat{\bf{e}}_x + \rho^{-1} \cos \theta \hat{\bf{e}}_y,\\[0.3em]
\bf{\varepsilon}^z &= \hat{\bf{e}}_z
\end{aligned}
$$

$$
[g_{ij}] = \begin{bmatrix} 1 & 0 & 0 \\ 0 & \rho^2 & 0 \\ 0 & 0 & 1\end{bmatrix} ,\qquad [g^{ij}] =  \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1/\rho^2 & 0 \\ 0 & 0 & 1\end{bmatrix}
$$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_6}
#### Arfken 4.3.6

공변 벡터의 공변 미분은 아래와 같다는 것을 보여라.

$$
V_{i;j} := \dfrac{\partial V_i}{\partial q^j} - V_k \Gamma^k _{ij}
$$ {#eq-Tensor_covariant_derivative_4}

:::

</div></br>

::: {.solution}

우선 $\bf{\varepsilon}^i \bf{\cdot \varepsilon}_j = \delta^i_j$ 의 양변을 미분하면 다음을 얻는다.

$$
\dfrac{\partial \bf{\varepsilon}^i}{\partial q^k} \bf{\cdot \varepsilon}_j + \bf{\varepsilon}^i \bf{\cdot}\dfrac{\partial \bf{\varepsilon}_j}{\partial q^k} = 0.
$$ {#eq-exr_Arfken_4_3_6_1}

이로부터 @eq-Tensor_christoffel_symbol_of_2nd_kind_2 은

$$
\Gamma^m_{jk} =  \bf{\varepsilon}^m \bf{\cdot} \dfrac{\partial \bf{\varepsilon}_k}{\partial q^j} = - \bf{\varepsilon}_k \bf{\cdot} \dfrac{\partial \bf{\varepsilon}^m}{\partial q^j}
$$ {#eq-exr_Arfken_4_3_6_1}

임을 안다. @eq-Tensor_inner_product_of_two_basis_vector 을 이용하면 다음을 얻는다. 

$$
\dfrac{\partial \bf{\varepsilon}^m}{\partial q^j} = - \Gamma^m_{jk} \bf{\varepsilon}^k
$${#eq-exr_Arfken_4_3_6_3}
또한

$$
(V')_i = \dfrac{\partial q^k}{\partial x^i}V_k
$$

이며

$$
\dfrac{\partial (V')_i}{\partial q^j} = \dfrac{\partial q^k}{\partial x^i}\dfrac{\partial V_k}{\partial q^j} + \dfrac{\partial^2 q^k}{\partial q^j \partial x^i}V_k
$$

이므로 @eq-Tensor_contravariant_basis_vector 로부터, 그리고 @eq-exr_Arfken_4_3_6_3 을 이용하면 

$$
\begin{aligned}
\dfrac{\partial \bf{V}'}{\partial q^j} &= \dfrac{\partial V_k}{\partial q^j}\bf{\varepsilon}^k + V_k \dfrac{\partial \bf{\varepsilon}^k}{\partial q^j} =  \dfrac{\partial V_k}{\partial q^j}\bf{\varepsilon}^k - V_k \Gamma^k_{j\mu}\bf{\varepsilon}^\mu \\[0.3em]
&= \dfrac{\partial V_i}{\partial q^j}\bf{\varepsilon}^i- V_k \Gamma^k_{ji}\bf{\varepsilon}^i = \left(\dfrac{\partial V_i}{\partial q^j}- V_k \Gamma^k_{ij}\right)\bf{\varepsilon}^i
\end{aligned}
$$ {#eq-exr_Arfken_4_3_6_4}
이다. 위 식에서 $\Gamma^k_{ji}=\Gamma^k_{ij}$ 와 dummy index 부호 변경을 사용하였다.. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_7}
#### Arfken 4.3.7

$V_{i;j}=g_{ik}V^k_{;j}$ 임을 보여라. 이를 위해

$$
\dfrac{\partial V_{i}}{\partial q^j} - V_k \Gamma^k_{ij} = g_{ik}\left[\dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{mj}\right]
$$ {#eq-exr-Arfken_4_3_7_1}

임을 보여라.

:::

</div></br>

::: {.solution}

@eq-Tensor_covariant_derivative_2 와 @eq-exr_Arfken_4_3_6_4 로 부터 

$$
\left[\dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{mj}\right]\bf\varepsilon_k = \left[\dfrac{\partial V_{k}}{\partial q^j} - V_m \Gamma^m_{kj}\right] \bf{\varepsilon}^k
$$

이며 양변에 $\bf\varepsilon_i$ 와의 내적을 취하면, 

$$
\left[\dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{mj}\right](\bf\varepsilon_k \bf{\cdot \varepsilon}_i) = \left[\dfrac{\partial V_{k}}{\partial q^j} - V_m \Gamma^m_{kj}\right] (\bf{\varepsilon}^k\bf{\cdot \varepsilon}_i)
$$

이다. $g_{ik}= (\bf\varepsilon_k \bf{\cdot \varepsilon}_i)$ 이며 $(\bf{\varepsilon}^k\bf{\cdot \varepsilon}_i) = \delta^k_i$ 이므로 @eq-exr-Arfken_4_3_7_1 을 얻는다. 이 식의 우변은 $V_{i;j}$ 이며 좌변은 $g_{ik}V^k_{:j}$ 이다. 

:::


</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_8}
#### Arfken 4.3.8

원통 좌표계의 메트릭 텐서 $g_{ij}$ 로부터 $\Gamma^k_{ij}$ 를 구하라.

:::

</div></br>

::: {.solution}

@eq-Tensor_1st_and_2nd_christoffel_symbol, @exr-Arfken_4_3_5 를 참고한다. $g^{ij}$ 가운데 편미분이 $0$ 이 아닌 것은 $g^{22}$ 뿐이므로 @eq-Tensor_1st_and_2nd_christoffel_symbol 에서 $i,\,j$ 중 하나는 무조건 $2$ 이어야 한다. 

$$
\begin{aligned}
\Gamma^\rho_{\theta \theta}&= -\dfrac{1}{2}g^{\rho \rho} \dfrac{\partial \rho^2}{\partial \rho} = -\rho \\
\Gamma^\theta_{\rho \theta}&= \Gamma^\theta_{\theta \rho} = \dfrac{1}{2}{g^{\theta \theta}} \dfrac{\partial \rho^2}{\partial \rho} = \dfrac{1}{\rho}
\end{aligned}
$$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken_4_3_9}
#### Arfken 4.3.9

@exr-Arfken_4_3_8 의 $\Gamma^k_{ij}$ 을 이용하여 벡터 $\bf{V}$ 의 원통좌표계에서의 공변 미분 $V^i_{:j}$ 를 계산하라.

:::

</div></br>

::: {.soution}

$$
V^k_{;j} := \dfrac{\partial V^k}{\partial q^j} + V^m \Gamma^k_{jm},\qquad \text{so }\quad \dfrac{\partial \bf{V}'}{\partial q^j} = V^k_{;j}\bf{\varepsilon}_k.
$$ 

$V=V^\rho\hat{\bf{e}}_\rho + V^\theta \hat{\bf{e}}_\theta +V^z \hat{\bf{e}}_z$ 이다. 
@eq-Tensor_covariant_derivative_3 을 보라.

$$
\begin{aligned}
V^\rho_{;\rho} &= \dfrac{\partial V^\rho}{\partial \rho}, \\
V^\rho_{;\theta} &= \dfrac{\partial V^\rho}{\partial \theta} + V^\theta \Gamma^\rho_{\theta \theta} =  \dfrac{\partial V^\rho}{\partial \theta} -V^\theta \rho, \\
V^\rho_{;z} &= \dfrac{\partial V^\rho}{\partial z},\\
V^\theta_{;\rho} &= \dfrac{\partial V^\theta}{\partial \rho} + V^\theta \Gamma^\theta_{\theta \rho} = \dfrac{\partial V^\theta}{\partial \rho} + \dfrac{V^\theta}{\rho},\\
V^\theta_{;\theta} &= \dfrac{\partial V^\theta}{\partial \theta} + V^\rho \Gamma^\theta_{\rho \theta}= \dfrac{\partial V^\theta}{\partial \theta} + \dfrac{V^\rho}{\rho},\\
V^\theta_{;z} &= \dfrac{V^z}{\partial z}
\end{aligned}
$$

이며 $V^z_{:i} = \dfrac{\partial V^z}{\partial q^i}$ 꼴이다. 

:::

