---
title: "군과 양자역학"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---  


{{< include ../../latexmacros.qmd >}}

</br>

## 대칭과 물리

### 슈뢰딩거 방정식과 degeneracy {#sec-Group_group_of_schroedinger_equation_and_degeneracy}
해밀토니안 $H = T+V$ 인 양자역학 시스템을 생각하자 그리고 해밀토니안 $H$ 에 어떤 기하학적인 대칭이 존재한다고 하자. 운동 에너지 $T$ 는 회전과 병진에 대해 자체로 불변이기 때문이기 때문에 해밀토니안 $H$ 에 어떤 공간대칭성이 있다면 일반적으로 포텐셜 에너지 $V$ 의 대칭성이다. 비상대론적 양자역학은 슈뢰딩거 방정식에 의해 기술된다.

$$
i\hbar \dfrac{\partial \Psi}{\partial t} = H\Psi.
$$ {#eq-Group_schroedinger_equation}

양자역학에서 변환은 유니타리 연산자에 의해 표현되는 유니타리 변환이며 유니타리 변환 $T$ 에 대해 $H$ 가 불변이라는 것은 $TH=HT$ 임을 의미한다. 그리고 이런 변환의 집합은 군을 이룬다는 것을 쉽게 보일 수 있다. 



::: {.callout-note appearance="simple" icon="false"}
::: {#def-Group_schoroedinger_equation_group}
#### 슈뢰딩거 방정식 군

슈뢰딩거 방정식에 대해 불변인 유니타리 변환의 집합을 **슈뢰딩거 방정식 군(the group of Schrödinger equation)**$^\ast$[$^\ast$ [슈뢰딩거 군(Schrödinger group)](https://en.wikipedia.org/wiki/Schrödinger_group) 과는 다르다.]{.aside} 이라고 한다(@tinkham2012group)

:::
:::


$|\Psi_n\rangle$ 이 슈뢰딩거 방정식의 고유상태로 $E_n$ 의 고유값을 갖는다고 하자. $T$ 가 슈뢰딩거 방정식군에 포함된다면

$$
HT|\Psi_n \rangle = TH |\Psi_n \rangle = E_nT|\Psi_n\rangle
$$

이므로 $T|\Psi_n\rangle$ 역시 $E_n$ 의 고유값을 갖는 슈뢰딩거 방정식의 고유상태이다. 즉 어떤 대칭성이 있을 때 degeneracy 가 발생한다. 


::: {.callout-note appearance="simple" icon="false"}
::: {#def-Group_normal_degeneracy}
#### Normal degeneracy

어떤 양자 시스템의 degeneracy 를 대칭성을 통해 이해 할 수 있을 때 이 degeneracy 를 **normal degeneracy** 라고 한다. 그렇지 않을 때는 **accidental degeneracy** 혹은 **dynamical degeneracy** 라고 한다.

:::
:::


예를 들어 수소 원자 스펙트럼에서 $2s$ 와 $2p$ 오비탈은 같은 에너지를 갖는 것으로 알려졌지만 이후 운동량 공간에서의 해밀토니안의 4차원 회전 대칭 때문임이 알려졌다$^\dagger$[$^\dagger$ Fock. *Z. Physik, **98** 145 (1935)]{.aside}. Accidental degeneracy 는 대칭성을 이용하여 이해 할 수 없기 때문에 앞으로 특별한 언급이 없는 한 모든 degeneracy 는 normal degeneracy 를 의미한다.

</br>

### 슈뢰딩거 방정식 군의 표현 {#sec-Group_representation_of_schroedinger_equation_group}

여기서는 해밀토니안 $H$ 와 이 해밀토니안에 대한 슈뢰딩거 방정식 군 $G_S$ 을 알 때 $G_S$ 의 기약표현으로부터 해밀토니안의 가능한 degeneracy 를 알 수 있다는 것을 보이고자 한다. 

우선 해밀토니안 $H$ 의 고유값 $E_n$ 에 대해 $d$-fold normal degeneracy 가 존재한다고 하자. 이 $d$ 차원 고유공간을 $\mathcal{H}_n$ 이라고 하자. 그렇다면 $d$ 개의 정규직교 고유상태 $\{|\Gamma_n1\rangle,\ldots,|\Gamma_n d\rangle\}$ 가 존재한다. 여기서 $\Gamma_n$ 은 $\mathcal{H}_n$ 에 속한다는 것을 의미하며 그 뒤의 인덱스는 고유상태의 순서를 의미한다. $\{|\Gamma_n 1\rangle,\ldots,|\Gamma_n d\rangle\}$ 에 의해 정의되는 벡터공간은 힐베르트 공간의 부분공간이며 $G_S$ 군에 속하는 모든 변환에 대한 불변 공간이다. 임의의 $T\in G_S$ 에 대해

$$
T|\Gamma_n i\rangle = \sum_{j=1}^d D^{(\Gamma_n)}(T)_{ji} |\Gamma_n j\rangle
$$ {#eq-Group_transformation_by_schroedinger_equation_group}

인 $d\times d$ 행렬 $D^{(\Gamma_n)}(T)$ 가 존재한다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-Group_transformation_by_schroedinger_equation_group_1}

@eq-Group_transformation_by_schroedinger_equation_group 의 $D^{(\Gamma_n)}$ 는 $G_S$ 에 대한 $d$ 차원 유니타리 기약표현이다.
:::

</div></br>

::: {.proof}

우선 $D^{(\Gamma_n)}$ 이 표현임을 보이자. 표기의 편의를 위해 잠시 $D=D^{(\Gamma_n)}$ 이라고 놓자. $S,\,T\in G_S$ 에 대해

$$
\begin{aligned}
ST|\Gamma_n i\rangle &= S\sum_j D(T)_{ji}|\Gamma_nj\rangle = \sum_k\sum_j D(T)_{ji}D(S)_{kj}|\Gamma_n k\rangle \\[0.3em] 
&= \sum_k\left[D(S)D(T)\right]_{ki}|\Gamma_nk\rangle
\end{aligned}
$$

이다. 즉 $D(ST) = D(S)D^{(n)}(T)$ 이므로 $D$ 은 $G_S$ 에 대한 $d$ 차원 표현이다. 

이제 $D$ 이 기약표현이 아님을 가정하자. $D$ 이 모든 $G_S$ 에 대해 블럭대각행렬이라면 어떤 $|\Gamma_ni\rangle,\, |\Gamma_nj\rangle$ 이 존재하여 모든 $T\in G_S$ 에 대해 $T|\Gamma_ni\rangle \ne |\Gamma_nj\rangle$ 이어야 한다. 그렇다면 여기에 accidental degeneracy 가 있는 것이며 normal degeneracy 라는 가정에 모순된다. 

이제 $D$ 이 유니타리 임을 보이자. 임의의 $T\in G_S$ 에 대해

$$
\begin{aligned}
\delta_{ij} &= \langle \Gamma_n j|\Gamma_n i\rangle = \langle \Gamma_nj|T^\dagger T|\Gamma_ni\rangle = \sum_{k,m} \left(D(T)_{kj}\right)^\ast D(T)_{mi}\langle \Gamma_n k|\Gamma_n m\rangle \\[0.3em]
&= \sum_{k,m} \left(D(T)_{kj}\right)^\ast D(T)_{mi}\delta_{km} = \sum_k (D(T))^\dagger_{jk}D(T)_{ki} = [D(T)^\dagger D(T)]_{ji}
\end{aligned}
$$

이므로 $\left(D(T)\right)^{-1}=D(T)^\dagger$ 이다. 즉 $D=D^{(\Gamma_n)}$ 은 $d$ 차원 유니타리 기약표현이다. $\square$

:::

</br>

이제 우리는 해밀토니안에 $d$-fold degeneracy 가 존재하면 슈뢰딩거 방정식 군에 대해 $d$ 차원 기약표현이 존재한다는 것을 안다. 이제 반대로 슈뢰딩거 방정식 군에 $d$ 차원 기약표현이 존재한다면 해밀토니안에 $d$-fold degeneracy 가 존재할까? 답은 그렇다 이다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-Group_transformation_by_schroedinger_equation_group_2}

슈뢰딩거 방정식 군 $G_S$ 에 각각의 기약표현 $\Gamma_n$ 과 그 차원 $d_n$ 에 대해  $d_n$-fold degeneracy 가 존재한다. 

:::

</div></br>

::: {.proof}

$D$ 가 $G_S$ 에 대한 $d$ 차원 기약표현이라고 하자. 모든 $T\in G_S$ 에 대해 $HT=TH$ 이며 따라서 $HD(T)= D(T)H$ 이다. 슈어 보조정리(@lem-Group_schur_lemma) 에 의해 $H$ 는 항등행렬의 상수배이므로 해밀토니안에는 $d$-fold degeneracy 가 존재한다. $\square$

:::

</br>

우리는 이로부터 다음의 결론을 내릴 수 있다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-Group_uniqueness_of_representation_of_schroedinger_group}

해밀토니안 $H$ 와 슈뢰딩거 방정식 군 $G_S$ 를 생각하자. $G_S$ 의 모든 기약표현의 차원을 알면 이 해밀토니안서 가능한 degeneracy 를 알 수 있으며 그 역도 성립한다.

:::

</div></br>

우리는 앞서 degenerated 된 상태를 $|\Gamma_n i\rangle$ 로 표기하였다. $\Gamma_n$ 은 해밀토니안의 degeneracy 에 대한 인덱스였지만 이제 이것이 기약표현의 인덱스로도 사용 될 수 있다는 것을 안다. 즉 $|\Gamma_n j\rangle$ 은 $\Gamma_n$ 기약표현에서 $j$ 번째 기저상태를 의미한다.

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Group_schroedinger_equation_group_of_triangle}

예를 들어 정삼각 형의 각 꼭지점에 동일한 이온이 존재할 때 여기서 움직이는 전자를 슈뢰딩거 방정식으로 기술한다고 하자. 이 대칭 구조는 $D_{3}$ 군으로 표현 할 수 있으며(@exm-Group_d3_multiplication_table) $D_{3}$ 는 3개의 conjugate class 를 가지므로 3개의 기약표현을 가진다. $1^2+1^2+2^2=6$ 이므로(@prp-Group_regular_representation_is_not_irreducible_3) 1차원 기약표현 2개와 2차원 기약표현 1개를 가진다는 것을 알 수 있으며 더 고도의 대칭은 군론의 입장에서 배재된다. 

:::
</div></br>

### 아벨군의 표현 {#sec-Group_representation_of_abelian_group}


아벨군은 군의 특성상 각각의 성분이 하나의 class 를 구성한다. 따라서 모든 기약표현은 1차원이며, 복소수이다. 해밀토니안의 슈뢰딩거 방정식군이 아벨군이라면 degeneracy 가 존재하지 않는다. 

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Group_abelian_schroedinger_equation_group}

#### 순환군

계수가 $n$ 인 순환군 $G=\langle g\rangle$ 을 생각하자. 표현 $D$ 에 대해 $D(g) = r$ 이라고 하자. $1=D(g^n)= \left(D(g)\right)^n = r^n$ 이므로 $r=e^{2\pi n i},\, (n=1,\ldots,\, n)$ 이다.   

원주 상의 $n$ 개의 등간격 점에 의한 포텐셜이나 periodic boundary condition 을 적용할 경우 슈뢰딩거 방정식 군이 이런 순환군이 된다. 

:::

</div>
</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Group_bloch_theorem}

#### 블로흐 정리

1차원의 경우를 생각하자. $V(x+a)=V(x)$ 라고 하자. $-a$ 만큼의 translation $T$ 에 대해 $T|x\rangle = T|x-a\rangle$ 이며, 

$$
T\psi(x) = \langle x|T|\psi\rangle = \psi(x+a)
$$

이다. 슈뢰딩거 방정식 군은 $T$ 에 의해 생성되는 무한군이다. $p$ 번째 기약표현에 의한 해를 $\psi_p$ 라고 하자.

$$
\psi_p(x+a) = T\psi(p)(x) = D^{(p)}(T)\psi_p(x) = e^{2\pi p/n}\psi_p(x)
$$

$L = an$ 으로 놓고, $k=2\pi n/L = 2\pi/a$ 로 놓으면

$$
\psi_p(x+a) = e^{2\pi p a/L}\psi_p(x) = e^{ika} \psi_p(x)
$$

이다.

$$
\psi_k (x+a) = e^{ika}\psi_k(x)
$$

이며 이런 형태의 $\psi_k(x)$ 는 다음과 어떤  $a$ 를 주기로 갖는 주기 함수 $u_k(x)$ 에 대해

$$
\psi_k(x) = u_k(x) e^{ika}
$$

로 쓸 수 있음을 안다. 

:::

</div>
</br>


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-Group_2d_rotational_group}

#### 2차원 회전군

정해진 축으로의 회전은 아벨군이다. $\varphi$ 만큼의 회전 연산을 $R(\varphi)$ 라고하면 

$$
D(R(\varphi_1))D(R(\varphi_2)) = D(R(\varphi_1+\varphi_2))
$$

임을 안다. 또한 이것을 만족시키는 표현은 정수 $n$ 에 대해 

$$
D^{(m)}(\pm \varphi) = e^{im\varphi}
$$

라는 것도 안다. 

:::

</div>
</br>

### 기약표현의 기저함수 {#sec-Group_basis_functions_for_irreducible_representations}

기약표현 $\Gamma_n$ 에 속하는(즉 $\Gamma_n$ 에 의해 표현되는 degeneratcy 에 포함되는) 기저의 한 상태 $|\Gamma_n k\rangle$ 을 생각하자. 이 기저에서 $|\Gamma_n k\rangle$ 을 제외한 기저의 상태들을 $|\Gamma_nk\rangle$ 의 **파트너(partner)** 라고 한다.


@eq-Group_transformation_by_schroedinger_equation_group 를 생각하자. 슈뢰딩거 방정식군 $G_S$ 와 $R\in G_S$ 인 연산자. 그리고 기약표현 $\Gamma_n$ 에 속한 벡터에 대해 아래와 같이 놓을 수 있다.
$$
R|\Gamma_n k\rangle  = \sum_{j=1}^{d_n} D^{(\Gamma_n)}(R)_{jk} |\Gamma_n j\rangle
$$

여기에 $D^{(\Gamma_m)}(R)^\ast_{j'k'}$ 를 곱하고 $\sum_{R\in G_S}$ 로 더하자. 위대한 직교정리(@thm-Group_great_orthogonality_theorem) 에 의해 다음이 성립한다.

$$
\begin{aligned}
\sum_{R\in G_S} D^{(\Gamma_m)}(R)^\ast_{j'k'} R|\Gamma_n k\rangle &= \sum_{j=1}^{d_n} \sum_{R\in G_S}D^{(\Gamma_n)}(R)_{jk} D^{(\Gamma_m)}(R)^\ast_{j'k'} |\Gamma_n j\rangle \\[0.3em]
&= \sum_{j=1}^{d_n} \dfrac{|G_S|}{d_n}\delta_{mn}\delta_{jj'}\delta_{kk'} |\Gamma_n j\rangle
\end{aligned}
$$

즉

$$
\sum_{R\in G_S} D^{(\Gamma_n)}(R)^\ast_{jk} R|\Gamma_n k\rangle = \dfrac{|G_S|}{d_n} |\Gamma_nj\rangle
$${#eq-Group_projection_operator_from_k_to_j_0}

이다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-Group_projection_operator}
#### Projection 연산자

Projection 연산자 $P^{(\Gamma_n)}_{jk}$ 를 아래와 같이 정의한다. 

$$
P^{(\Gamma_n)}_{jk} := \left(\dfrac{d_n}{|G_S|}\sum_{R\in G_S} D^{(\Gamma_n)}(R)^\ast_{jk} R\right).
$$ {#eq-Group_projection_operator_from_k_to_j}


:::
:::


그렇다면

$$
P^{(\Gamma_n)}_{jk}|\Gamma_n k\rangle = \left(\dfrac{d_n}{|G_S|}\sum_{R\in G_S} D^{(\Gamma_n)}(R)^\ast_{jk} R\right)|\Gamma_n k\rangle = |\Gamma_n j\rangle
$$

이다. 즉 projection 연산자 $P^{(\Gamma_n)}_{jk}$ 는 $\Gamma_n$ 기약표현의 $k$ 기저상태 를 $j$ 기저상태로 변환시켜주는 연산자이다$^{\ast}$[$^\ast$ 양자역학(혹은 선형대수학) 에서의 projection operator 와는 다르다!!!]{.aside}. 당연하게도 아래가 성립한다.

$$
\begin{aligned}
P^{(\Gamma_n)}_{jj}|\Gamma_n j\rangle &= \left(\dfrac{d_n}{|G_S|}\sum_{R\in G_S} D^{(\Gamma_n)}(R)^\ast_{jj} R\right)|\Gamma_n j\rangle = |\Gamma_n j\rangle.
\end{aligned}
$$

즉 $P^{(\Gamma_n)}_{jj}$ 는 양자역학과 선형대수학에서의 projection 연산자이며 $P^{(\Gamma_n)}_{jk}$ 는 projection 연산자의 확장판이라고 볼 수 있다.  $P^{(\Gamma_n)}_{jk}$ 를 다시 쓰면 다음과 같다.

$$
P_{jk}^{(\Gamma_n)} = |\Gamma_nj\rangle \langle \Gamma_n k|.
$$ {#eq-Group_projection_operator_in_ketbra_form}


</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-Group_uniqueness_of_representation_of_schroedinger_group}

공간 $V$ 에 작용하는 연산자에 의한 유한군 $G$ 에 대해 $\Gamma^{(1)},\ldots,\,\Gamma^{(n)}$ 이 서로 동등하지 않은 기약표현이라고 하자. $F:V \to V$ 에 대해 

$$
f_j^{(\Gamma_n)}|\Gamma_n j\rangle := F|\Gamma_n j\rangle
$$

이라면 다음이 성립한다.

$$
F = \sum_{n}\sum_{j} f_j^{(\Gamma_n)}.
$$

:::

</div></br>

::: {.proof}

@eq-Group_projection_operator_from_k_to_j 로부터

$$
P_{jj}^{(\Gamma_n)}F = \left(\dfrac{d_n}{|G_S|}\sum_{R\in G} D^{(\Gamma_n)}(R)^\ast_{jk} RF\right)
$$

이다. 

:::