---
title: "르장드르 다항식과 구면조화함수"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}


## 르장드르 다항식 {#sec-SF_legendre_polynomials}

### 라플라스 방정식과 르장드르 다항식 {#sec-SF_laplace_equation_and_legendre_polynomials}

여기서는 르장드르 다항식, 르장드르 연관 다항식, 그리고 구면조화함수에 대해 간단하게 정리한다. 자세한 내용은 @Arfken2013Mathematical, @Jackson1999Classical 등을 참고하라. 

기본적으로 구면좌표계에서 라플라스 방정식 $\nabla^2 \phi (r,\,\theta,\, \varphi) = 0$ 을 살펴보자. 우선 구면좌표계에서

$$
\nabla^2 \phi = \dfrac{1}{r}\dfrac{\partial^2}{\partial r^2}(r\phi) + \dfrac{1}{r^2 \sin \theta}\dfrac{\partial}{\partial \theta}\left(\sin \theta \dfrac{\partial \phi}{\partial \theta}\right) + \dfrac{1}{r^2 \sin^2 \theta}\dfrac{\partial^2 \phi}{\partial \varphi^2}
$$ {#eq-SF_laplace_equation_in_spherical_coordinate}

이며 변수분리법을 이용하여 $\phi (r,\, \theta,\,\varphi) = \dfrac{R(r)}{r}\Theta(\theta)\Phi(\varphi)$ 로 놓으면 위의 라플라스 방정식은 다음과 같이 변한다. 

$$
r^2 \sin^2 \theta \left[\dfrac{1}{R} \dfrac{d^2 R}{dr^2} + \dfrac{1}{\Theta r^2\sin\theta} \dfrac{d}{d\theta}\left(\sin \theta \dfrac{d\Theta}{d\theta}\right)\right] + \dfrac{1}{\Phi}\dfrac{d^2 \Phi}{d\varphi^2}=0
$${#eq-SF_laplace_equation_in_spherical_coordinate_2}


위 식에서 마지막 항 $\dfrac{1}{\Phi}\Phi''(\varphi)$ 를 보자. 여기에 $\varphi$ 의존성이 있다면 미분방정식의 앞부분에도 $\varphi$ 의존성이 있어야 하므로 변수분리 가정에 모순된다. 따라서 어떤 상수값밖에 가질 수 없다. 이 상수값을 $-m^2$ 라고 하자. 즉
$$
\dfrac{1}{\Phi}\dfrac{d^2 \Phi}{d^2\varphi} = -m^2
$$

를 얻는다. $\Phi(\varphi)= e^{\pm im\varphi}$ 이며 single-valued 이어야 하므로 $\Phi(\varphi + 2\pi) = \Phi(\varphi)$ 이어야 한다. 즉 $m$ 은 정수이다.

이제 남은 두 식은 다음과 같다.

$$
\begin{aligned}
\dfrac{1}{\sin\theta} \dfrac{d}{d\theta}\left(\sin \theta \dfrac{d\Theta}{d\theta}\right) + \left[l(l+1)- \dfrac{m^2}{\sin^2\theta}\right]\Theta &=0,  \\[0.3em]
\dfrac{d^2 R}{dr^2} - \dfrac{l(l+1)}{r^2}R &= 0.
\end{aligned}
$$

여기서 $l(l+1)$ 은 임의의 실수이다. $R(r)$ 에 대해 해는

$$
R_l(r) = a_l r^{l+1} + b_l r^{-l}
$$

이며 $\Theta$ 는 $m,\,l$ 에 대해 성립하며 역시 single valued 조건 등에 의해 $l$ 은 음이 아닌 정수이고 $m$ 은 $-l$ 부터 $l$ 까지의 값을 가질 수 있다는 것을 보일 수 있다. $m=0$ 일 경우 $l$ 값에 대한 미분방정식의 해는 뒤에 나올 르장드르 다항식 $P_l(\cos\theta)$ 이며 $m \ne 0$ 경우의 해가 연관 르장드르 다항식 $P_{l}^m(\cos \theta)$ 이다. 즉 라플라스 방정식 $\nabla^2 \phi(r,\, \theta,\, \phi)=0$ 의 해는

$$
\phi(r,\,\theta,\,\varphi) = \sum_{l=0}^\infty\sum_{m=-l}^l (a_l r^l + b_l r^{-(l+1)})P_{l}^m(\cos \theta) e^{im\varphi}
$$

로 주어진다. 이 때 구면조화함수 $Y_{l}^m(\theta,\, \varphi) := P_l^m(\cos \theta)e^{im\varphi}$ 로 정의한다. 즉

$$
\phi(r,\,\theta,\,\varphi) = \sum_{l=0}^\infty\sum_{m=-l}^l (a_l r^l + b_l r^{-(l+1)}) Y_{l}^m(\theta,\, \varphi)
$$

이다. 

</br>


### 르장드르 다항삭의 생성함수 {#sec-SF_generator_of_legendre_polynomials}

르장드르 다항식은 다음을 만족하는 $P_n(x)$ 이며 이 때 $1/\sqrt{1-2xt+t^2}$ 를 르장드르 다항식의 **생성 함수(generator)** 라고 한다.

$$
\dfrac{1}{\sqrt{1-2xt + t^2}} = \sum_{n=0}^\infty P_n (x) t^n.
$$ {#eq-SF_generator_of_legendre_polymonals}

두 벡터 $\bf{r}_>,\, \bf{r}_<$ 이 $r_> > r_<$ 라고 하자. $t=\dfrac{r_<}{r_>}$ 에 대해 

$$
\begin{aligned}
\dfrac{1}{\|\bf{r}_>-\bf{r}_<\|} &=  \dfrac{1}{r_>} \dfrac{1}{\sqrt{1-2\cos \theta t+t^2}} = \dfrac{1}{r_>}\sum_{n=0}^\infty \left(\dfrac{r_<}{r_>}\right)^n P_n (\cos \theta)
\end{aligned}
$$ {#eq-SF_legendre_expansion}

이다. 


</br>

### 르장드르 다항식의 재귀관계 {#sec-SF_recurssion_relation_of_legendre_polynomials}

&emsp;($1$) $nP_n (x) = (2n-1)xP_{n-1}(x) - (n-1)P_{n-2}(x)$,

&emsp;($2$) $xP'_n(x) - P'_{n-1}(x) = nP_n (x)$,

&emsp;($3$) $P'_n(x)- xP'_{n-1}(x) = nP_{n-1}(x)$,

&emsp;($4$) $(1-x^2)P'_n(x) = nP_{n-1}(x) - nxP_n(x)$, 

&emsp;($5$) $(2n+1)P_n(x) = P'_{n+1}(x) - P'_{n-1}(x)$, 

&emsp;($6$) $(1-x^2)P'_{n-1}(x) = nxP_{n-1}(x) - nP_n(x)$.

</br>

### 르장드르 다항식의 직교성과 반전성 {#sec-SF_orthogonality_and_parity_of_legendre_polynomials}

$$
\int_{-1}^1 P_n(x) P_m(x)\, dx = \dfrac{2}{2n+1} \delta_{mn}
$$ {#eq-SF_orthogonality_of_legendre_polynomial}

$$
P_n(-x) = (-1)^n P_n(x)
$${#eq-SF_parity_of_legendre_polynomial}

따라서 자연수 $m$ 에 대해 $P_{2m}(-x)= P_{2m}(x)$ 이고 $P_{2m+1}(0)=0$ 이다. 


</br>

### 르장드르 다항식 {#sec-SF_low_order_legendre_polynomials} 

$0$ 차에서 $5$ 차 르장드르 다항식은 다음과 같다.


$$
\boxed{
\begin{aligned}
P_0(x) &= 1, \\[0.3em]
P_1(x) &= x, \\[0.3em]
P_2(x) &= \dfrac{1}{2} (3x^2-1), \\[0.3em]
P_3(x) &= \dfrac{1}{2} (5x^3-3x), \\[0.3em]
P_4(x) &= \dfrac{1}{8}(35 x^4-30x^2 +3) , \\[0.3em]
P_5(x) &= \dfrac{1}{8}(63x^5 - 70x^3 +15x).
\end{aligned}
}
$$ {#eq-SF_legendre_polynomials}


</br>

## 연관 르장드르 연관 함수 {#sec-SF_associated_legendre_function}

### 연관 르장드르 함수의 정의 {#sec-SF_definition_of_associated_legendre_functions}
$$
\begin{aligned}
P_n^m(x) &:= (1-x)^{|m|/2} \dfrac{d^{|m|} P_n(x)}{dx^{|m|}},\\[0.3em]
P_n^{-m}(x) &:= (-1)^m \dfrac{(n-m)!}{(n+m)!} P_{n}^m (x). 
\end{aligned}
$$ {#eq-SF_definition_of_associated_legendre_polynomial}

</br>

### 연관 르장드르 함수의 직교성과 반전성 {#sec-SF_orthogonality_and_parity_of_associated_legendre_functions}

$$
\int_{-b}^b P_n^m \left(\dfrac{x}{b}\right)P_l^m \left(\dfrac{x}{b}\right)^m dx = \dfrac{2b}{2n+1}\dfrac{(n+|m|)!}{(n-|m|)!} \delta _{ln}.
$$ {#eq-SF_orthogonality_of_associated_legendre_polynomials}

$$
P_l^m(-x) = (-1)^{l-m} P_l^m(x)
$${#eq-SF_parity_of_associated_legendre_polynomials}

</br>

### 연관 르장드르 함수의 재귀관계 {#sec-SF_recursion_relations_of_associated_legendre_polynomials}

&emsp;($1$) $P_n^{m+1} (x) = \dfrac{2mx}{\sqrt{1-x^2}}P_n^m(x) + [m(m-1)-n(n+1)] P_n^{m-1}(x)$, 

&emsp;($2$) $(2n+1) xP_n^m(x) = (n+m)P_{n-1}^m (x) + (n-m+1)P_{n+1}^m (x)$, 

&emsp;($3$) $(2n+1)\sqrt{1-x^2} P_{n}^m (x) = P_{n+1}^{m+1} (x) - P_{n-1}^{m+1}(x)$,

&emsp;($4$) $2\sqrt{1-x^2} \dfrac{dP_n^m(x)}{dx} = P_{n}^{m+1}(x) - (n+m)(n-m+1)P_{n}^{m-1}(x)$.

</br>

## 구면조화함수 {#sec-SF_spherical_harmonic_functions}

### 구면조화함수의 정의 {#sec-SF_definition_of_spherical_harmonic_functions}

구면조화함수는 $(r,\, \theta,\, \varphi)$ 에 의해 기술되는 구면좌표계에서 아래와 같이 정의되는 함수이다.


$$
Y_l^m (\theta,\, \varphi) = \sqrt{\dfrac{2l+1}{4\pi}\dfrac{(l-|m|)!}{(l+|m|)!}} P_l^m(\cos\theta) e^{im\varphi}
$$ {#eq-SF_definition_of_spherical_harmomics}

</br>

### 구면조화함수의 직교성과 반전성 {#sec-SF_orthogonality_and_parity_of_spherical_harmonics}

$$
\begin{aligned}
\oint_{\Omega} {Y_{l'}^{m'}}^\ast (\theta,\, \varphi)\, Y_l^m (\theta,\, \varphi) d\Omega &=\int_0^{2\pi} \int_0^\pi  {Y_{l'}^{m'}}^\ast (\theta,\, \varphi)\, Y_l^m (\theta,\, \varphi)  \sin \theta\, d\theta d\varphi \\[0.3em]
&= \delta_{ll'}\delta_{mm'}
\end{aligned}
$$ {#eq-SF_orthogonamity_of_spherical_harmonics}

</br>

또한 같은 $l$ 에 대해 다음 관계를 만족한다.

$$
Y_l^{-m}(\theta,\, \varphi) = (-1)^mY_{l}^m (\theta,\, \varphi).
$$ {#eq-SF_similarity_of_spherical_harmonics}

그리고 $\bf{r} \mapsto -\bf{r}$ 변환에 대해 다음이 성립한다.

$$
\begin{aligned}
Y_{l}^m (-\bf{r}) &= (-1)^l Y_l^m(\bf{r})\\[0.3em]
Y_{l}^m \left(\pi - \theta,\,\varphi + \pi \right) &=(-1)^l Y_l^m(\theta,\, \varphi)
\end{aligned}
$$ {#eq-SF_parity_of_spherical_harmonics}

</br>

### 구면조화 함수의 몇가지 성질 {#sec-SF_properties_of_spherical_harmonic_functions}

$$
\begin{aligned}
{Y_{l}^m(\theta,\,\varphi)}^\ast &= (-1)^mY_{l}^{-m}(\theta,\, \varphi), \\[0.3em]
Y_l^m (0,\, \varphi) &= \sqrt{\dfrac{2l+1}{4\pi}}\delta_{m0},\\[0.3em]
Y_l^m (\pi,\,\varphi) &= (-1)^lY_{l}^m(0,\, \varphi) = (-1)^l\sqrt{\dfrac{2l+1}{4\pi}}\delta_{m0}.
\end{aligned}
$$ {#eq-SF_conjugate_of_spherical_harmonics}

</br>

### 구면조화함수의 완비성 {#sec-SF_completeness_of_spherical_harmonic_functions}

$$
\sum_{l=0}^\infty \sum_{m=-l}^l {Y_{l}^m}^\ast (\theta',\, \varphi')\,Y_l^m (\theta,\, \varphi) = \delta (\varphi - \varphi')\,\delta(\cos \theta - \cos \theta')
$$ {#eq-SF_completeness_of_spherical_harmonics}

</br>

### 구면조화함수 {#sec-SF_spherical_harmonic_functions_of_low_order} 

$$
\boxed{
\begin{aligned}
Y_0^0(\theta,\, \varphi) &= \dfrac{1}{\sqrt{4\pi}}\\[0.3em]
\hline
Y_1^1(\theta,\, \varphi) &= -\sqrt{\dfrac{3}{8\pi}} \sin \theta\, e^{i\varphi} = - \sqrt{\dfrac{3}{8\pi}}\dfrac{x+iy}{r}\\[0.3em]
Y_1^0(\theta,\, \varphi) &= \sqrt{\dfrac{3}{4\pi}}\cos\theta = \sqrt{\dfrac{3}{4\pi}}\dfrac{z}{r}\\[0.3em]
Y_1^{-1}(\theta,\, \varphi) &= \sqrt{\dfrac{3}{8\pi}} \sin \theta \, e^{-i\varphi} = - \sqrt{\dfrac{3}{8\pi}}\dfrac{x-iy}{r}\\[0.3em]
\hline
Y_2^2(\theta,\, \varphi) &=\sqrt{\dfrac{5}{96\pi}} 3 \sin \theta \cos\theta \, e^{2i\varphi} = \sqrt{\dfrac{45}{96\pi}} \dfrac{x^2-y^2+2ixy}{r^2}\\[0.3em]
Y_2^1(\theta,\, \varphi)&= -\sqrt{\dfrac{5}{24\pi}} 3 \sin \theta \cos \theta 
\, e^{i\varphi} = -\sqrt{\dfrac{5}{24\pi}} \dfrac{3z(x+iy)}{r^2}\\[0.3em]
Y_2^0(\theta,\,\varphi) &= \sqrt{\dfrac{5}{4\pi}} \left(\dfrac{3}{2} \cos^2 \theta -\dfrac{1}{2}\right) = \sqrt{\dfrac{5}{4\pi}} \left(\dfrac{3}{2}\left(\dfrac{z}{r}\right)^2-\dfrac{1}{2}\right)\\[0.3em]
Y_2^{-1}(\theta,\, \varphi)&= +\sqrt{\dfrac{5}{24\pi}} 3 \sin \theta \cos \theta \, e^{-i\varphi} = +\sqrt{\dfrac{5}{24\pi}} \dfrac{3z(x-iy)}{r^2}\\[0.3em]
Y_2^{-2}(\theta,\, \varphi) &=\sqrt{\dfrac{5}{96\pi}} 3 \sin \theta \cos\theta \,e^{-2i\varphi} = \sqrt{\dfrac{45}{96\pi}} \dfrac{x^2-y^2-2ixy}{r^2}\\[0.3em]
\hline
Y_3^{3}(\theta,\, \varphi) &= -\sqrt{\dfrac{7}{2880\pi}} 15 \sin^3 \theta \,e^{3i\varphi} = - \sqrt{\dfrac{7}{2880\pi}} \dfrac{15(x^3-3xy^2 + i(3x^2y-y^3))}{r^3} \\[0.3em]
Y_3^{2}(\theta,\,\varphi) &= \sqrt{\dfrac{7}{480\pi}} 15 \cos \theta \sin^2\theta \,  e^{2i\varphi} = \sqrt{\dfrac{7}{480 \pi}} \dfrac{15z(x^2-y^2+2ixy)}{r^3} \\[0.3em]
Y_3^1(\theta,\,\varphi) &= -\sqrt{\dfrac{7}{48 \pi}} \left(\dfrac{15}{2}\cos^2 \theta -\dfrac{3}{2}\right) \sin \theta \, e^{i\varphi} = - \sqrt{\dfrac{7}{48 \pi}} \left(\dfrac{15}{2}z^2-\dfrac{3}{2}r^2\right) \dfrac{x+iy}{r^3} \\[0.3em]
Y_3^0(\theta,\,\varphi) &= \sqrt{\dfrac{7}{4 \pi}} \left(\dfrac{5}{2}\cos^3 \theta -\dfrac{3}{2}\cos \theta\right) =  \sqrt{\dfrac{7}{4 \pi}} \left[\dfrac{5}{2}\left(\dfrac{z}{r}\right)^3 - \dfrac{3}{2}\dfrac{z}{r}\right]\\[0.3em]
Y_3^{-1}(\theta,\,\varphi) &= \sqrt{\dfrac{7}{48 \pi}} \left(\dfrac{15}{2}\cos^2 \theta -\dfrac{3}{2}\right) \sin \theta\, e^{-i\varphi}=  \sqrt{\dfrac{7}{48 \pi}} \left(\dfrac{15}{2}z^2-\dfrac{3}{2}r^2\right) \dfrac{x-iy}{r^3} \\[0.3em]
Y_3^{-2}(\theta,\,\varphi) &= \sqrt{\dfrac{7}{480\pi}} 15 \cos \theta \sin^2\theta \,  e^{-2i\varphi} = \sqrt{\dfrac{7}{480 \pi}} \dfrac{15z(x^2-y^2-2ixy)}{r^3} \\[0.3em]
Y_3^{3}(\theta,\, \varphi) &= \sqrt{\dfrac{7}{2880\pi}} 15 \sin^3 \theta \,e^{-3i\varphi} = - \sqrt{\dfrac{7}{2880\pi}} \dfrac{15(x^3-3xy^2 - i(3x^2y-y^3))}{r^3} \\[0.3em]
\end{aligned}
}
$$ {#eq-SF_spherical_harmonics}

</br>

### 르장드르 다항식과 구면조화함수 {#sec-SF_legendre_polynomials_and_spherical_harmonic_functions}

두 위치 벡터 $\bf{r},\, \bf{r}'$ 이 구면좌표계에서 각각 $(r,\, \theta,\, \varphi),\, (r',\, \theta',\, \varphi')$ 로 표현된다고 하자. $\bf{r}$ 과 $\bf{r}'$ 사이의 각이 $\gamma$ 일 때

$$
P_l(\cos\gamma) = \dfrac{4\pi}{2l+1} \sum_{m=-l}^l {Y_l^m}^\ast(\theta,\,\varphi') Y_l^m(\theta,\, \varphi)
$$ {#eq-SF_addition_theorem_for_spherical_harmonics}

임을 보일 수 있다. 그렇다면 @eq-SF_legendre_expansion 로부터

$$
\dfrac{1}{\|\bf{r}_> - \bf{r}_<\|} = \sum_{l=0}^\infty \sum_{m=-l}^l \dfrac{4\pi}{2l+1} \left(\dfrac{r_<^l}{r_>^{l+1}}\right) {Y_l^m}^\ast(\theta,\,\varphi') Y_l^m(\theta,\, \varphi)
$$ {#eq-SF_spherical_haromics_expansion_of_inverse_vector_difference}

이다. 


</br>