---
title: "복소 변수 이론 1"
number-sections: true
number-depth: 3
crossref:
  chapters: true
--- 


## 복소변수와 복소함수

::: {.callout-note appearance="minimal"}

::: {#def-complex_start}

#### 복소수와 복소함수의 다양한 정의들

$x,\,y\in\mathbb{R}$ 에 대해 복소수 $z=x+iy$ 를 생각 할 수 있다. 이 때 $z$ 에 대한 **conjugate** 를 $z^\ast$ 라고 표기하며 $z^\ast :=x-iy$ 로 정의된다. 복소수 $z$ 를 $r,\, \theta\in \mathbb{R}$ 에 대해 극좌표계에서 $z=re^{i\theta}$ 로 표현 할 수 있으며 $r$ 을 **modulus** 라고 하고 $\theta$ 를 **argument** 혹은 **phase** 라고 한다. 

:::

:::


</br>

### 복소 함수

어떤 함수 $f$ 가 실수에서 급수로 표현된다고 하자. $f(x)= \sum_{j=0}^\infty c_j x^j$ 이고 $x$ 의 수렴반경이 $R$ 이라고 하면 $|z|<R$ 인 복소수 $z$ 에 대해 $f(z)=\sum_{j=0}^\infty c_j z^j$ 라고 정의 할 수 있다. 예를 들어 $\exp (x)$ 는 모든 $x\in \mathbb{R}$ 에 대해 수렴하므로 모든 $z\in \mathbb{C}$ 에 대해 

$$
f(z) = 1+z+\dfrac{z^2}{2!} + \dfrac{z^3}{3!} + \cdots
$$

라고 $f:\mathbb{C} \to \mathbb{C}$ 를 정의 할 수 있다. $f:\mathbb{C}\to \mathbb{C}$ 인 경우 함수의 실수부와 허수부를 다음과 같이 나눈다.

$$
f(z) = u(z) + iv(z) \qquad \text{or}\qquad f(x,\,y) = u(x,\,y) + i v(x,\,y)
$$

이 때 $u,\, v$ 는 $\mathbb{C}\mapsto \mathbb{R}$ 함수이다.

</br>

### 복소수의 지수와 로그

$z=x+iy$ 를 극좌표계에서 $z=re^{i\theta}$ 로 표현하는 것은 1-1 대응을 이룬다. 정확히 말하면 1-1 대응을 이루도록 하기 위해 $\theta$ 의 범위를 $[0,\, 2\pi)$ 로 제한한다. 정수 $n$ 에 대해 

$$
z^n = (x+iy)^n = r^n e^{in\theta}
$$

이며 정해진 $n\in \mathbb{Z}$ 에 대해 $x+iy$ 와 $r^n e^{i n \theta}$ 는 1-1 대응을 이룬다. 그러나 $1/n$ 승의 경우는 그렇지 못한데 이는 양의 정수 $n$ 과 $n$ 보다 작은 음이 아닌 정수 $k$ 에 대해 

$$
0\le \dfrac{\theta + 2k \pi}{n} < 2\pi, \qquad \left[e^{i(\theta + 2k\pi )/n} \right]^n = e^{i\theta}
$$

가 성립하기 때문이다. 즉 $z=i = e^{i\pi/2}$ 에 대해 $e^{i\pi/4}$ 와 $e^{5i\pi/4}$ 가 제곱했을 때 $z=i$ 가 된다. 즉 복소수 $z$ 와 정수 $n$ 에 대해 $z^{1/n}$ 은 $n$ 개의 값을 가질 수 있다.

$\ln (z)$ 역시 여러 값을 가진다. $z=re^{i\theta}$ 와 정수 $k$ 에 대해 

$$
\ln (re^{i(\theta + 2k\pi)}) = \ln r +i (2k\pi +\theta) = \ln r + i\theta = \ln z
$$

이므로 $z$ 에 대한 로그함수 값은 무한개의 값을 가질 수 있다. 이렇게 어떤 함수가 여려개의 값을 가질 때 이를 **다가 함수(multivalued function)** 라고 한다. 다가함수는 엄밀한 의미에서의 함수는 아니지만 여기서는 이 용어를 사용하기로 한다.


</br>


## 코시-리만 조건 과 해석 함수

### 코시-리만 조건

::: {.callout-note appearance="minimal"}

::: {#def-differentiability_of_complex_valued_function}

#### 복소함수의 미분

$f:Z\subset \mathbb{C}\to \mathbb{C}$ 에 대해 $z\in Z$ 로 접근하는 경로와 상관 없이 아래의 극한이 존재한다면 $f$ 는 $z$ 에서 미분가능하다고 한다.

$$
\lim_{\delta z \to 0} \dfrac{f(z+\delta z)-f(z)}{\delta z}
$$

이 때 위 극한값을 $f'(z)$ 라고 표기한다.

:::

:::


$z=x+iy$ 에 대해 $x,\,y$ 의 변화량 $\delta x,\, \delta y$ 를 생각 할 수 있다. 이 때

$$
\delta z = \delta x + i \delta y
$$

이다. $f=u+iv$ 일 때 

$$
\delta f = \delta u + i \delta v
$$

라고 쓰면

$$
\dfrac{\delta f}{\delta z} = \dfrac{\delta u + i\delta v}{\delta x + i \delta y}
$$ {#eq-complex_variation_of_function}

@eq-complex_variation_of_function 을 두가지 경로에서 생각해보자. 우선  $\delta y=0$ 인 경로에서 생각하면

$$
\lim_{\delta z \to 0} \dfrac{\delta f}{\delta z} = \lim_{\delta x\to 0} \left(\dfrac{\delta u}{\delta x} + i \dfrac{\delta v}{\delta x}\right) = \dfrac{\partial u}{\partial x} + i\dfrac{\partial v}{\partial x}
$$

이며, $\delta x = 0$ 인 경로에서 생각하면 

$$
\lim_{\delta z \to 0} \dfrac{\delta f}{\delta z} = \lim_{\delta y\to 0} \left(-i\dfrac{\delta u}{\delta y} +  \dfrac{\delta v}{\delta y}\right) = -i\dfrac{\partial u}{\partial y} + \dfrac{\partial v}{\partial y}
$$

이다. $f$ 가 $z$ 에서 미분가능하다면 

$$
\dfrac{\partial u}{\partial x} = \dfrac{\partial v}{\partial y},\qquad \dfrac{\partial v}{\partial x} = -\dfrac{\partial u}{\partial y}
$$ {#eq-complex_cauchy_riemann_condition}

이어야 한다. @eq-complex_cauchy_riemann_condition 의 조건을 **코시-리만 조건 (Cauchy-Riemann condition)** 이라고 하며 코시 리만 조건은 도함수가 존재하기 위한 필요조건이다.

이제 코시 리만 조건을 만족하면 도함수가 존재하며 여기에 각각의 편도함수가 $z$ 에서 연속이라고 하자. 그렇다면 $f(x,\,y)$ 에 대해

$$
\delta f = \left(\dfrac{\partial u}{\partial x} + i \dfrac{\partial v}{\partial x}\right)\delta x + \left(\dfrac{\partial u}{\partial y} + i \dfrac{\partial v}{\partial y}\right)\delta y
$$

이며 여기에 코시-리만 조건을 적용하면

$$
\begin{aligned}
\delta f &= \left(\dfrac{\partial u}{\partial x} + i \dfrac{\partial v}{\partial x}\right)\delta x + \left(- \dfrac{\partial v}{\partial x} + i \dfrac{\partial u}{\partial x}\right)\delta y \\
&= \left(\dfrac{\partial u}{\partial x} + i \dfrac{\partial v}{\partial x}\right)(\delta x +i\delta y) 
\end{aligned}
$$

이므로

$$
\dfrac{d f}{d z} = \dfrac{\partial u}{\partial x} + i \dfrac{\partial v}{\partial x} = \dfrac{\partial v}{\partial y} - i\dfrac{\partial u}{\partial y}
$$ {#eq-complex_derivative_of_complex_function}

이다. @eq-complex_derivative_of_complex_function 은 $\delta x$ 와 $\delta y$ 의 상대적인 값에 무관하며 따라서 경로에 무관하다. 즉 $f$ 에 대한 $z$ 에서의 미분값이 존재한다.

</br>

### 해석 함수

::: {.callout-note appearance="minimal"}

::: {#def-complex_analytic_function}

#### 해석 함수, 전해석 함수, 특이점

복소평면의 어떤 열린 부분집합 $U \subset \mathbb{C}$ 에서 정의된 함수 $f:U \to \mathbb{C}$ 가 각각의 $z\in U$ 에서 미분가능하며, 다가 함수(multivalued function) 가 아닐 때 이 함수를 **해석 함수(analytic function)** 라고 한다. $U=\mathbb{C}$ 일 때 이 함수를 **전해석 함수(entire function)** 이라고 한다. $z_0\in Z$ 에서 도함수가 존재하지 않을 경우 이 $z_0$ 를 **특이점 (singular point)** 라고 한다.

:::

:::


</br>

실함수와 구별되는 복소함수의 가장 큰 특징을 나열하고자 한다. 여기에 대한 증명은 복소해석학의 다양한 교과서를 참고하라. 


::: {#prp-complex_properties_of_analytic_function}

복소평면의 열린 부분집합 $U\subset C$ 에서 정의된 $f:U \to \mathbb{C}$ 에 대해 다음은 동치이다.

&emsp;($1$) $f$ 는 해석함수이다.

&emsp;($2$) 모든 $z\in U$ 에서 $f$ 는 무한번 미분 가능하다.

&emsp;($3$) 모든 $z\in U$ 에서의 $f$ 의 테일러 급수는 $f(z)$ 로 수렴한다.
:::


</br>

다가 함수의 경우 range 를 제한하여 단일값을 가지도록 하고 그 제한에서 해석 함수로 사용하기도 한다. 

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-complex_zsq}

$f(z) = z^2$ 가 해석함수임을 보이자. $z=x+iy$ 라고 하면 $f(x,\,y) = (x^2-y^2)+2ixy$ 이며 

$$
\dfrac{\partial u}{\partial x}=2x = \dfrac{\partial v}{\partial y},\qquad \dfrac{\partial u}{\partial y} = -2y = -\dfrac{\partial v}{\partial x}
$$

이므로 코시-리만 조건을 만족한다. 또한 각 편미분이 연속이므로 $f(z)=z^2$ 은 전해석 함수이다.


:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-complex_conjugate_z}

$f(z) = z^\ast = x-iy$ 에 대해

$$
\dfrac{\partial u}{\partial x} = 1 \ne \dfrac{\partial v}{\partial y} = -1
$$


이므로 $f(z)$ 는 해석 함수가 아니다.

:::

</div></br>


### 해석함수와 라플라스 방정식

$f(x,\,y) = u(x,\,y) + iv(x,\,y)$ 가 $Z\subset \mathbb{C}$ 에서 해석함수라면 코시 리만 조건으로부터

$$
\dfrac{\partial^2 u}{\partial x^2} + \dfrac{\partial^2 u}{\partial y^2}=\dfrac{\partial^2 v}{\partial x^2} + \dfrac{\partial^2 v}{\partial y^2} = 0
$$

을 만족한다. 우리는 $n$ 차원 유클리드 공간에서 라플라스 방정식

$$
\nabla^2 f = \sum_{i=1}^n \dfrac{\partial^2 f}{\partial x_i^2} =  0
$$ {#eq-complex_laplace_equation}

을 만족하는 함수 $f$ 를 **조화 함수(harmonic function)** 이라고 부른다(구면 조화 함수(spherical harmonic function) 과는 완전히 다른 종류이다). 즉 해석함수의 실수부와 허수부는 2차원 조화함수이다.

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-complex1_orthoginality_of_real_and_complex_function}

$u(x,\,y)=c$ 를 만족하는 곡선 $C_u$을 생각하자. 

$$
0 = du(x,\,y) = \dfrac{\partial u}{\partial x}dx + \dfrac{\partial u}{\partial y}dy
$$

이므로 $(x_0,\,y_0) \in C_u$ 에서의 $C_u$ 의 기울기는

$$
\left(\dfrac{dy}{dx}\right)_{u} = -\dfrac{\partial u/\partial x}{\partial u/\partial y}
$$

이다. 이 $(x_0,\,y_0)$ 에 대해 $v(x_0,\,y_0) = d$ 일 때 $v(x,\,y)=d$ 를 만족하는 곡선 $C_v$ 에 대해 $(x_0,\,y_0) \in C_v$ 에서의 기울기는

$$
\left(\dfrac{dy}{dx}\right)_v = -\dfrac{\partial v/\partial x}{\partial v/\partial y} = \dfrac{\partial u/\partial y}{\partial u/\partial x} = -\left[\left(\dfrac{dy}{dx}\right)_{u}\right]^{-1}
$$

이다. 즉 $x_0,\,y_0$ 에서의 $u(x,\,y) = u(x_0,\,y_0)$ 와 $v(x,\,y) = v(x_0,\,y_0)$ 의 두 곡선은 항상 직교한다.


:::

</div></br>

### 해석함수의 미분

@eq-complex_derivative_of_complex_function 로부터

$$
f'(z) = \dfrac{df}{dz} = \dfrac{\partial f}{\partial x}
$$

임을 안다. $f(z) = z$ 일 때

$$
\dfrac{dz}{dz} = \dfrac{\partial (x+iy)}{\partial x}  = 1
$$

임을 알 수 있다. 또한 두 복소함수의 곱의 미분을 계산 할 수 있다. 

$$
\begin{aligned}
\dfrac{d}{dz}[f(z)g(z)] = \dfrac{\partial}{\partial x}[f(z)g(z)] = (\partial_x f) g + f (\partial_x g)= f'(z)g(z) +f(z)g'(z)
\end{aligned}
$$ {#eq-complex1_derivative_of_product_of_functions}

즉 실함수에서의 두 함수의 곱의 미분과 동일하다.

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-complex1_derivative_of_power}

@eq-complex1_derivative_of_product_of_functions 를 이용하여 양의 정수 $n$ 에 대해 $(z^n)' = nz^{n-1}$ 임을 보일 수 있다. Induction 을 사용한다. $n=1$ 일 경우는 이미 보였다. $(z^n)'=nz^{n-1}$ 임을 가정하면

$$
(z^{n+1})' = (z z^n)' = z^n + z(nz^{n-1})= z^{n} + nz^{n} = (n+1)z^{n+1}
$$

이다. 

:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-complex1_derivative_of_logarithm}

$\ln z = \ln r+i(\theta +2n\pi) = u+iv$ 라고 놓으면, 

$$
\dfrac{\partial u}{\partial x} = \dfrac{x}{r^2}, \qquad \dfrac{\partial u}{\partial y} = \dfrac{y}{r^2},\qquad \dfrac{\partial v}{\partial x} = - \dfrac{y}{r^2}, \qquad \dfrac{\partial v}{\partial y} = \dfrac{x}{r^2}
$$

이며 $r=0$ 을 제외하고는 코시-리만 조건을 만족한다. 따라서

$$
\dfrac{d(\ln z)}{dz} = \dfrac{\partial \ln z}{\partial x} = \dfrac{x}{r^2} - i \dfrac{y}{r^2} = \dfrac{1}{x+iy} = \dfrac{1}{z}
$$ {#eq-complex1_derivative_of_ln_z}

이다. 주의해야 할 것은 $\ln z$ 는 다가함수(multivalued function) 이므로 함수의 영역을 제한해야 해석함수가 된다. 여기에 대해서는 이후 다루기로 한다.

:::

</div></br>


### 무한원점 (Point at infinity)

복소수를 다룰 때 무한대는 하나의 점으로 다루게 되며 이 점을 무한원점이라고 한다. 무한원점의 근방(neighborhood) 를 다룰 때는 $w=1/z$ 로 변환시킨 후 $w = 0$ 근방을 다룬다. 이렇게 되면 큰 양의 실수 $R$ 에 대해 $z=-R$ 을 다룰 때 $w=1/z$ 근처의 미분을 다루게 되면 $z=R$ 이 모두 $w=1/z$ 근처에 있기 때문에 영향을 끼치게 된다. 이외의 특이한 사항에 대해서는 차후 다루기로 한다.


</br>

### 연습문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_1}

#### Arfken 11.2.1

$f(z) = \text{Re}(z)= x$ 가 해석함수인지 여부를 확인하라.

:::

::: {.solution}

$$
\partial_x u = 1 \ne \partial_y v = 0
$$

이므로 해석함수가 아니다.
:::
</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_2}

#### Arfken 11.2.2

해석함수 $w(z)$ 의 실수부 $u(x,\,y)$ 와 허수부 $v(x,\,y)$ 가 복소평면의 열린 부분집합 $U$ 에서 라플라스 방정식을 만족한다고 하자. 그렇다면 $u,\,v$ 모두 $U$ 의 내부에서 최대값 혹은 최소값을 갖지 않는다는 것을 보여라.

:::

::: {.solution}

$u$ 와 $v$ 에 대한 헤세 행렬(Hessian matrix) $H_u=\begin{bmatrix} \partial_x^2 u & \partial_x\partial_y u\\ \partial_x\partial_y u & \partial_y^2 u\end{bmatrix}$,  $H_v=\begin{bmatrix} \partial_x^2 v & \partial_x\partial_y v\\ \partial_x\partial_y v & \partial_y^2 v\end{bmatrix}$ 를 생각하자. $\det(H_u) < 0$, $\det(H_v) \le 0$ 이면 $u,\,v$ 모두 영역에서 극값을 가지 않는다. 코시-리만 조건과 라플라스 방정식을 이용하면 다음을 보일 수 있다.

$$
\begin{aligned}
\det(H_u) = (\partial_x^2u) (\partial_y^2 u)- (\partial_x \partial_y u )^2 &= - (\partial_x^2 u)^2 - (\partial_x^2 v)^2  \le 0
\end{aligned}
$$


이며 $\det(H_v) \le 0$ 도 같은 방법으로 보일 수 있다.

:::
</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_4}

#### Arfken 11.2.4

$w_1 = u(x,\,y) + i v(x,\,y)$, $w_2= w_1^\ast = u(x,\,y) - iv(x,\,y)$ 가 공통으로 해석함수가 되는 영역을 가진다면 $u(x,\,y)$ 와 $v(x,\,y)$ 는 상수임을 보여라.


:::

::: {.solution}

$w_1$ 의 코시-리만 조건으로부터 $\partial_x u = - \partial_y v$ 이며 $w_1^\ast$ 의 코시 리만 조건으로 부터 $\partial_x u = \partial_yv$ 이므로 $\partial_x u = 0$ 이다. 즉 $u=u(x)$ 이다. $w_1$ 의 코시-리만 조건으로부터 $\partial_x v =  -\partial_y u$ 이며  $w_1^\ast$ 의 코시-리만 조건으로부터 $\partial_x v = \partial_y u$ 이므로 $\partial_y u=0$ 이다. 즉 $u$ 는 상수이다. 마찬가지로 $v$ 가 상수 임을 보일 수 있다.

:::
</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_5}

#### Arfken 11.2.5

$f(z) = 1/(x+iy)$ 에 대해 $1/z$ 가 $z=0$ 을 제외하고는 전해석 함수 임을 보여라. 이를 이용하여 $n\in \mathbb{Z}_+$ 에 대해 $z^{-n}$ 가 $z=0$ 을 제외한 영역에서의 해석함수 여부까지 확장하라.


:::

::: {.solution}

$f(z) = \dfrac{x}{x^2+y^2} - i \dfrac{y}{x^2+y^2}$ 이며,

$$
\dfrac{\partial u}{\partial x} = \dfrac{-x^2+y^2}{(x^2+y^2)^2},\, \dfrac{\partial u}{\partial y} =  -\dfrac{2xy}{(x^2+y^2)^2},\, \dfrac{\partial v}{\partial x} = \dfrac{2xy}{(x^2+y^2)^2},\, \dfrac{\partial v}{\partial y} = \dfrac{-x^2+y^2}{(x^2+y^2)^2} 
$$

이므로 $z=0$ 을 제외한 영역에서 코시-리만 조건을 만족하며, 모든 편도함수가 연속임을 알 수 있다. $f'=\partial_xu + i \partial_y u$ 므로

$$
\dfrac{d}{dz}\left(\dfrac{1}{z}\right) = \dfrac{-x^2+y^2 + i2xy}{(x^2+y^2)^2}= - \dfrac{(x-iy)^2}{(x^2+y^2)} = - \dfrac{1}{z^2}
$$

이다. 즉 $(z^{-1})' = -1/z^2$ 임을 알 수 있다. 이제 양의 정수 $n$ 에 대해 $(z^{-n})'  = -nz^{-(n+1)}$ 임을 induction 을 이용하여 보이자. $n=1$ 일 때 성립하며

$$
(z^{-(n+1)})' = \dfrac{d}{dz}\left(\dfrac{1}{z} z^{-n}\right)  = - \dfrac{1}{z^2} z^{{-n}} - \dfrac{1}{z}nz^{-(n+1)}= -(n+1) z^{-(n+2)}
$$

이다. 

이제 $f(z) = z^{-n}$ 함수의 해석 함수 여부를 따져 보자. 

$$
f(z) = \dfrac{1}{(x+iy)^n} = \dfrac{(x-iy)^n}{(x^2+y^2)^n}
$$

이며 $n=1$ 일 때와 마찬가지로 $z\ne 0$ 에서 해석함수 임을 보일 수 있다.

:::
</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_7}

#### Arfken 11.2.7

$f(re^{i\theta})= R(r,\,\theta) e^{i\Theta(r,\,\theta)}$ 를 생각한다. 여기서 $R(r,\,\theta),\,\Theta(r,\,\theta)$ 미분 가능한 실함수이다. 이 때 극좌표계에서의 코시 리만 조건은 다음과 같음을 보여라.

$$
\dfrac{\partial R}{\partial r}= \dfrac{R}{r} \dfrac{\partial \Theta}{\partial \theta},\qquad \dfrac{1}{r} \dfrac{\partial R}{\partial \theta} = - R\dfrac{\partial \Theta}{\partial r}
$$ {#eq-complex1_cauchy_riemann_condition_in_polar_coordinate}

:::

::: {.solution}
 
$$
\begin{aligned}
\dfrac{\partial u}{\partial r} &= \dfrac{\partial u}{\partial x}\dfrac{\partial x}{\partial r} + \dfrac{\partial u}{\partial y}\dfrac{\partial y}{\partial r} = \cos \theta \dfrac{\partial u}{\partial x} + \sin \theta \dfrac{\partial u}{\partial y}, \\
\dfrac{\partial v}{\partial \theta} &= \dfrac{\partial v}{\partial x}\dfrac{\partial x}{\partial \theta} + \dfrac{\partial v}{\partial y}\dfrac{\partial y}{\partial \theta} = -r \sin \theta \dfrac{\partial v}{\partial x} + r \cos \theta \dfrac{\partial v}{\partial y}  \\
&= r\sin \theta \dfrac{\partial u}{\partial y } + r\cos\theta \dfrac{\partial u}{\partial x} = r \dfrac{\partial u}{\partial r}, \\
\dfrac{\partial v}{\partial r} &= \dfrac{\partial v}{\partial x}\dfrac{\partial x}{\partial r} + \dfrac{\partial v}{\partial y}\dfrac{\partial y}{\partial r} = \cos \theta \dfrac{\partial v}{\partial x} + \sin \theta \dfrac{\partial v}{\partial y} \\
\dfrac{\partial u}{\partial \theta} &= \dfrac{\partial u}{\partial x}\dfrac{\partial x}{\partial \theta} + \dfrac{\partial u}{\partial y}\dfrac{\partial y}{\partial \theta} = -r \sin \theta \dfrac{\partial u}{\partial x} + r \cos \theta \dfrac{\partial u}{\partial y}  \\
&= -r\sin \theta \dfrac{\partial v}{\partial y } - r\cos\theta \dfrac{\partial v}{\partial y} = -r \dfrac{\partial v}{\partial r}, \\
\end{aligned}
$$

즉, 

$$
\dfrac{\partial u}{\partial r} = \dfrac{1}{r}\dfrac{\partial v}{\partial \theta},\qquad \dfrac{\partial v}{\partial r} = - \dfrac{1}{r} \dfrac{\partial u}{\partial \theta}
$$

이다. $u=R\cos \Theta,\, v = R \sin \Theta$ 이므로, 

$$
\begin{aligned}
\dfrac{\partial R}{\partial r} \cos \Theta - R \sin \Theta \dfrac{\partial \Theta}{\partial r} &= \dfrac{1}{r} \dfrac{\partial R}{\partial \theta} \sin \Theta + \dfrac{R}{r} \cos \Theta \dfrac{\partial\Theta}{\partial \theta}, \\
\dfrac{\partial R}{\partial r} \sin \Theta + R \cos \Theta \dfrac{\partial \Theta}{\partial r} &= -\dfrac{1}{r} \dfrac{\partial R}{\partial \theta} \cos \Theta + \dfrac{R}{r} \sin \Theta \dfrac{\partial\Theta}{\partial \theta}.
\end{aligned}
$$

이다. 이로부터,

$$
\dfrac{\partial R}{\partial r} = \dfrac{R}{r}\dfrac{\partial \Theta}{\partial \theta},\qquad \dfrac{1}{r}\dfrac{\partial R}{\partial \theta} = - R \dfrac{\partial \Theta}{\partial r}
$$

을 얻는다. 


:::
</div></br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-Arfken7_11_2_8}

#### Arfken 11.2.8

@exr-Arfken7_11_2_7 의 $\Theta (r,\,\theta)$ 는 극좌표계에서의 라플라스 방정식

$$
\dfrac{\partial^2 \Theta}{\partial r^2} + \dfrac{1}{r} \dfrac{\partial \Theta}{\partial r} + \dfrac{1}{r^2} \dfrac{\partial^2 \Theta}{\partial \theta^2} = 0
$$

을 만족함을 보여라.

:::

::: {.solution}
 
$$
\begin{aligned}
\dfrac{\partial^2 \Theta}{\partial r^2} &= \dfrac{\partial}{\partial r}\left(- \dfrac{1}{rR} \dfrac{\partial R}{\partial \theta}\right)  = \dfrac{1}{r^2R}\dfrac{\partial R}{\partial\theta} + \dfrac{1}{rR^2}\dfrac{\partial R}{\partial r} \dfrac{\partial R}{\partial \theta} - \dfrac{1}{rR}\dfrac{\partial^2 R}{\partial r \partial \theta} \\
&= - \dfrac{1}{r} \dfrac{\partial \Theta}{\partial r}  - \dfrac{1}{r} \dfrac{\partial \Theta}{\partial \theta}\dfrac{\partial \Theta}{\partial r} - \dfrac{1}{rR}\dfrac{\partial^2 R}{\partial r \partial \theta} 
\end{aligned}
$$

이며 여기서

$$
\begin{aligned}
\dfrac{\partial^2 R}{\partial r \partial \theta} &= \dfrac{\partial}{\partial \theta}\left(\dfrac{R}{r} \dfrac{\partial \Theta}{\partial \theta}\right) = \dfrac{1}{r} \dfrac{\partial R}{\partial \theta}\dfrac{\partial \Theta}{\partial \theta} + \dfrac{R}{r} \dfrac{\partial^2 \Theta}{\partial \theta^2} \\
&= -R \dfrac{\partial \Theta}{\partial r} \dfrac{\partial \Theta}{\partial \theta} + \dfrac{R}{r}\dfrac{\partial^2 \Theta}{\partial^2 \theta} 
\end{aligned}
$$

이므로, 

$$
\dfrac{\partial^2 \Theta}{\partial r^2} = - \dfrac{1}{r}\dfrac{\partial \Theta}{\partial r} -\dfrac{1}{r}\dfrac{\partial \Theta}{\partial \theta} \dfrac{\partial \Theta}{\partial r} + \dfrac{1}{r}\dfrac{\partial \Theta}{\partial \theta} \dfrac{\partial \Theta}{\partial r}- \dfrac{1}{r^2} \dfrac{\partial^2 \Theta}{\partial \theta^2} =  - \dfrac{1}{r}\dfrac{\partial \Theta}{\partial r} - \dfrac{1}{r^2} \dfrac{\partial^2 \Theta}{\partial \theta^2} 
$$

이다. 주어진 식을 만족한다.

:::
</div></br>